src/components/UserProfile.tsx, src/services/profiles.ts
depends on https://github.com/overture-stack/persona/pull/27
=> update to camelCase

src/components/Join.js, src/components/forms/SelectRoleForm.js, src/components/loginButtons/DeleteButton.js, src/stateProviders/provideLoggedInUser.js, src/theme/defaultTheme.js
one day i will stop fiddling with this form
=> :bug: fix select role inital validate

src/components/Join.js, src/components/Login.js, src/components/LogoutButton.js, src/stateProviders/provideLoggedInUser.js
requested by @joneubank. First login will save JWT to localstorage, next loads will attempt to restore user from the saved JWT.
r? @Jephuff, don't really know what I'm doing with `gapi.auth2`.
=> :floppy_disk: persist jwt to localstorage

package-lock.json, package.json, src/components/AdvancedFacetViewModal/index.js, src/components/AdvancedFacetViewModal/style.css
- updated AFV (Arranger 0.1.9)
- minor style overrides
- modal click-away implementation change to support search box in AFV
=> ⬆️ Arranger 0.1.9

src/components/forms/BasicInfoForm.js
This is why @joneubank couldn't get to 100% profile fill during the demo.
=> more role fixups so can get to 100% fill

src/components/FileRepoSidebar.js, src/services/downloadData.js
~needs https://github.com/overture-stack/arranger/pull/222~
~depends on https://github.com/overture-stack/arranger/pull/230~
=> ✨biospecimen download

src/services/downloadData.js
~needs https://github.com/overture-stack/arranger/pull/222~
~depends on https://github.com/overture-stack/arranger/pull/230~
=> ✨ clinical download family

src/components/FamilyManifestModal/DataTypeOption.js, src/components/FamilyManifestModal/FamilyManifestModal.js, src/components/FamilyManifestModal/index.js, src/components/FileRepoSidebar.js, src/components/Stats/Stats.js, src/services/downloadData.js
~depends on https://github.com/overture-stack/arranger/pull/230~
=> ✨ download manifest for family

public/index.html
=> Add the google analytics to <head> (#120)

package-lock.json, package.json, src/components/FamilyManifestModal/FamilyManifestModal.js, src/components/FileRepo.js, src/components/Stats/index.js
not sure how many participants there should be, but now it's 100
=> update stats queries

src/components/FileRepo.js
~depends on https://github.com/overture-stack/arranger/pull/249~
=> 💄 update column dropdown text

src/App.css, src/components/AdvancedFacetViewModal/style.css
=> white button background for dropdowns

src/components/FileRepo.js
depends on https://github.com/overture-stack/arranger/compare/feat/customize-filter-types?expand=1
=> ✨  pass filter types for filter

src/components/UserDashboard/MySavedQueries.js
=> line-height and margin.

src/components/Login.js, src/services/secrets.js
Issue description: Login to portal > Save Gen3 token > Logout and log back in. Gen3 token is gone.
this PR fixes this issue.
=> Bug fix for getting Gen3 token on logout

src/components/Header.js, src/components/forms/BasicInfoForm.js
=> Changed Role Label

src/components/UserDashboard/MySavedQueries.js, src/components/UserDashboard/index.js
i thought my prettier was messing up the indent spaces, so I did install prettier-atom but it did the same spacing /shrug
=> :sparkles: delete saved query from dashboard

src/components/UserDashboard/MySavedQueries.js, src/stateProviders/provideSavedQueries.js
=> 219 dont over re-fetch mysavedqueries

src/components/Join.js, src/uikit/Wizard.js
item 5 of https://github.com/kids-first/kf-portal-ui/issues/115
=> item 5 of #115

src/theme/defaultTheme.js
dedicated to @andricDu 
before:
after:
=> 🐛 nowrap on the action button

src/App.js, src/common/injectGlobals.js, src/components/LoginPage.js, src/stateProviders/provideLoggedInUser.js
Ready to merge, after this is merged, kf-arranger can be updated to require auth
~requires https://github.com/overture-stack/arranger/pull/293~
~and https://github.com/kids-first/kf-arranger/pull/7~
=> ✨ add auth header to arranger requests

package-lock.json, package.json, src/App.js, src/components/FileRepo.js, src/components/FileRepoSidebar.js, src/components/Footer.js, src/components/Header.js, src/components/ShareSaveQuery/SaveQuery.js, src/components/ShareSaveQuery/ShareQuery.js, src/components/UserProfile/AboutMe.js, src/components/UserProfile/Settings.js, src/components/UserProfile/index.js
once this is deployed it will also adjust the number of pagination options based on the screen size
https://github.com/overture-stack/arranger/pull/304
=> ✨ scroll everything

package-lock.json, package.json, src/App.js, src/components/FileRepo.js
for if https://github.com/overture-stack/arranger/pull/267 is merged
=> ✨ remove some socket props

src/components/FamilyManifestModal/FamilyManifestModal.js, src/components/Stats/Stats.js, src/components/Stats/index.js
requires https://github.com/overture-stack/arranger/pull/299
=> 🐛 fix counts in family manifest modal

src/App.js, src/components/Page.js, src/components/SideImagePage.js
Moves some components in around to make App.js a little cleaner
=> ♻️ cleanup App.js

public/locales/en/translations.json, public/locales/fr/translations.json, src/components/FileRepo.js, src/components/FileRepoSidebar.js, src/components/Footer.js, src/components/Header.js, src/components/Join.js, src/components/Login.js, src/components/LoginPage.js, src/components/LogoutButton.js, src/components/ShareSaveQuery/SaveQuery.js, src/components/ShareSaveQuery/ShareQuery.js, src/theme/defaultTheme.js, src/uikit/EditableLabel.js
Completed all components in the /components and /components/ShareSaveQuery directories.
=> i18next translations

src/components/FamilyManifestModal/FamilyManifestModal.js
=> 🐛 this should rid us of the graphql 400?

src/stateProviders/provideSavedQueries.js
not sure why this was commented out...
=> 🐛 fixes spinning dashboard

src/App.js, src/stateProviders/provideLoggedInUser.js
=> ✨ improved routing

package-lock.json, package.json, src/App.js, src/components/DownloadManifestModal.js, src/components/FamilyManifestModal/FamilyManifestModal.js, src/components/FileRepo.js, src/components/FileRepoSidebar.js, src/components/ParticipantManifestModal.js, src/components/ShareSaveQuery/SaveQuery.js, src/components/ShareSaveQuery/ShareQuery.js, src/components/ShareSaveQuery/shortenApi.js, src/components/UserDashboard/MySavedQueries.js, src/components/UserDashboard/index.js, src/services/ajax.js, src/services/api.js, src/services/arranger.js, src/stateProviders/provideSavedQueries.js
implements custom fetcher, requires arranger update (https://github.com/overture-stack/arranger/pull/332)
=> ✨ Common api fetcher

src/services/downloadData.js
manifest download should include one file, columns changed too
=> 💄 download participant / family manifest changes

package-lock.json, package.json, src/common/translateSQONValue.js, src/components/FileRepo.js
translate sqon `set_id` values to something more user friendly.
depends on https://github.com/overture-stack/arranger/pull/339
=> ✨ translate set_id sqon values to something prettier

public/locales/en/translations.json, public/locales/fr/translations.json, src/App.js, src/components/ContextProvider.js, src/components/DownloadManifestModal.js, src/components/Header.js, src/components/Join.js, src/components/Login.js, src/components/LoginPage.js, src/components/LogoutButton.js, src/components/UploadIdsModal.js, src/components/UserProfile/AboutMe.js, src/components/UserProfile/index.js, src/components/forms/BasicInfoForm.js, src/components/forms/SelectRoleForm.js, src/components/loginButtons/DeleteButton.js, src/services/api.js, src/services/profiles.js, src/stateProviders/provideLoggedInUser.js
Mostly those called during signups
=> 🐛 tracks down more 401 cases

.env.schema, public/index.html, src/App.js, src/common/injectGlobals.js, src/components/AdvancedFacetViewModal/index.js, src/components/AdvancedFacetViewModal/style.css, src/components/FileRepo.js, src/components/Modal/index.js, src/components/SQONURL.js, src/index.js, src/services/usersnap.js, src/stateProviders/provideLoggedInUser.js, src/stateProviders/provideModalState.js, src/stateProviders/provideToast.js
Adds [UserSnap](https://usersnap.com/) feedback widget to all pages for anonymous and authenticated users.
=> Adds usersnap integration

src/services/usersnap.js
adds a conditional for the widget email field population
=> 🐛 allow anonymous portal user: UserSnap screen creation

src/services/profiles.js
createProfile was broke, data is not nested under data no more
=> 🐛 fix user create profile 

README.md
=> README Acknowledgments Section

src/components/FileRepo.js
depends on https://github.com/overture-stack/arranger/pull/363
=> 🐛 passes a ref that allows term agg to stay in view on 'less'

src/App.js, src/components/ArrangerConnectionGuard.js, src/components/FileRepo.js
if the file repo is down show an error page rather than a runtime error
=> 🐛 show a connection error page if arranger is down

package.json, public/locales/en/translations.json, public/locales/fr/translations.json, src/App.js, src/components/ContextProvider.js, src/components/Error.js, src/components/Login.js, src/components/LoginPage.js, src/components/SplashPage.js, src/services/api.js, src/services/history.js, src/stateProviders/provideLoggedInUser.js
if we fail when initializing it means a service is down, this provides a generic error page we can point to, and guards against runtime errors.
=> 🐛 better service-down handling

package-lock.json, package.json, src/components/AdvancedFacetViewModal/index.js
depends on https://github.com/overture-stack/arranger/pull/366
arranger now defaults hiding id & text, which is what we need in KF
=> 🐛 enable bool & date fields in advanced facet view

src/components/Stats/index.js
=> fixes the file size stat query

src/components/FamilyManifestModal/queries.js
this should be all that's shared
=> 🐛 matched up with new index

src/components/FileRepo.js, src/components/ShareSaveQuery/SaveQuery.js, src/components/ShareSaveQuery/ShareQuery.js
disable save / share while stats query is loading
=> 🐛 save / share should be disabled while loading stats

package-lock.json, package.json
=> ⬆️ updates arranger version

src/components/FileRepo.js, src/components/Modal/index.js, src/components/UploadIdsModal.js
requires https://github.com/overture-stack/arranger/pull/391
=> removes some dom element and sets modal maxHeight

package.json, src/components/FileRepo.js
2 things here:
- standardizes our initialization of translateSQON
- passes translateSQON to AFV 'cause it now accepts it too
depends on https://github.com/overture-stack/arranger/pull/390
=> 🐛 standardize translate SQON, pass to AFV for sqon view

src/components/Join.js, src/components/forms/SelectRoleForm.js, src/uikit/Wizard.js
pretty much the same strategy as the modal :)
=> 💄 make role select form scrollable

public/locales/en/translations.json, public/locales/fr/translations.json, src/components/UserProfile/AboutMe.js, src/components/UserProfile/InterestsAutocomplete.js, src/services/profiles.js
persona supports interests searching now - this uses that to provide a list of suggestions when entering interests. users can add their own interests by entering a new one.
=> ✨ added auto-complete interests from persona

public/locales/en/translations.json, public/locales/fr/translations.json, src/components/forms/BasicInfoForm.js
part of design review ticket but this one is a little bit of functionality to figured to make a separate PR
=> ✨ adds organization to community account edit

package-lock.json, package.json, src/components/FamilyManifestModal/FamilyManifestModal.js
depends on https://github.com/overture-stack/arranger/pull/401
=> 💄 numbers should be formatted properly

package-lock.json, package.json, src/components/ContextProvider/ContextProvider.js, src/components/ContextProvider/ScrollbarSizeProvider.js, src/components/ContextProvider/index.js, src/components/FileRepo.js
depends on https://github.com/overture-stack/arranger/pull/402
=> 💄 account for scrollbar width in non-mac-chrome browsers

public/locales/en/translations.json, public/locales/fr/translations.json, src/components/cavatica/CavaticaCopyButton.js
=> ✨ re-enable cavatica now that internal review is done

package-lock.json, package.json, src/components/FileRepo/FileRepo.js, src/components/UploadIdsModal.js, src/stateProviders/provideModalState.js
A couple things:
- arranger update to fix upload ids modal
- fixes a race condition when setting new SQON on AFV close
=> 🐛 fix some modal navigation / functionality issues

src/services/arranger.js
related to, but not the only issue causing https://github.com/kids-first/kf-portal-ui/issues/434.
Rosi is looking into the `uuid` case
=> fix the hits extraction

src/components/UserProfile/AboutMe.js, src/components/UserProfile/InterestsAutocomplete.js
fixed up some style stuff according to the new plan, and got rid of one of those pesky missing key react warnings.
the real functionality here is just highlighting tag suggestions w/ the input word
=> 💄 highlight tag suggestions

src/components/FileRepo/AggregationSidebar/AggregationSidebar.js, src/components/UploadIdsModal.js, src/stateProviders/provideModalState.js
fixed the race condition issues, and modals now provide a warning that unsaved changes may apply.
=> 🐛 fixed some modal state / history issues

public/locales/en/translations.json, public/locales/fr/translations.json, src/App.js, src/components/AdvancedFacetViewModal/style.css, src/components/FileRepo/FileRepo.js, src/components/Join.js, src/components/Modal/index.js, src/components/RoleIconButton.js, src/components/UserProfile/CompletionWrapper.js, src/components/UserProfile/InterestsAutocomplete.js, src/components/forms/SelectRoleForm.js, src/services/profiles.js, src/theme/defaultTheme.js, src/uikit/CheckboxBubble.js, src/uikit/Column.js, src/uikit/Dropdown.js, src/uikit/PillInputWithButton.js, src/uikit/Row.js, src/uikit/Select/index.js, src/uikit/TextArea.js, src/uikit/Wizard.js
I was working on mailing list subscription but will be doing import / export arranger config today. However I think there may be enough css changes here to warrant getting this in asap & continuing with the mailing list stuff later. I've commented out the mailing stuff w/ TODO notes for now until I can pick that up again.
=> 💄more css refactor + some stub-ins for mailing list subscription

src/components/AdvancedFacetViewModal/index.js, src/components/CompleteOMeter.js, src/components/DownloadManifestModal.js, src/components/FileRepo/AggregationSidebar/AggregationSidebar.js, src/components/FileRepo/FileRepo.js, src/components/FileRepoSidebar/FileManifestsDownloadInput.js, src/components/FileRepoSidebar/FileRepoSidebar.js, src/components/FileRepoSidebar/Subsection.js, src/components/Modal/index.js, src/components/Modal/ui.js, src/components/ShareSaveQuery/SaveQuery.js, src/components/ShareSaveQuery/ShareQuery.js, src/components/ShareSaveQuery/ui.js, src/components/UserDashboard/Integrations.js, src/components/UserProfile/AboutMe.js, src/theme/defaultTheme.js, src/uikit/Button.js, src/uikit/Column.js, src/uikit/Row.js
main changes:
- common action button style, use it for "all filters" button
- refactors and fixes minor afv modal styling
- update the save and share button area
=> 💄 Style/overall touchup

src/components/FileRepo/FileRepo.js
=> 🐛 fixes the table floating over other components

package-lock.json, package.json, src/components/FileRepo/FileRepo.js
merge https://github.com/overture-stack/arranger/pull/410 first and I'll bundle the arranger update in here :)
=> ✨ feeds filterInputPlaceholder

src/components/AdvancedFacetViewModal/index.js, src/components/FileRepo/AggregationSidebar/AggregationSidebar.js, src/components/FileRepo/FileRepo.js, src/uikit/Input.js
Added a FilterInput that extends the react-dom's input component for consistency.
Merge https://github.com/overture-stack/arranger/pull/413 first then I'll bundle the update in here
=> ✨ feeds custom FilterInput component to Arranger components

src/App.js, src/components/FileRepo/AggregationSidebar/AggregationSidebar.js, src/components/FileRepo/AggregationSidebar/UploadIdsButton.js, src/components/FileRepo/FileRepo.js, src/components/FileRepo/arrangerStyle.js, src/components/FileRepoSidebar/FileRepoSidebar.js, src/components/Header/index.js, src/components/Header/ui.js, src/components/Join.js, src/components/Page.js, src/components/ShareSaveQuery/ui.js, src/components/links/ToSearchPage.js, src/theme/defaultTheme.js, src/uikit/Button.js, src/uikit/Dropdown.js, src/uikit/Dropdown/index.js, src/uikit/Dropdown/ui.js, src/uikit/Row.js
was going to work on all of https://github.com/kids-first/kf-portal-ui/issues/63 but figured to take it one step at a time so the PRs are more managable.
Actually this pretty much covers everything in that issue now...
=> 💄 Overall file repo styling touchups

src/components/UserDashboard/Integrations.js, src/components/UserDashboard/MySavedQueries.js, src/components/UserDashboard/Notifications.js, src/components/UserDashboard/index.js, src/components/UserDashboard/styles.js, src/icons/SaveIcon.js, src/theme/defaultTheme.js, src/uikit/Core.js
a huge diff for a one-liner, did a fair bit of css cleanup
=> adds 'ago' to the saved queries description

package-lock.json, src/App.js, src/common/constants.js, src/components/Login.js, src/components/LogoutButton.js, src/components/UserDashboard/Integrations.js, src/components/UserDashboard/MySavedQueries.js, src/components/UserDashboard/Notifications.js, src/components/UserDashboard/index.js, src/components/UserDashboard/styles.js, src/components/UserProfile/AboutMe.js, src/components/UserProfile/Account.js, src/components/UserProfile/ConnectedWithBadge.js, src/components/UserProfile/Settings.js, src/components/UserProfile/index.js, src/components/UserProfile/ui/index.js, src/components/cavatica/CavaticaCopyButton.js, src/icons/SaveIcon.js, src/stateProviders/provideLoggedInUser.js, src/theme/defaultTheme.js, src/uikit/Button.js, src/uikit/Column.js, src/uikit/Core.js, src/uikit/Row.js, src/uikit/Tags.js
Did a bunch more css clean up, and added a 'connected with' button to the profile/settings page.
Since we don't lock a user to a specific method of logging in it simply uses the last method of login (storing the last method in localStorage to account for the re-load w/ valid token case).
=> ✨ adds connected with button to user profile page

src/services/downloadData.js
as per https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/290422965/Download+Files+Manifests#DownloadFiles/Manifests-2.DownloadParticipantManifest
=> ✨ file manifest column change requested

src/services/profiles.js
depends on https://github.com/kids-first/kf-persona being the active persona instance, which depends on https://github.com/overture-stack/persona/pull/70
=> ✨ kf-persona / persona 1.0.0 has a different tag structure

public/locales/en/translations.json, public/locales/fr/translations.json, src/components/forms/ConsentForm.js
=> Updated terms & conditions as per CHOP request

public/locales/en/translations.json, public/locales/fr/translations.json, src/components/Login.js, src/components/forms/ConsentForm.js
=> Updated Login.js language

public/locales/en/translations.json, public/locales/fr/translations.json, src/components/Login.js, src/components/UserProfile/Gen3Connection.js, src/components/UserProfile/Gen3ConnectionDetails.js, src/components/UserProfile/UserIntegrations/index.js, src/components/cavatica/CavaticaConnectModal.js, src/services/secrets.js, src/stateProviders/provideLoggedInUser.js
so the main problem was that axios turns no response into empty strings, which got saved into localStorage and picked up by the component as a truthy value even though it's not a valid token.
=> 🐛 fixes gen3 integration status

src/components/FileRepoSidebar/FileRepoSidebar.js, src/components/cavatica/CavaticaFileSummary.js, src/components/cavatica/utils.js, src/services/arranger.js
… (#545)
* implements better queries to offload aggregations to elasticsearch
=> ⚡️ implements better queries to offload aggregations to elasticsearch

src/components/FileRepo/FileRepo.js, src/components/FileRepo/customTableColumns.js, src/components/FileRepo/ui.js, src/components/UserProfile/Gen3ConnectionDetails.js, src/services/arranger.js, src/services/gen3.js, src/uikit/Core.js, src/uikit/Row.js
Basically introduced a query layer to the download column cells in the table for getting the study ID and renders download buttons or lock according to whether gen3 user has access
=> ✨ Feat/file repo table update

src/components/Footer.js, src/components/Page.js
Because wrappers solves everything in css T_T
=> 🐛 fixes the floating footer on smaller screens

src/components/FileRepo/customTableColumns.js, src/components/FileRepo/ui.js
- make the loader smaller
- only fetch when cell value changes
=> ⚡️optimizes fetching data for the download columns and some styling

package-lock.json, package.json, src/components/Header/index.js, src/uikit/Dropdown/index.js, src/uikit/Dropdown/ui.js
* Changed alignment
* Move dropdown further from side of browser
* Fix refkey to dimiss dropdown properly
* Bump Downshift version
=> 💄 ⬆️ User menu dropdown (#615)

src/components/UserProfile/FindMe.js
thin handler to track interactions with User Profile - Fine Me On card, does not track specfic fields as that’s better done through persona
=> :chart_with_upwards_trend: adds tracking to profile Find Me On

src/App.js, src/components/ContextProvider/ContextProvider.js, src/stateProviders/provideLoggedInUser.js
🐛 logs out before reloading on 401
=> 🐛 logs out and clear ego jwt from localStorage before reloading (#625)

src/components/Header/index.js
* Add override for dropdown logic
=> 🐛 Add override for dropdown logic (#639)

src/components/UserProfile/FindMe.js, src/components/UserProfile/ResearchInterests.js, src/components/UserProfile/index.js
=> 💄 Align complete-o-meter (#640)

src/common/constants.js, src/components/forms/SelectRoleForm.js
* reorder roles
* updates user role descriptions
* fixes positioning
* changes community icon color
* Revert "changes community icon color"
This reverts commit 40f0852b6527e52d7874087718f562fc96f6b275.
=> 💄 role style updates (#647)

src/components/UserProfile/FindMe.js, src/components/UserProfile/ResearchInterests.js
* Add additional buttons to Research Interests
* Add additional buttons to Find Me
=> ✨ Feature/594 add edit profile buttons (#642)

src/common/injectGlobals.js, src/components/UserDashboard/Integrations.js
* Remove links on Dashboard footer
* Add default for gen3webroot
=> :wrench: Add default for gen3 webroot (#667)

src/components/UserProfile/UserIntegrations/index.js, src/services/gen3.js
by writing token to key manager and reading from there when auth window is detected to be closed
=> 🐛 removes gen3 connect race condition

src/components/AdvancedFacetViewModal/index.js, src/components/FileRepo/AggregationSidebar/AggregationSidebar.js
updates and moves tracking props form the `AggregationsSidebar` down to the AFV modal content components
=> 📈 Analytics/afv events update

package-lock.json, package.json, src/components/FileRepo/AggregationSidebar/AggregationSidebar.js, src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js, src/components/FileRepo/AggregationSidebar/aggsConfig.js, src/uikit/Column.js, src/uikit/Row.js
We'll have to think about ways to support this from arranger later, putting this here for now.
=> 💩temporary implementation of split tabbed aggs in the portal

src/components/UserProfile/UserIntegrations/index.js, src/components/cavatica/CavaticaConnectModal.js, src/services/analyticsTracking.js
forgot to actually add the string constant for integrations event labels
=> 🐛 Gen3 analytics string constant

.env.schema, src/common/injectGlobals.js, src/components/ShareSaveQuery/ShareQuery.js
needs to add `REACT_APP_SHORTURL_RESOLVE_ROOT` to env for deploy
=> ✨ changes root for shorturl away from kf-arranger

.env.schema, package-lock.json, package.json, src/common/injectGlobals.js, src/components/FamilyManifestModal/FamilyManifestModal.js, src/components/FileRepo/AggregationSidebar/AggregationSidebar.js, src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js, src/components/FileRepo/AggregationSidebar/aggsConfig.js, src/components/Header/index.js, src/components/ShareSaveQuery/ShareQuery.js, src/components/UserProfile/UserIntegrations/index.js, src/components/cavatica/CavaticaConnectModal.js, src/services/analyticsTracking.js, src/services/api.js, src/services/gen3.js, src/services/profiles.js, src/stateProviders/provideLoggedInUser.js, src/uikit/Column.js, src/uikit/Row.js
* rendering is working
* implements the tab
* some styling
* improves scrolling behaviour
better stretch implementation
* organizations
* proper aggs orders
* latest arranger
* removes diffs
* removes info icon
* minor optimization
* optimizes rendering
* adds note
* removes extra props
* put the conditional rendering logic to its own component
* minor refactoring
* unused import
* biger tab font size
=> Updates master

src/services/analyticsTracking.js, src/services/gen3.js
* 📈track the Gen3 authorized studies per user
* :art: updated analtyics setUserDimension function
=> 📈track the Gen3 authorized studies per user (#685)

src/components/FileRepo/DownloadFileButton.js
=> fixes firefox file download (#711)

src/components/FileRepo/DownloadFileButton.js
=> 🐛 fixes firefox file download (#711)

src/components/ShareSaveQuery/SaveQuery.js, src/components/ShareSaveQuery/ShareQuery.js, src/components/ShareSaveQuery/ui.js
Ran across it while debugging something.
=> Small typo fix for CustomLightButton

src/services/usersnap.js
Putting on my mad scientist hat to do an extreme log measure :P
Can't reproduce the google button issue, so adding this for when the issue is reported again so we can see what is and isn't actually in the dom
=> 📈 adds immediate dom content to user snap

src/common/constants.js, src/components/Login.js, src/components/UserDashboard/MySavedQueries.js, src/components/UserDashboard/QueryBlock.js, src/services/riffQueries.js, src/stateProviders/provideSavedQueries.js
* Add Query component
* Add Query Block to DefaultQueries
* Style popular query heading:
* Add Query component
* Add Query Block to DefaultQueries
* Style popular query heading:
* Style file repo link
* Add sample queries
* Move prompt message
* Example queries working
* Add all example queries
* Add exampleQueries to state
* Fix display of banner
* Styling
* Styling
* Move query stuff out of profiles
* Delete defaultsavedqueries
* remove the extra hoc
* also need to update deleted queries
* cleanups
* dynamic sample query urls
* updates sample queries orders and names
* updates link color
=> ✨ Sample queries implementation (#735)

src/common/constants.js
* updates second query
* Revert "updates second query"
This reverts commit 127b3a8a44dd4c99545f6f60f16a2972f37989db.
* puts sample query fix in the right spot
=> 🐛 fixes the sample query being empty queries

src/components/AdvancedFacetViewModal/index.js
* makes the facet panel in afv bigger
* hides the doc_counts
removes the doc_counts
=> ✨ Feat/afv modal improvement (#760)

src/components/UserProfile/FindMe.js
@rosibaj can you take a look at this? I think I fixed the correct typo but the usersnap issue that was linked in #754 was for something different
=> ✏️ORCHID -> ORCId id

src/components/FileRepo/AggregationSidebar/UploadIdsButton.js, src/components/UploadIdsModal.js
Fixes #758 
updates wording on action buttons in uploads ids modal
=> 🔥 removes uploads ids filter dropdown

src/components/cavatica/CavaticaAddProject.js, src/components/cavatica/CavaticaProjects.js, src/components/cavatica/projectDescription.md, src/services/utils.js
prod preview link: https://5bb37c2267610c536e38eb7e--prod-kidsfirst-portal.netlify.com/
=> ✨ includes description for cavatica project creation

.circleci/config.yml, README.md
Adds standard CRA linting check in CircleCI. Won't be required for merge until all of the linting issues are cleaned up.
=> ✅ Add CircleCI status check

package-lock.json, package.json, src/components/FileRepo/FileRepo.js, src/components/FileRepo/ui.js
* hides the input
* updates arranger
* updates style
=> ✨ hides the input (#861)

src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js, src/components/UserProfile/FindMe.js, src/components/UserProfile/InterestsAutocomplete.js, src/components/cavatica/CavaticaExportWidget.js, src/components/cavatica/CavaticaProjects.js, src/components/forms/BasicInfoForm.js, src/uikit/Input.js
* Add icon check for FilterInput
* Dashboard add clear x for inputs
* Style input on Cavatica modal
* Change FilterInput to be TermAgg input component
* Remove unused import. CircleCI build was failing
=> Style/823 add clear input x (#854)

src/components/Header/AppsMenu.js, src/components/Header/ui.js, src/uikit/ExternalLink.js
tracks usage of the apps menu external links
=> 📈 convert apps menu links to ExternalLink

public/index.html, src/services/analyticsTracking/googleAnalytics.js
Track when a query abandonment when a user starts a query and navigates away from the page without saving or downloading it
=> 📈 updates abandoned query tracking

public/index.html, src/common/injectGlobals.js, src/components/UserProfile/UserIntegrations/index.js, src/services/analyticsTracking/googleAnalytics.js, src/services/analyticsTracking/hotjarTracking.js, src/services/analyticsTracking/index.js, src/services/analyticsTracking/trackingEventConstants.js
re-organizes the structure of the analyticsTracking service to allow for easier integration with multiple analytics tracking providers.  
🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧
@hlminh2000 don't merge this to prod until we get the go-ahead from @baileyckelly as we need to merge some wording into the Terms and Conditions before deploying Hotjar on the portal 
🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧
=> 🎨 Analytics tracking service reorg

package-lock.json, src/components/FileRepo/AggregationSidebar/AggregationSidebar.js, src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js, src/components/FileRepo/ui.js, src/components/Page.js
* Move footer to below fold (#848)
* Move footer to below fold
* add overflow none
* Fix height for file repo cont
* Fix footer space on large display
* Center loader and stop flash of footer on load
* Remove unused styled component
* Remove Fragment
* ✨ hides the input (#861)
* hides the input
* updates arranger
* updates style
* ⬆️  updates arranger (#863)
* Add HPO Phenotype facets (#868)
*  🐛 fixes the field (#871)
* Style/823 add clear input x (#854)
* Add icon check for FilterInput
* Dashboard add clear x for inputs
* Style input on Cavatica modal
* Change FilterInput to be TermAgg input component
* Remove unused import. CircleCI build was failing
* 📈 convert apps menu links to ExternalLink (#860)
* :chart_with_upwards_trend: convert apps menu links to ExternalLink component
tracks …
=> Style/848 file repo dynamic layout (#900)

package-lock.json, src/components/FileRepo/AggregationSidebar/AggregationSidebar.js, src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js, src/components/FileRepo/ui.js, src/components/Page.js
* Move footer to below fold (#848)
* Move footer to below fold
* add overflow none
* Fix height for file repo cont
* Fix footer space on large display
* Center loader and stop flash of footer on load
* Remove unused styled component
* Remove Fragment
* ✨ hides the input (#861)
* hides the input
* updates arranger
* updates style
* ⬆️  updates arranger (#863)
* Add HPO Phenotype facets (#868)
*  🐛 fixes the field (#871)
* Style/823 add clear input x (#854)
* Add icon check for FilterInput
* Dashboard add clear x for inputs
* Style input on Cavatica modal
* Change FilterInput to be TermAgg input component
* Remove unused import. CircleCI build was failing
* 📈 convert apps menu links to ExternalLink (#860)
* :chart_with_upwards_trend: convert apps menu links to ExternalLink component
tracks …
=> ✨ Style/848 file repo dynamic layout (#900) (#914)

.env.schema
Documents the .env.schema file needed to make the portal operate.
Need help with the blank descriptions.
=> 📝  Add documentation to the .env.schema

src/chartkit/components/HorizontalBar.js, src/components/UserDashboard/charts.js
links to file repo with: lower-case search values, correct diagnosis field
makes labels clickable
=> Diagnoses chart label action

src/components/UserDashboard/CavaticaProjects/NotConnected.js, src/components/UserDashboard/CavaticaProjects/index.js
=> UI touchup

src/chartkit/components/ChartLoadGate.js, src/components/UserDashboard/DashboardCardError.js, src/components/UserDashboard/index.js
looks like so, only for the charts as that's the only place we're expecting error for now.
=> simple error state for now

src/components/UserDashboard/CavaticaProjects/Create.js, src/components/UserDashboard/CavaticaProjects/ProjectList.js, src/components/UserDashboard/CavaticaProjects/index.js, src/services/analyticsTracking/googleAnalytics.js, src/services/analyticsTracking/trackingEventConstants.js, src/uikit/Multicard/index.js
adds GA tracking for Cavatica integration events 
- project link clicks 
- project creation 
- project creation cancelation
- tab navigation 
It also adds a custom GA dimension to track the number of Cavatica projects per user
=> :chart_with_upwards_trend: Analytics/cavatica integration tracking

src/chartkit/components/ProgressBar.js, src/components/UserDashboard/AuthorizedStudies/Gen3Connected.js, src/components/UserDashboard/AuthorizedStudies/Study.js, src/services/analyticsTracking/googleAnalytics.js, src/services/analyticsTracking/trackingEventConstants.js
Tracks hovers and clicks in GA for the User Dashboard Authoerized Studies card
=> :chart_with_upwards_trend: Authorized Studies Card GA tracking

src/chartkit/components/HorizontalBar.js, src/components/UserDashboard/charts.js, src/services/analyticsTracking/trackingEventConstants.js
GA tracking code for onClick and toolTip interaction for bar charts
=> :chart_with_upwards_trend: Bar Chart GA tracking

src/chartkit/components/Donut.js, src/components/UserDashboard/CavaticaProjects/ProjectList.js
quick PR to remove unused var so CicleCI stops complaining
=> 🔥 removes unused vars

src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js
Related to arranger PR https://github.com/overture-stack/arranger/pull/477/files
@hlminh2000 Following our discussion yesterday- this is the complementary PR.
=> Add # Files to Facet UI#820

README.md
Adds badges back to head of readme.
=> 🐛 Add badges back to README

src/components/FileRepo/AggregationSidebar/AggregationSidebar.js, src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js
* prevents aggs rerendering on aggs panel expansion
* adds comment
=> 🐛 prevents refetch on aggs panel expansion (#1066)

package-lock.json, package.json, src/components/EntityPage/File/index.js, src/components/FileRepo/customTableColumns.js
[MINH]: Hold off untill overture-stack/arranger#478 is merged :)
=> Feature File entity repo link

package-lock.json, package.json, src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js
* Bumbped @arrange/components to 1.3.0
* Bumbped @arrange/components to 1.3.0
* adds back the headerTitle to term aggs
=> adds "# FILES" to term aggs and bumps @arrange/components (#1085)

src/components/EntityPage/File/index.js, src/uikit/LoadingSpinner.js
Margin between the top of the page and the loader (31px) has been taken from the FileRepo page.
=> fixed #1091 - FileEntityPage loader

src/components/EntityPage/File/fileProperties.js
Fixed the link so it refer to the same url, though I've left the value of the analytics events as they were.
=> fixes #1171 - Dead link on file entity page

src/components/CohortBuilder/QueriesResolver.js, src/components/CohortBuilder/Summary/DemographicChart.js, src/components/CohortBuilder/Summary/index.js
One thing to note.
Looks like it makes more sense to pass SQON to QueriesResolver instead of to the transform functions.
I will make this change in https://app.zenhub.com/workspaces/oicr-sprints-59a846e9d6fb732a00631122/issues/kids-first/kf-portal-ui/1157 work
=> Feature - Demographic Chat Data Provider

src/components/CohortBuilder/QueriesResolver.js
@ciaranschutte I think I'm already regretting my recommendation for using class components T_T
=> ⚡️Implements memoization of query results

src/components/CohortBuilder/QueriesResolver.js, src/components/CohortBuilder/Summary/DemographicChart.js, src/components/CohortBuilder/Summary/StudiesChart.js, src/components/CohortBuilder/Summary/index.js, src/uikit/InfoBox/InfoBox/index.js
Adds data fetching to study card. Does not modify UI work done already, just moves it to it's own file.
=> #1161 data fetching study card

package-lock.json, package.json, src/components/CohortBuilder/SqonBuilder/index.js
and a bunch of updates from sqon builder
=> ✨ Implements clear all modal

src/components/CohortBuilder/ParticipantsTableView/index.js, src/components/CohortBuilder/Results.js, src/components/CohortBuilder/Summary/index.js
Uses an actual flag for no data rather than faulsey sqon, which semantically means something different. 
Falsey sqon should mean no filter, which means we should show all data, not no data
=> ♻️ move overlay to parent component

src/components/CohortBuilder/Summary/FileBreakdown.js
I saw why it was the component flow was a little confusing so submitting this PR so we can wrap this up :P
=> links to file repo from cohort builder with client-side link

src/components/CohortBuilder/Summary/FileBreakdown.js
=> removes unneeded wrapper

src/components/CohortBuilder/Categories/index.js, src/components/CohortBuilder/ParticipantsTableView/index.js, src/components/CohortBuilder/QueriesResolver.js, src/components/CohortBuilder/Results.js, src/components/CohortBuilder/Summary/DiagnosesChart.js, src/components/CohortBuilder/Summary/StudiesChart.js, src/components/CohortBuilder/Summary/index.js
=> ✨ adds name prop to QueriesResolver

src/components/CohortBuilder/Categories/index.js
Reordering to alphabetize by Display Name ( not field name)
=> adding alpha order based on display name not field order

src/components/CohortBuilder/Summary/FileBreakdown/index.js
Vincent wants the File Breakdown card renamed
=> rename for vincent

src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js
fix family id reference- i think the one on family is empty
=> update familyid field to particiapnt level

src/components/ShareSaveQuery/ShareQuery.js
updating the text on the share buttons to be more general for file repository and virtual studies
=> change social message

src/components/CohortBuilder/Summary/AgeDiagChart.js
basically shifting a chunk of bucketing logic over to the api to handle.
=> 🐛 handle age at diagnosis aggregation in gql

src/components/CohortBuilder/SqonBuilder/SqonBuilder.css, src/components/CohortBuilder/SqonBuilder/index.js
I'd appreciate it if someone not on Linux could check this is looking correct please :)
=> remove default button styling

src/components/CohortBuilder/Categories/index.js
Age related fields has been excluded, for technical and UX reasons.
See : #1459 for reference
All the other fields that are searchable by other filters are present. Performances are good.
=> Fix/1368 Search All missing fields

src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js, src/components/CohortBuilder/ParticipantsTableView/RemoveFromCohortButton.js, src/uikit/DataTable/TableToolbar/styles.js
This is by no mean a clean fix, but I have to work around react-table bugs and limitations.
To be done in a better way once react-table is updated.
=> Fix/1359 Fixed the "select all" of participant table

src/App.js, src/common/constants.js, src/components/Header/index.js
commented out because we're hiding the link still
=> updates cohort builder path to /explore

src/components/UserDashboard/charts.js
full update requires deploy of this as well: https://github.com/kids-first/kf-public-stats-api/pull/31
=> updates label to say Other Participants instead of Family Members

src/components/FileRepo/CustomColumns/ActionsColumn.js, src/components/FileRepo/FileRepo.js, src/components/FileRepo/customTableColumns.js, src/components/cavatica/CavaticaCopyButton.js, src/components/cavatica/CavaticaCopyModal.js, src/components/cavatica/CavaticaOpenModalWrapper.js
This also makes a Component that handles opening the Cavatica modal that is separate from the UI of the button.
=> :sparkles: Cavatica action per file repo row

src/components/CohortBuilder/common.js
Added validation for categories with range fields
=> Facets: When sending in an empty array, disable button #1438

package-lock.json, package.json
This would move severals tickets from In Review to Preview/QA for the next release.
=> Update @arranger/components to v.1.1.6

package-lock.json, src/components/CohortBuilder/Summary/SurvivalChart.js
Removes placeholder card over survival chart.
=> Charts now available!

src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js, src/uikit/DataTable/Table/StyleWrapper.js
this PR is connected to this ticket too:
Show only one item when they are all the same #1575
=> fix participant table ui and add tooltip

src/services/analyticsTracking/trackingEventConstants.js, src/services/virtualStudies.js
GA events for the virtualStudies service
=> 📈 Tracks Virtual Study operations

src/components/UserProfile/UserIntegrations/FenceIntegrationItem.js, src/components/cavatica/CavaticaConnectModal.js, src/services/analyticsTracking/trackingEventConstants.js, src/services/fence.js
updates GA tracking for Gen3 and DCF
=> 📈 Analytics/fence auth tracking

config/env.js, public/index.html, src/services/analyticsTracking/hotjarTracking.js, src/services/analyticsTracking/index.js
Removes the fancy scriptjs loading in favor of a plain ol' script tag in the document head.
This is a second PR related to https://github.com/kids-first/kf-portal-ui/pull/1622 to address issuess we had after rebasing the PR.
All credits goes to Ben Dolly :)
=> 🚑 fixes the loading of the hotjar js script

package-lock.json, package.json, src/App.js, src/components/AdvancedFacetViewModal/index.js, src/components/ArrangerAdmin.js, src/components/CohortBuilder/Categories/Category.js, src/components/CohortBuilder/Categories/Filter.js, src/components/CohortBuilder/Results.js, src/components/CohortBuilder/SQONProvider.js, src/components/CohortBuilder/SearchAll/QueryResultsBody.js, src/components/CohortBuilder/SearchAll/index.js, src/components/CohortBuilder/SqonBuilder/index.js, src/components/CohortBuilder/Summary/FileBreakdown/index.js, src/components/CohortBuilder/index.js, src/components/FamilyManifestModal/FamilyDataTypesStatsQuery.js, src/components/FamilyManifestModal/FamilyManifestModal.js, src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js, src/components/FileRepo/AggregationSidebar/QuickSearchBox.js, src/components/FileRepo/CustomColumns/ActionsColumn.js, src/components/FileRepo/DownloadButton.js, src/components/FileRepo/FileRepo.js, src/components/FileRepo/ui.js, src/components/FileRepoSidebar/ClinicalDownloadButton.js, src/components/FileRepoSidebar/FileRepoSidebar.js, src/components/GenerateManifestSet.js, src/components/Stats.js, src/components/UploadIdsModal.js, src/components/UserProfile/InterestsAutocomplete.js, src/services/downloadData.js, src/stateProviders/provideLoggedInUser.js
Rolling temporarily back for a release.
This commit will be reverted afterward.
=> temporarily rolling back to using @arranger/components@1.1.7

src/components/CohortBuilder/SearchAll/index.js, src/services/analyticsTracking/trackingEventConstants.js
Adds Google Analytics tracking events for category `Cohort Builder: Filters - Search All`
Events tracked:
=> 📈Analytics/cohort builder/search filters tracking

src/components/CohortBuilder/Categories/Category.js, src/components/Utils/index.js, src/services/analyticsTracking/trackingEventConstants.js, src/uikit/Dropdown/index.js
🚧 BLOCKED by: #1448 
This tracks when a user applies a category filters in the Cohort Builder. We track the the filter SQON to be added and the resulting SQON from the addition 
reference: https://github.com/kids-first/kf-user-analytics/issues/16
=> 📈 Analytics/cohort builder/facet categories tracking

package-lock.json, package.json, src/App.js, src/ErrorBoundary.js
Defaulting to existing maintenance page.
=> Improve error handling: add error boundaries for widgets #1536

package-lock.json, src/components/CohortBuilder/SQONProvider.js, src/components/CohortBuilder/index.js
Introduces a glitch when navigating back to a query that has been loaded, and then modified without being saved.
Will be fixed as part of https://github.com/kids-first/kf-portal-ui/issues/1533
=> bug/1705 - refactored the SQONProvider to have a more predictable state

src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js, src/components/CohortBuilder/ParticipantsTableView/queries.js
Replace `Diagnosis` column by `Diagnosis (Mondo)` in the Cohort Builder's Participant Table.
Also fixed the CSV export.
=> fix/1776 replace 'Diagnosis' column by 'Diagnosis (Mondo)'

src/components/CohortBuilder/VirtualStudiesMenu/index.js, src/components/CohortBuilder/VirtualStudiesMenu/index.postcss, src/store/reducers/cohortBuilder.js
Fixes:
- "Save" should not open a dialog - but simply save the study under the same name #1781 
-  Virtual studies: Add an "Edit" button #1782
=> [RELEASE] Feat/1781 save no popup

src/components/CohortBuilder/VirtualStudiesMenu/index.js
The "Open" button has already been fixed in another PR.
The "New" button is now working properly.
=> fix/1780 - 'New' button disabled when it should not

NEWS.md, package.json
- Update NEWS, preparing 2.4.0
- Update version to 2.4.0 in package.json
=> Update version to 2.4.0 and prepare release notes

docs/dev.md, src/components/CohortBuilder/VirtualStudiesMenu/index.js, src/components/CohortBuilder/VirtualStudiesMenu/index.postcss
Also add an error message if there is an error in the virtual studies (Riff/Persona error or timeout).
=> Fix/1836 Remove empty space when there is not description

src/components/CohortBuilder/VirtualStudiesMenu/index.js, src/components/CohortBuilder/VirtualStudiesMenu/index.postcss
=> fix/1866 - added "You have unsaved changes" back

src/components/EntityPage/Participant/ParticipantClinical.js
It was a state bug (I was mutating the object, so when we went back to the tab it tried recalculating the values with erroneous input)
=> fix NaN on age in participant clinical diagnoses

src/components/UserDashboard/SavedQueries/index.js
changed wrapping css to word-break. Added div and the same style to tooltip. Number of chars now calculated in JS instead of CSS
=> Fixed and ready to merge

src/components/CohortBuilder/index.js, src/components/Header/index.js
This reverts commit 6e3804994c539744af1f88a705411f5dc9e967bb.
=> Revert "removed beta from cohort builder"

NEWS.md, package.json, src/components/CohortBuilder/index.js, src/components/Header/index.js
This release introduces a bug fix.
- #1943 Put back "Beta release" banner
=> Release 2.5.1

package-lock.json, package.json
Ignore the name of the branch.
=> Bump @kf-arranger/admin-ui to 1.3.1

NEWS.md, package-lock.json, package.json
Release notes and version bump.
=> Chore/release 2.7.0

NEWS.md, package-lock.json, package.json, src/common/constants.js, src/components/EntityPage/File/index.js, src/components/EntityPage/Participant/ParticipantClinical.js, src/components/EntityPage/Participant/Utils/FamilyTable.js, src/components/EntityPage/Participant/Utils/Links.js, src/components/EntityPage/Participant/Utils/SequencingDataTable.js, src/components/EntityPage/Participant/Utils/prettifyAge.js, src/components/UserDashboard/SavedQueries/index.js, src/services/arranger/participantEntityQuery.js, src/services/virtualStudies.js
Includes changes between versions v2.6.0 and 2.7.0, to be deployed in production.
See [NEWS.md](https://github.com/kids-first/kf-portal-ui/pull/1999/files#diff-8312ad0561ef661716b48d09478362f3) for details.
=> Release v2.7.0

src/components/EntityPage/Participant/Utils/FamilyTable.js
NOTE: couldn't find such a case in QA, but the fix should work
=> 2008 fixed by filtering by '--'

src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js, src/components/FileRepo/CustomColumns/ActionsColumn.js, src/services/fileAccessControl.js
The fix affects both the display in the file repository table and in the file entity page.
=> fix/1961 - fixes the display of open access files

src/components/EntityPage/EntityTitle.js, src/components/EntityPage/File/fileProperties.js, src/components/EntityPage/File/index.js, src/components/EntityPage/File/utils.js, src/uikit/CircleIcon.js
make sure that in the file repository screen file with no participant don't explode
=> 2041 bug fix file with no participant

src/components/CohortBuilder/SearchById/SearchByIdModal.js, src/components/CohortBuilder/SearchById/SearchResults.js, src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js, src/uikit/DataTable/ControlledDataTable.js
- Always display the results table
- Remove the "VIEW RESULTS" button, refresh results in real time
- Rename "APPLY FILTER" to "VIEW RESULTS"
- Add "family" in the text listing id types that can be searched
=> Search by Ids: changes following QA

start.sh
=> added a small script to start without sudo

src/chartkit/utils.js, src/components/EntityPage/File/fileProperties.js, src/components/EntityPage/File/index.js, src/components/EntityPage/File/participantBiospecimenTable.js, src/components/EntityPage/File/sequencingProperties.js, src/components/EntityPage/File/utils.js, src/components/UserDashboard/AuthorizedStudies/StudiesConnected.js, src/components/UserDashboard/charts.js, src/components/UserDashboard/index.js, src/components/loginButtons/FacebookLogin.js, src/services/fileAccessControl.js, src/stateProviders/provideFenceConnections.js, src/stateProviders/provideLoggedInUser.js
Note: I didn't change the other lodash imports since @jberube is working on updating babel version. So it would possibly be irrelevant to change once the babel import plugin will be in used (tree-shaking)
=> remove _ and chain implicit imports from lodash

src/App.js, src/components/AuthRedirect.js, src/components/Login/Join.js, src/components/Login/Login.js, src/components/Login/LoginFooter.js, src/components/Login/LoginPage.js, src/components/Login/index.css, src/components/SideImagePage.js, src/components/forms/ConsentForm.js, src/components/forms/SelectRoleForm.js, src/stateProviders/provideLoggedInUser.js, src/uikit/ExternalLink.js
Adds a "Deploys by Netlify" badge to the login page so we can have a free OSS licence.
Also:
- Regrouped the Login-related files under the `components/Login` folder
=> feat/2021 added Netlify badge to login page to have a free OSS licence ♥

package-lock.json, package.json, src/antd-kf-theme.css, src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js, src/components/FileRepo/DownloadButton.js
While the report is loading, display a loader. Display a confirmation once it is done downloading, or an error otherwise.
=> feat/2031 - added a loader during the report generation

NEWS.md, package-lock.json, package.json
=> Release 2.12.0

src/components/UserProfile/HeaderBanner.js, src/components/UserProfile/UserProfilePageContainer.js, src/services/profiles.js, src/utils.js
=> target another property to generate gravatar url.

src/components/MemberSearchPage/FilterTableList.js
=> Disable filter selection is 0 items count

src/components/Fence/FenceAuthorizedStudies.css, src/components/Fence/FenceAuthorizedStudies.js, src/components/UserProfile/Integration.js
1. Enable to show a scroll bar is more Authorized studies that the max window size.
2. Fix condition that was determining if authorized studies should be shown. 
For point 2, 
-> current version, check if the user has at least one project. If not, no authorized study shown even if the user has some. 
-> proposed version, check if the user has actual authorized studies or not.
=> Fix authorized studies check

src/components/Fence/FenceAuthorizedStudies.js, src/components/Modal/ui.js
- Text when no studies are allowed.
- Fix Modal title styling (was absent pb due to refactoring) and replaced with Ant design
- Some clean-up of commented out code.
=> Fix no studies text and fix style of modal title (with ant design)

src/components/FileRepo/FileRepo.js
=> fix: 1966 - select files in different pages

package-lock.json, package.json
Just move some development dependencies from dependencies
=> fix: 2311 - Remove dev dependencies from dependencies

.eslintrc, docs/performance.md
Add documentation about finding on how to optimize our bundle. 
Add a simple eslint rule
=> 2307 add documentation on future performance fix and update package.json

.env.schema, src/components/UserProfile/AboutMe.js, src/components/UserProfile/ContactEditForm.js, src/components/UserProfile/ContactReadOnly.js, src/components/UserProfile/EditToggle.js, src/components/UserProfile/ProfileEditable.js, src/components/UserProfile/ProfileReadOnly.js, src/components/UserProfile/ReportMemberDlg.js, src/components/UserProfile/UserProfilePage.js, src/components/UserProfile/UserProfilePageContainer.js, src/services/login.js, src/services/members/reportMember.js
- add report member button when loggedIn user views other's profile.
Note: Env variable added in QA and PRD + service is broken in persona back-end
=> Add report member feature

src/components/FileRepo/AggregationSidebar/AggregationSidebar.js, src/components/FileRepo/AggregationSidebar/AggregationSidebar.module.css, src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js, src/components/FileRepo/AggregationSidebar/Tab.js, src/components/FileRepo/AggregationSidebar/aggsConfig.js, src/components/FileRepo/FileRepo.css, src/components/FileRepo/FileRepo.js, src/components/Header/Header.css, src/components/Header/index.js, src/components/Page.js, src/components/Page.module.css
fix: 2334 content boby shrinks
=> fix: 2334 content boby shrinks

src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js, src/components/CohortBuilder/ParticipantsTableView/index.js, src/components/CohortBuilder/Results.js, src/components/CohortBuilder/index.js
code cleanup before proceding with a bigger PR
=> fix: 2348 remove ununsed code in cohort builder

.eslintrc, .eslintrc.json, README.md, commitlint.config.js, package-lock.json, package.json
Validate eslint
Validate commit message
=> feat: #2325 add precommit hook, updated eslint

.eslintrc.json, package-lock.json, package.json
Updated eslint to be a little closer to airbnb, plus I added auto formatting with prettier. 
will fix some inconsistencies automaticaly on save/eslint.
=> fix: #2300 update eslint and prettier for auto formatting

src/antd-kf-theme.css
Update styles to 4.0.4
close #2380
=> fix: #2380 update antd 4.0.4 styles

src/components/OntologyBrowser/SelectionTree.tsx, src/components/OntologyBrowser/index.tsx, src/components/OntologyBrowser/store.ts
Refresh the ontology information based on added or removed filters
=> fix(ontologies): #2342 update tree with updated filters

src/components/OntologyBrowser/SelectionTree.tsx, src/components/OntologyBrowser/index.tsx, src/components/OntologyBrowser/store.ts
=> fix(ontologies): #2342 bug fix tree refresh

src/components/OntologyBrowser/SelectionTree.css, src/components/OntologyBrowser/SelectionTree.tsx
=> fix(SelectionTree): #2456 use highlight instead of bold and only lhs

src/components/CohortBuilder/ParticipantsTableView/ParticipantTableView.css, src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js, src/components/CohortBuilder/ParticipantsTableView/SaveSetModal.test.tsx, src/components/CohortBuilder/ParticipantsTableView/SaveSetModal.tsx, src/components/CohortBuilder/ParticipantsTableView/index.js, src/components/CohortBuilder/Results.js, src/components/FileRepo/DownloadButton.js, src/components/FileRepo/FileRepo.css, src/components/FileRepo/FileRepo.js, src/components/OntologyBrowser/Test/SelectionTree.test.tsx, src/components/OntologyBrowser/index.tsx, src/types/index.d.ts, src/uikit/DataTable/BaseDataTable.css, src/uikit/DataTable/BaseDataTable.js, src/uikit/DataTable/TableToolbar/TableToolbar.js, src/uikit/DataTable/ToolbarButtons/ColumnFilter.js, src/uikit/DataTable/ToolbarButtons/Export.js, src/uikit/DataTable/ToolbarButtons/exportTSV.js, src/utils.js
Action buttons Refactored/ReStyle
Modal : 
Dropdown with antd
File View (export button modified (same button as of cohortBuilder))
=> 2465 add saveset button modal to cohort

src/components/CohortBuilder/ParticipantsTableView/ParticipantTableView.css, src/components/FileRepo/DownloadButton.css, src/components/FileRepo/FileRepo.css, src/components/FileRepo/FileRepo.js
=> fix(DownloadButton): #2495 visual issue

src/components/Charts/Ontology/OntologySunburst.tsx, src/components/OntologyBrowser/store.ts, src/components/UI/Charts/Sunburst/sunburst-d3.jsx
fix bug #2504 in sunburst
- auto update
- extra comma
- center text to low
=> 2504  auto update on sqon changes

src/components/UI/Charts/Sunburst/sunburst-d3.jsx
#2511  auto update on sqon changes
=> 2511 auto update on sqon changes

.eslintrc.json, src/components/Login/OrcidRedirect.js, src/components/RoleIconButton.js
fixes #2544 typescript build error
=> fix: #2544 typescript build error

.circleci/config.yml
=> 2546 update circleci node

src/components/OntologyBrowser/SelectionTree.tsx, src/components/OntologyBrowser/Test/OntologyModal.test.tsx, src/components/OntologyBrowser/index.tsx, src/services/report.tsx, src/store/sqon.d.ts, src/store/sqon.ts
=> fix(ontologyBrowser): #2552 enable combined queries

src/components/CohortBuilder/ParticipantsTableView/SaveSetModal.tsx, src/components/CohortBuilder/Results.js, src/services/report.tsx, src/store/actionCreators/Test/report.test.tsx, src/store/actionCreators/report.tsx, src/ui/ButtonWithRouter.tsx, src/ui/Test/ButtonWithRouter.test.tsx, src/ui/Test/ReportsButton.test.tsx
=> Use same reports in cb and fr

src/components/FileRepo/AggregationSidebar/EntityFileSearchFilter.tsx, src/components/FileRepo/AggregationSidebar/aggregationSideBar.css, src/components/FileRepo/Test/EntityFileSearchFilter.test.tsx, src/store/actionCreators/Test/fileSearchFilters.test.tsx, src/store/actionCreators/fileSearchFilters.tsx, src/store/fileSearchFiltersTypes.tsx
=> fix(file repo, search filters): improve ui when there is an error

package-lock.json, package.json, src/components/CohortBuilder/Categories/Category.js, src/components/CohortBuilder/Categories/categories.ts, src/components/CohortBuilder/Categories/index.js, src/components/CohortBuilder/FieldFilterContainer.js, src/components/CohortBuilder/Modals.tsx, src/components/CohortBuilder/SqonBuilder/index.js, src/components/CohortBuilder/index.js, src/components/OntologyBrowser/OntologyBrowser.ts, src/components/OntologyBrowser/index.css, src/components/OntologyBrowser/index.tsx, src/store/actions/modal.ts, src/store/reducers/index.js, src/store/reducers/modal.ts, src/store/rootState.d.ts
=> feat: 2534 open ontology browser

src/components/CohortBuilder/Summary/Summary.css, src/components/CohortBuilder/Summary/SurvivalChart.js, src/components/CohortBuilder/Summary/SurvivalPlot.js, src/components/CohortBuilder/Summary/ui.js
partial fix for #2676 
dynamicaly scale d3 graph.
All card now will pass a height props if children is a function
=> fix: #2676 survival strech

src/components/FileRepo/AggregationSidebar/Tab.tsx, src/components/FileRepo/AggregationSidebar/UploadIdsButton.tsx, src/components/UploadIdsModal.js, src/components/uploadIdsModal.css, src/store/actions/modal.ts
=> refactor(UploadModalIds): #2683 remove freactal set/unset modal.

package-lock.json, package.json, src/components/CohortBuilder/ParticipantsTableView/AddRemoveSaveSetModal.css, src/components/CohortBuilder/ParticipantsTableView/AddRemoveSaveSetModal.tsx, src/components/CohortBuilder/ParticipantsTableView/ParticipantSetDropdown.css, src/components/CohortBuilder/ParticipantsTableView/ParticipantSetDropdown.tsx, src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js, src/components/CohortBuilder/ParticipantsTableView/SaveSetModal.tsx, src/components/CohortBuilder/ParticipantsTableView/Test/AddRemoveSaveSetModal.test.tsx, src/components/CohortBuilder/ParticipantsTableView/Test/SaveSetModal.test.tsx, src/components/CohortBuilder/ParticipantsTableView/index.js, src/components/UserDashboard/ParticipantSets/ParticipantSets.css, src/components/UserDashboard/ParticipantSets/Test/ParticipantSets.test.tsx, src/components/UserDashboard/ParticipantSets/index.tsx, src/components/UserDashboard/index.js, src/services/sets.tsx, src/stateProviders/provideLoggedInUser.js, src/store/actionCreators/Test/saveSets.test.tsx, src/store/actionCreators/saveSets.ts, src/store/reducers/Test/saveSets.test.tsx, src/store/reducers/saveSets.tsx, src/store/saveSetTypes.tsx, src/store/selectors/saveSetsSelectors.tsx
=> Feat/2615 add/remove participants to set

src/components/CohortBuilder/SearchById/SearchByIdModal.js, src/components/CohortBuilder/SearchById/styles.scss
fixed:
Note: we really should replace it with <UploadIdsModal/> since it s a kind of duplication
=> quick fix(cohort builder, upload ids modal): fix layout

src/components/UserDashboard/ParticipantSets/ParticipantSets.css, src/style/themes/antd-kf-theme.css, src/style/themes/antd-kf-theme.less
* quick fix(cohort builder, upload ids modal): fix layout
* fix lint
=> fix(savesets): #2615 qa review

src/components/FamilyManifestModal/FamilyManifestModal.js, src/components/FamilyManifestModal/FamilyManifestModal.module.css, src/components/FamilyManifestModal/statVisuals.js, src/components/FamilyManifestModal/statVisuals.module.css, src/style/themes/antd-kf-theme.less
=> fix: #2558 make modal readable

src/components/CohortBuilder/Results/Toolbar/Toolbar.scss
=> fix: #2730 align async button spinner in cb toolbar

src/components/CohortBuilder/SearchById/SearchByIdModal.js, src/components/CohortBuilder/VirtualStudiesMenu/index.js, src/components/LoadShareSaveDeleteQuery/SaveQuery.js, src/style/themes/default/main.scss, src/uikit/Core.module.css, src/uikit/Headings.js
=> refactor(style): #2737 style refactor searchByIdModal

src/components/UserDashboard/AuthorizedStudies/StudiesConnected.js, src/components/UserDashboard/CavaticaProjects/Connected.js, src/components/UserDashboard/SavedQueries/index.js, src/components/UserDashboard/UserDashboard.module.css
=> 2742 fix scroll card

src/style/README.md
close #2756 
add link to ant design customizable variable
=> fix: #2756 update style documentation

src/components/UI/Charts/Sunburst/sunburst.css
=> fix(sunburst): #2840 fix width and height of tree nodes (reduce)

src/common/constants.js, src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js, src/components/CohortBuilder/ParticipantsTableView/queries.js, src/components/EntityPage/Participant/ParticipantSummary.js
=> feat (#2830) remove age diag and add pedcbio columns

package-lock.json, package.json, src/common/Test/sqonToName.test.js, src/common/Test/sqonUtils.test.js, src/components/CohortBuilder/ParticipantsTableView/SaveSetModal.tsx, src/components/CohortBuilder/ParticipantsTableView/Test/SaveSetModal.test.tsx
=> feat(sets): #2851 set default name as per file repo

src/components/EntityPage/Participant/ParticipantSummary.js
=> feat: change external id label

src/components/OntologyBrowser/index.css, src/components/OntologyBrowser/index.tsx
=> fix(ontologyBrowser): #2586 empty data

src/pages/studies/SidebarFilters.tsx, src/pages/studies/studies.tsx
Hack while we fix the react-router-dom issue
=> fix: #2991 studi page flash when loading new data

package-lock.json, package.json, src/pages/studies/Sidebar.module.scss, src/pages/studies/Sidebar.tsx, src/pages/studies/SidebarFilters.module.scss, src/pages/studies/SidebarFilters.tsx, src/style/dist/themes/default/_colors.scss, src/style/dist/themes/default/antd.css, src/style/themes/default/antd/_colors.less, src/style/themes/default/antd/antd.less, src/style/themes/default/antd/collapse.less
=> 2998 sidebar stype update

src/pages/studies/SidebarFilters.tsx, src/pages/studies/StudyTableContainer.tsx, src/pages/studies/studies.tsx, src/store/graphql/studies/actions.tsx, src/store/graphql/studies/models.ts, src/store/graphql/studies/queries.tsx
=> fix: #3006 fix table with new columns

src/components/CohortBuilder/Categories/categories.ts, src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js, src/components/CohortBuilder/ParticipantsTableView/queries.js, src/components/FileRepo/AggregationSidebar/aggsConfig.js
Resolves both [https://github.com/kids-first/kf-portal-ui/issues/3004](url) & [https://github.com/kids-first/kf-portal-ui/issues/3001](url)
=> Add filters to cb and file repo

package.json, src/pages/studies/utils.ts, src/style/dist/themes/default/_colors.scss, src/style/dist/themes/default/antd.css, src/style/themes/default/antd/_colors.less
=> fix: #3024 fix checkbox colors and tag aligment

package-lock.json, src/pages/variants/WorkBench.module.scss, src/pages/variants/WorkBench.tsx, src/style/dist/themes/default/_colors.scss, src/style/dist/themes/default/antd.css
=> fix: variant overflow

src/store/graphql/studies/models.ts
=> fix: #3030 study table column width

src/pages/studies/SidebarFilters.tsx, src/pages/studies/StudyPageContainer.tsx, src/pages/studies/studies.tsx
=> fix: #2997 fix boolean filter

src/pages/studies/StudyPageContainer.tsx, src/pages/studies/StudyTableContainer.tsx, src/pages/studies/studies.tsx, src/pages/studies/utils.ts
closes #3015 
Functional pagination
=> fix: #3015 Functional pagination

public/index.html, src/pages/variantEntity/TabClinical.tsx, src/pages/variantEntity/TabFrequencies.tsx, src/style/dist/themes/default/_colors.scss, src/style/dist/themes/default/antd.css, src/style/themes/default/antd/_colors.less, src/style/themes/default/antd/antd.less
=> fix: #3046 fix background and table border variant

src/App.js, src/common/routes.js, src/components/Header/index.js
closes #3054 
update Variant link
=> fix: #3054 update variant menu link

src/pages/variantEntity/TabFrequencies.tsx, src/pages/variantEntity/TabSummary.tsx
=> fix: #3052 variable table container

src/App.js, src/pages/variantEntity/clinical.tsx, src/pages/variantEntity/index.tsx, src/pages/variantsSearchPage/VariantTable.module.scss, src/pages/variantsSearchPage/VariantTable.tsx, src/store/graphql/variants/queries.tsx, src/store/graphql/variants/searchActions.tsx
=> add link to variant entity and fix various issues

src/components/ExpandableCell.module.scss, src/components/ExpandableCell.tsx, src/pages/variantEntity/TabSummary.tsx, src/pages/variantEntity/tables.module.scss, src/style/dist/themes/default/_colors.scss, src/style/dist/themes/default/antd.css, src/style/themes/default/antd/_colors.less, src/style/themes/default/antd/table.less
=> fix: #3071 fix table layout

src/common/sqonUtils.js, src/pages/variantEntity/TabFrequencies.tsx, src/pages/variantsSearchPage/VariantTable.tsx, src/store/graphql/studies/tableColumns.tsx, src/store/graphql/variants/models.ts, src/store/graphql/variants/queries.tsx, src/store/graphql/variants/tabActions.tsx
=> add link to CB from variant frequencies

src/pages/studies/Sidebar.tsx, src/pages/studies/SidebarFilters.tsx, src/pages/studies/index.tsx, src/pages/studies/studies.tsx
=> fix: #3078 studies pagination

src/style/dist/themes/default/antd.css, src/style/themes/default/antd/antd.less, src/style/themes/default/antd/buttons.less
=> fix: #3085 fix button on hover

src/pages/variantEntity/ClinVarExternalLink.tsx, src/pages/variantEntity/TabClinical.tsx, src/pages/variantEntity/clinical.tsx
Test Suites: 26 passed, 26 total
Tests:       153 passed, 153 total
Time:        4.994s
=> clinvar link + remove mim on hpo

src/components/Header/index.js, src/pages/variantsSearchPage/Suggester.tsx
```
Test Suites: 26 passed, 26 total
Tests:       153 passed, 153 total
Time:        5.248s, estimated 10s
```
=> add "beta" badge to variant button

src/store/graphql/studies/tableColumns.tsx
=> fix: #3125 add tooltip on some table columns

src/pages/variantEntity/TabFrequencies.tsx, src/pages/variantsSearchPage/VariantTable.tsx, src/store/graphql/variants/queries.tsx, src/store/graphql/variants/tabActions.tsx
=> feat: #3140 add participants link on variant pages

src/components/EntityPage/Participant/ParticipantClinical.css
=> fix: #3146 fix small table font

src/components/Variants/ServerError.tsx, src/pages/variantEntity/Summary.tsx, src/pages/variantEntity/TabClinical.tsx, src/pages/variantEntity/TabFrequencies.tsx, src/pages/variantEntity/TabSummary.tsx, src/pages/variantsSearchPage/VariantTable.module.scss, src/pages/variantsSearchPage/VariantTable.tsx, src/store/graphql/variants/models.ts, src/store/graphql/variants/queries.tsx, src/store/graphql/variants/searchActions.tsx, src/utils.js
Time:        9.987s
(bypassing circle-ci)
=> show error if graphql error + point correct properties for frequencies

src/pages/variantsSearchPage/VariantTable.tsx, src/store/graphql/variants/searchActions.tsx
=> fix: #3145 enable pagination size change

src/pages/variantEntity/TabFrequencies.tsx, src/pages/variantEntity/TableSummaryKfStudies.tsx, src/pages/variantsSearchPage/VariantTable.tsx, src/ui/TableOptions.ts, src/utils.js
```
Time:        5.577s, estimated 6s
```
=> incorporate elements from code review + add freq column

src/components/EntityPage/Participant/ParticipantClinical.css, src/components/FileRepo/FileRepo.scss, src/uikit/DataTable/Table/Table.css
=> fix: #3146 Match uikit table match ant design default

src/style/dist/themes/default/antd.css, src/style/themes/default/antd/table.less
=> fix: #3124 fix table border/line color

src/components/CohortBuilder/ParticipantsTableView/SaveSetModal.tsx
=> fix: #3062 saveset default name

src/components/Header/Header.css, src/style/dist/themes/default/_colors.scss, src/style/dist/themes/default/antd.css, src/style/themes/default/antd/_colors.less, src/style/themes/default/antd/antd.less, src/style/themes/default/antd/typography.less
=> 3123 fix default table link color

src/components/Variants/EmptyTable.tsx, src/pages/variantEntity/TabClinical.tsx, src/pages/variantEntity/TabFrequencies.tsx, src/style/dist/themes/default/antd.css, src/style/themes/default/antd/antd.less, src/style/themes/default/antd/card.less
**Note:** I've added --no-verify when I made my commit since I had linting errors that I think are not genuine errors. Here's what I got
```
...omitted...src/style/dist/themes/default/antd.css
5:6  error  Parsing error: '{' expected
...omitted.../src/style/themes/default/antd/antd.less
1:1  error  Parsing error: Expression expected
...omitted.../src/style/themes/default/antd/card.less
1:0  error  Parsing error: Declaration or statement expected
```
**For cicrle-ci:**
```
Time:        7.702 s
```
=> fix(variant entity) #3128 better display when empty tables

src/components/Variants/Empty.tsx, src/pages/variantEntity/TabClinical.tsx, src/pages/variantEntity/TabFrequencies.tsx, src/pages/variantEntity/TabSummary.tsx, src/pages/variantEntity/clinicalColumns.tsx, src/pages/variantsSearchPage/VariantTable.tsx
```
Time:        6.378 s, estimated 7 s
```
=> fix(variant): #3113 improve display when no datum

package-lock.json, package.json
=> fix: #3595 upgrade commit-lint

src/pages/variantEntity/TabSummary.tsx
```
Time:        9.017 s
```
https://github.com/kids-first/kf-portal-ui/issues/3111
=> feat(Variant): #3111 display long impact names when possible

src/pages/variantsSearchPage/VariantTable.tsx
=> fix(variantSearchPage): #3200 do not show pagination message when empty

.eslintignore, commitlint.config.js, package.json
=> fix: #3197 commitlint better messages

package-lock.json, package.json, src/style/dist/themes/default/antd.css, src/style/themes/default/antd/antd.less, src/style/themes/default/antd/buttons.less, src/style/themes/default/antd/pagination.less
=> fix: #3214 link underline for pagination and participant

src/components/FileRepo/StatsBar.tsx
=> fix: #3218 icon in file repo statbar

NEWS.md, package-lock.json, package.json, src/pages/variantEntity/TabFrequencies.tsx
```
Time:        5.746 s, estimated 7 s
Watch Usage: Press w to show more
```
=> build: #0000 bump version and fix empty table display

.eslintignore, package-lock.json, package.json, src/pages/studies/Sidebar.module.scss, src/pages/studies/Sidebar.tsx, src/pages/studies/SidebarFilters.tsx, src/pages/studies/StudyPageContainer.tsx, src/pages/studies/index.tsx, src/pages/studies/studies.module.scss, src/pages/studies/studies.tsx, src/style/dist/themes/default/antd.css, src/style/themes/default/antd/antd.less
=> fix: #3131 update sidebar filter wrap colors and size

src/services/api.js
Since latest version of axios, delete, get, options and head don't support body argument, instead data should be passed by config argument.
Issue: https://github.com/axios/axios/issues/897
Documentation: https://github.com/axios/axios#request-method-aliases
So I update api.js to pass data in different way depending on method
=> fix: #3247 fix delete request

src/pages/variantEntity/clinicalColumns.tsx
```
npm run test
Tests:       140 passed, 140 total
Time:        5.857 s, estimated 7 s
```
=> fix(variants): #3226 fix link

src/pages/studies/StudyTableContainer.tsx, src/pages/studies/studies.tsx, src/pages/variantsSearchPage/VariantTable.tsx, src/style/dist/themes/default/antd.css, src/style/themes/default/antd/pagination.less
=> 3211 fix pagination style to reflect theme

package-lock.json, package.json
Try to fix this error : 
And this error :
=> fix: #3244 try to fix circle ci errors in dev build

src/components/CohortBuilder/Summary/Cards/StudiesChart.js, src/components/CohortBuilder/Summary/index.js
=> fix: #3281 fix NPE when no top_hits for study

NEWS.md, package.json
EDIT: new script by itself won't break anything :)
=> fix: #3271 add script for netlify to install ci and build

package-lock.json, package.json, src/components/Footer.js, src/components/FooterLink.tsx, src/components/UserProfile/FindMeEditable.js, src/components/UserProfile/FindMeInput.js, src/components/UserProfile/FindMeReadOnly.tsx, src/components/UserProfile/utils.js, src/style/themes/default/colors.module.scss
=> refactor: #3322 remove react social icons lib

src/App.js, src/CavaticaIServiceErrorBanner.tsx
TEST ran locally
```
Tests:       140 passed, 140 total
Time:        10.578 s
```
=> #3347 add cavatica error banner

src/App.js, src/chartkit/components/ChartLoadGate.js, src/common/routes.js, src/components/Header/UserMenu.js, src/components/Login/TermsConditions.tsx, src/components/LogoutButton.js, src/shapes/effects.js, src/stateProviders/provideLoggedInUser.js
=> #3356 make surethat no unwanted components are loaded when logging out

src/pages/studies/SearchBar.module.scss
=> fix: #SKFP_19 fic color search bar

src/components/UserDashboard/SavedQueries/CohortTab.tsx, src/components/UserDashboard/SavedQueries/FileTab.tsx, src/components/UserDashboard/SavedQueries/SavedQueries.scss, src/components/UserDashboard/SavedQueries/index.tsx, src/store/SavedQueriesTypes.ts
=> #skfp-24 make sure saved queries display correctly

src/pages/studies/StudiesPageContainer.module.scss, src/pages/studies/StudyTableContainer.tsx, src/store/graphql/studies/tableColumns.tsx
=> fix(studies): #3232 add new header and totals on study table

src/components/Login/Login.js, src/services/api.js, src/services/cavatica/projectDescription.md, src/store/actionCreators/user.ts
make sure that connection to fences are not lost when a user logout but connections to fences are still on.
(connect successfully to fences, then logout then login => settings should be unchanged)
connect successfully to fences, then logout then login 
...
=> Fences behaviour when logout

src/components/FileRepo/FileRepo.js
#BUG
- closes [SKFP-119](https://d3b.atlassian.net/browse/SKFP-119)
File Repo shows wrong values for filters selected
before
https://files.slack.com/files-pri/T4KJMN4N4-F02DNQL4XV3/image.png
After
in File Repo select various filters
@celinepelletier @oliviercperrier
=> fix: #SKFP-119 fix file repo select filter display

src/common/constants.js
#[BUG] [TITLE] dbGaP issue 
- closes #SKFP-122
Remove v1.p1 at the end of dbgap url
Go to file repo and see link in dbGaP column
=> fix: #SKFP-122 fix dbgap url building

NEWS.md, package-lock.json, package.json
=> build: #SKFP-124 bump to version 3_3_0

NEWS.md
=> build: #SKFP-128 bump portal to 3_3_0

NEWS.md, package-lock.json, package.json, src/services/cookie.js, src/store/actionCreators/user.ts
#[BUG] Can't access to variant workbench because no ego-jwt cookie
- closes SKFP-130
...
Not able to fully test it in QA because no variant workbench in QA
=> fix: #SKFP-130 hotfix regression cannot access to variant workbench

NEWS.md, package-lock.json, package.json, src/services/cookie.js, src/store/actionCreators/user.ts
#[BUG | FEATUER | DOC] [TITLE]
- closes #3242
...
=> Master to dev after hotfix skfp 130

NEWS.md, package-lock.json, package.json, src/components/FileRepo/CustomColumns/DbGapExternalIdColumn.js
#SKFP-135 Fix (File repository, Filter options): Fix column selection error, pathology filter
- closes #SKFP-135
Error when filter try to display a file with 0 participant
No error, UI should be able to deal with that even if not expected
Go in File Repo in PRD, filter on Category - Pathology then try to add a column
Hotfix
=> fix: #SKFP-135 hotfix error in file repo due to file with no participant

NEWS.md, package-lock.json, package.json, src/components/FileRepo/CustomColumns/DbGapExternalIdColumn.js
Add hotfix done on master for SKFP-135 to dev
=> Master to dev after hotfix skfp 135

NEWS.md, package-lock.json, package.json, src/App.js
master to dev after hotfix SKFP-140
=> fix: #SKFP-140 hotfix login with orcid always redirect to login page

src/components/Login/termsConditions.css, src/pages/variantsSearchPage/VariantStats.tsx, src/pages/variantsSearchPage/VariantsSearchPage.module.scss, src/pages/variantsSearchPage/filters/VariantFilters.module.scss, src/pages/variantsSearchPage/index.tsx
#BUG
- closes [SKFP-154](https://d3b.atlassian.net/browse/SKFP-154)  [SKFP-162](https://d3b.atlassian.net/browse/SKFP-162)
see issues for details
...
@ QA,
=> fix: #SKFP-154 162 fix various style issues

src/components/Utils/utils.tsx, src/pages/variantsSearchPage/filters/GenericFilters.tsx, src/pages/variantsSearchPage/filters/fieldsMappings.ts
- closes [SKFP-183](https://d3b.atlassian.net/browse/SKFP-183)
before:
After:
...
=> fix: #SKFP-183 add acronym to terms

src/pages/variantsSearchPage/Suggester.tsx, src/pages/variantsSearchPage/VariantTableContainer.module.scss, src/pages/variantsSearchPage/filters/GenericFilters.tsx
=> fix(apply): #SKFP-214 add apply and clear button

src/pages/variantsSearchPage/SuggestionOptions.tsx, src/store/graphql/variants/models.ts
#BUG [Search by dbSNP ID, Clinvar ID]
- closes [#SKFP-199](https://d3b.atlassian.net/browse/SKFP-199)
Before:
After:
@celinepelletier @oliviercperrier
=> fix: #SKFP-199 fix search variant and gene suggestions

src/pages/variantsSearchPage/VariantPageContainer.tsx
#BUG] [Table: Results update without any query request]
- closes [#SKFP-211](https://d3b.atlassian.net/browse/SKFP-211)
@celinepelletier  @oliviercperrier  ...
=> fix: #SKFP-211 add a second ordering by hgvsg

package-lock.json, package.json
=> fix: #SKFP-226 update ferlab

src/pages/variantsSearchPage/SuggesterWrapper.tsx, src/pages/variantsSearchPage/filters/GeneFilters.tsx, src/pages/variantsSearchPage/filters/VariantFilters.tsx
=> fix(tooltips): #SKFP-232-233 fix tooltips messages

src/pages/variantsSearchPage/SuggesterWrapper.module.scss, src/pages/variantsSearchPage/SuggesterWrapper.tsx
=> fix(fontsize): #SKFP-181 small fix title font size

package-lock.json, package.json
=> fix: #SKFP-274 update ferlab

NEWS.md, package-lock.json, package.json
=> feat: #SKFP-279 bump portal version

src/App.js, src/components/LoginPage/Join/index.module.scss, src/components/LoginPage/Login/index.module.scss, src/components/LoginPage/Login/index.tsx, src/components/LoginPage/TermsConditions/index.css, src/components/SideImagePage.js, src/components/SideImagePage.module.css, src/components/SplashPage.css, src/style/dist/themes/default/_colors.scss, src/style/dist/themes/default/antd.css, src/style/themes/default/antd/_colors.less, src/style/themes/default/antd/antd.less
Also:
- fix info alert style
- fix Terms & Conditions last updated date color
- add margin at join form bottom
Home (S and XS)
Join (step 1 and 2 in S)
=> Feat/add responsive home page + UI fixes

package-lock.json, package.json, src/components/CohortBuilder/Categories/Category.js, src/components/CohortBuilder/Categories/Filter.js, src/components/CohortBuilder/Categories/index.js, src/components/CohortBuilder/SearchAll/index.js
- closes #SKFP-318
When selecting for a filter that is of “Multiselect” type under the Explore Data page, an error appears.
No more error
Before
After
Go in Explore Data and select a multiselect term
=> fix: #SKFP-318 fix error in cohort builder page

NEWS.md, package-lock.json, package.json, src/DynamicBanner.tsx
Need to display a banner without a link to Kids First forum
=> hotfix: Display kids first forum link in banner only if a link is provided

NEWS.md, package-lock.json, package.json
Bump version and add release note for 4.1.0
=> feat: #SKFP-26 release 4 1 0

package-lock.json, package.json, src/components/UploadIdsModal.js
=> fix: #SKFP-334 file repo upload Ids

src/components/OntologyBrowser/store.ts, src/services/arranger.js
=> fix: #SJIP-259 fix sunburst

src/pages/variantEntity/TabClinical.tsx, src/pages/variantEntity/TabSummary.tsx, src/pages/variantEntity/index.tsx, src/pages/variantsSearchPage/VariantTableContainer.tsx, src/store/graphql/variants/queries.tsx, src/store/graphql/variants/tabActions.tsx
=> fix: #SKFP-334 display hgvsg as title

src/views/Dashboard/components/DashboardCards/DataExplorationLinks/index.module.scss
=> :adhesive_bandage: fix(dataexploration): SKFP-449 adjust color theme

src/style/themes/kids-first/_theme.template.scss, src/style/themes/kids-first/antd/tabs.less, src/style/themes/kids-first/colors.less
- closes[ #470](https://d3b.atlassian.net/browse/SKFP-470)
- closes [#468](https://d3b.atlassian.net/browse/SKFP-468)
=> 🩹fix(theme): SKFP-470, SKFP-468 fix theme

src/components/uiKit/FilterList/index.tsx, src/graphql/constants.ts, src/graphql/files/actions.ts, src/graphql/files/models.ts, src/graphql/files/queries.ts, src/graphql/participants/models.ts, src/graphql/participants/queries.ts, src/locales/en.ts, src/store/fenceCavatica/thunks.tsx, src/store/fenceStudies/thunks.ts, src/store/report/thunks.tsx, src/utils/fieldMapper.ts, src/views/Dashboard/components/DashboardCards/AuthorizedStudies/ListItem/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx, src/views/DataExploration/components/BiospecimenSearch.tsx, src/views/DataExploration/components/BiospecimenSetSearch.tsx, src/views/DataExploration/components/FileSearch.tsx, src/views/DataExploration/components/FileSetSearch.tsx, src/views/DataExploration/components/PageContent/index.tsx, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DataCategoryGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DataTypeGraphCard/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx, src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx, src/views/DataExploration/components/UploadIds/FileUploadIds.tsx, src/views/DataExploration/index.tsx
=> :construction: Connect data to explore page (wip)

src/graphql/studies/queries.ts, src/locales/en.ts, src/style/themes/kids-first/antd/buttons.less, src/views/ProfileSettings/cards/Identification/ToggleProfileVisibility/index.tsx, src/views/ProfileSettings/cards/Identification/index.tsx, src/views/ProfileSettings/cards/Location/index.tsx, src/views/ProfileSettings/cards/RoleAndAffiliation/index.tsx, src/views/Studies/components/PageContent/index.module.scss, src/views/Studies/components/PageContent/index.tsx, src/views/Studies/components/SideBarFacet/index.module.scss, src/views/Studies/components/SideBarFacet/index.tsx, src/views/Studies/components/StudySearch/index.tsx, src/views/Studies/index.tsx, src/views/Variants/components/PageContent/index.tsx, src/views/Variants/index.tsx
- closes [#353](https://d3b.atlassian.net/browse/SKFP-353)
=> 🩹fix(study): SKFP-353 fix studies pages

src/style/themes/kids-first/antd-kids-first-theme.less, src/style/themes/kids-first/antd/buttons.less, src/style/themes/kids-first/antd/popover.less, src/views/Dashboard/components/CardHeader/index.module.scss, src/views/Dashboard/components/CardHeader/index.tsx, src/views/Dashboard/components/DashboardCards/CaringForChildrenWithCovid/index.module.scss, src/views/Dashboard/components/DashboardCards/CaringForChildrenWithCovid/index.tsx, src/views/Dashboard/components/DashboardCards/Notebook/index.module.scss
- closes [#381](https://d3b.atlassian.net/browse/SKFP-381)
=> 🩹fix(dashboard): SKFP-381 adjust color theme

src/services/api/savedFilter/models.ts, src/services/api/savedSet/models.ts, src/store/savedFilter/slice.ts, src/store/savedSet/slice.ts, src/utils/dates.ts, src/views/Dashboard/components/DashboardCards/SavedFilters/ListItem/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx
=> 🩹fix(dashboard): fix saved filters and set

src/components/Layout/Header/index.tsx
- closes #[484](https://d3b.atlassian.net/browse/SKFP-484)
=> 🐛fix(header): SKFP-484 place community button

Dockerfile, docker-compose.yaml
bump node version. I came aware of this because of a PR opened by _snyk_ for another project.
=> :arrow_up: Bump node version 18.8 to 18.10

src/views/Dashboard/components/CardHeader/index.tsx, src/views/Dashboard/components/DashboardCards/Notebook/index.tsx, src/views/Dashboard/components/DashboardCards/index.tsx
- closes #[490](https://d3b.atlassian.net/browse/SKFP-490)
[Dashboard] Can't dnd FHIR and Notebook card
https://user-images.githubusercontent.com/65532894/196740067-b425022b-bca0-47a0-b47e-b81b08694ce2.mp4
=> 🐛fix(dashboard): SKFP-490 fix drag and drop for notebook and fhir

src/locales/en.ts, src/views/DataExploration/components/PageContent/index.module.scss, src/views/DataExploration/components/PageContent/index.tsx
- closes #[485](https://d3b.atlassian.net/browse/SKFP-485)
[Data Explore] Add title of the page
=> 🐛fix(data-exploration): SKFP-485 add title

src/style/themes/kids-first/antd/buttons.less, src/views/FakeStorybook/index.tsx
#BUG 
- closes #[460](https://d3b.atlassian.net/browse/SKFP-460)
Fix design
=> 🐛feat(button): SKFP-460 fix themes

src/locales/en.ts
- closes #[485](https://d3b.atlassian.net/browse/SKFP-485)
=> 🐛fix(dataexplore): SKFP-385 fix title

src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
=> :pencil2: Fix typo in data explore page (ticket SKFP-386)

src/views/DataExploration/components/UploadIds/FileUploadIds.tsx
- closes #[496](https://d3b.atlassian.net/browse/SKFP-496)
Uploads file liste doesn't match anyu result when it should
https://user-images.githubusercontent.com/65532894/198384493-d5eab8dc-6892-4f07-b181-e364038a6d89.mp4
=> 🐛fix(dataexplore): SKFP-496 fix uploads ids

src/components/Layout/Header/index.tsx, src/locales/en.ts, src/views/ProfileSettings/cards/Identification/index.tsx
- closes #[503](https://d3b.atlassian.net/browse/SKFP-503)
Orcid and nih cannot be tested at times since I don't have the login. Will be validated after the merge with JP
=> ✨feat: add orchid/nih login info

src/auth/keycloak-api/utils.ts, src/components/Layout/Header/index.tsx, src/views/ProfileSettings/cards/Identification/index.tsx, src/views/ProfileSettings/cards/utils.ts
- closes #[503](https://d3b.atlassian.net/browse/SKFP-503)
Orcid and nih cannot be tested at times since I don't have the login. Will be validated after the merge with JP
=> 🐛fix(login): SKFP-503 fix provider string

src/locales/en.json, src/locales/en.ts, src/views/DataExploration/components/UploadIds/EntityUploadIds/index.tsx, src/views/Variants/components/GeneUploadIds/index.module.scss, src/views/Variants/components/GeneUploadIds/index.tsx
=> ✨feat(variant): SKFP-528 Add information icon to Upload Gene List modal

src/components/Icons/ListAddIcon.tsx, src/components/Icons/ListRemoveIcon.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx
- closes #[508](https://d3b.atlassian.net/browse/SKFP-508)
Before:
After:
=> 🐛fix(dataexplore): SKFP-512 Change add and remove saved sets icons

src/views/Variants/components/PageContent/index.tsx, src/views/Variants/index.tsx
- closes #[526](https://d3b.atlassian.net/browse/SKFP-526)
Ajout du dropdown lorsqu'on clique sur la query pill d'un critère de recherche de variant
Before:
After:
=> 🐛fix(variant): SKFP-526 Missing query pill dropdown

src/locales/en.ts, src/views/Dashboard/components/DashboardCards/CaringForChildrenWithCovid/index.tsx, src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
- closes #[536](https://d3b.atlassian.net/browse/SKFP-536)
Ajustement du contenu des popovers des widgets du dashboard.
Avant:
Après:
=> 🐛fix(dashboard): SKFP-536 Update widget cards content

src/locales/en.ts, src/views/Dashboard/components/DashboardCards/SavedSets/index.module.scss, src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
- closes #[474](https://d3b.atlassian.net/browse/SKFP-474)
"Biospecimen" au pluriel. Et j'en ai profiter pour mettre les strings du component dans le fichier de localisation.
Avant:
Après:
=> 🐛fix(dashboard): SKFP-474 Typo in Saved Sets card

src/style/themes/kids-first/antd-kids-first-theme.less, src/style/themes/kids-first/antd/descriptions.less, src/style/themes/kids-first/antd/popover.less
- closes #[532](https://d3b.atlassian.net/browse/SKFP-532)
Adjusted the Descriptions component colors and margins inside popovers. 
Before:
After:
=> 🐛fix(theme): SKFP-532 Descriptions style in popover

src/utils/string.ts, src/views/Variants/components/GeneUploadIds/index.tsx
Reverting case insensitive search for now, will be done on the backend side instead
=> 🐛fix(variant): SKFP-529 Remove case insensitive search

src/utils/translation.ts, src/views/Variants/index.tsx
- closes #[518
](https://d3b.atlassian.net/browse/SKFP-518)
Before
After
=> 🐛fix(facets): SKFP-518 fix facets translations

src/style/themes/kids-first/antd/pagination.less, src/views/Community/Member/index.tsx, src/views/Community/components/Filters/Box/index.tsx, src/views/Community/contants.ts, src/views/ProfileSettings/cards/ResearchInterests/index.tsx
- closes #[475](https://d3b.atlassian.net/browse/SKFP-475)
1. Ajouter un titre “Area of interest“ pour ces valeurs dans la Profile View Page
2. Lister les valeurs avec des bullet points (comme les rôles) et afficher les valeurs telles quelles (pas tout en minuscule)
3. pagination n’est pas conforme à la maquette
1-2
Before
After
3
=> 🐛fix(interests): SFKP-467 map the correct text format

src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.tsx
- closes [515](https://d3b.atlassian.net/browse/SKFP-515)
- Fixed the Studies graph that didn't show any results when clicked because the wrong key was sent.
- Cleaned up some variables that were not used.
- Created an enum to handle summary fields
Before:
After:
=> 🐛fix(studies): SKFP-315 Show results when clicking the Studies graph

src/locales/en.json, src/locales/en.ts, src/utils/translation.ts, src/views/DataExploration/index.tsx
- closes #[518](https://d3b.atlassian.net/browse/SKFP-518)
Page Data Exploration - Participant: Retirer la section Demographic
Before
After
Page Data Exploration - Clinical: Vital Status
Before
After
Page Data Exploration - Data File: Revoir tous les titres 
Before
After
Page Variants - Participant: Diagnosis (MONDO)
Before
After
Page Variants - Position
Before
After
Page Variants - Transmission
Before
After
Page Variants - Gene: Upload a gene list
Before
After
Page Variants - Pathogenicity: Déplacer ClinVar et VEP en haut de la section Predictions
Already done
=> 🐛fix(facets): SKFP-518 fix facets display name

src/locales/en.ts
=> 🐛fix(facets): SKFP-552 fix studies code

src/views/Variants/components/PageContent/index.tsx
[BUG
- closes #3242
Vue que ça m'a pris presque une journée et demi pour trouver d'où venait le problème, j'ai fait une petite documentation si on doit intégrer dans les prochaines pages
https://www.notion.so/ferlab/QueryBuilder-SavedFilter-et-partage-de-lien-7782573ab3b647dda2bb9cb96e5a73b7
Before
After
=> 🐛fix(variant): SKFP-544 can now share url

src/components/uiKit/search/GlobalSearch/Search/SearchAutocomplete/index.module.scss, src/components/uiKit/search/GlobalSearch/Search/SearchAutocomplete/index.tsx, src/style/themes/kids-first/antd/input.less, src/style/themes/kids-first/antd/selects.less
- closes #[519](https://d3b.atlassian.net/browse/SKFP-519)
Fix input
=> 🐛fix(input): SKFP-519 fix select

src/style/themes/kids-first/antd/selects.less
- closes #[519](https://d3b.atlassian.net/browse/SKFP-519)
Border color on hover was not the good one
Before
After
=> 💎 style(input): SKFP-519 fix select hover

package-lock.json, package.json
- closes #[22](https://ferlab-crsj.atlassian.net/browse/FLUI-22)
Upate pour tester de LUI-22
=> ♻ chore(package): FLUI-22 update ferlab-ui

.storybook/main.js, src/locales/en.ts, src/style/themes/kids-first/_theme.template.scss, src/style/themes/kids-first/antd-kids-first-theme.less, src/style/themes/kids-first/antd/list.less, src/style/themes/kids-first/antd/modal.less, src/style/themes/kids-first/antd/tables.less
- closes #[531](https://d3b.atlassian.net/browse/SKFP-531)
- closes #[500](https://d3b.atlassian.net/browse/SKFP-500)
- closes #[502](https://d3b.atlassian.net/browse/SKFP-502)
Fix theme, add storybook
Before
After
=> Fix/skfp 500 502 531/theme

src/locales/en.ts, src/views/Variants/components/GeneUploadIds/index.tsx
- closes #[547](https://d3b.atlassian.net/browse/SKFP-547)
Fix to the upload gene list 
Before:
After:
=> 🐛fix(variant): SKFP-547 Show results when uploading a gene list

src/locales/en.ts, src/views/DataExploration/components/SetsManagementDropdown/index.tsx
- closes #[562](https://d3b.atlassian.net/browse/SKFP-562)
Add plural version when multiple items are selected 
Before:
After:
=> 🐛fix(exploration): SKFP-562 Sets management dropdown text

src/services/api/savedSet/models.ts, src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx, src/views/DataExploration/components/FileSetSearch.tsx, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx
=> :bugs: Fix wording for files type in set dropdown (filess vs files)

src/views/Variants/components/PageContent/VariantsTable/index.module.scss, src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[574](https://d3b.atlassian.net/browse/SKFP-574)
Adjsut column size
Before
After
...
=> 🐛fix(variant): SKFP-574 adjust cell size

package-lock.json, package.json
=> Feats/skfp 574/gnom ad

src/locales/en.ts, src/store/savedSet/index.ts, src/utils/fieldMapper.ts, src/views/DataExploration/components/SetsManagementDropdown/index.tsx
- closes #[SKFP-568](https://d3b.atlassian.net/browse/SKFP-568)
- Fix the QueryPill title for saved sets
- Fix the file saved set query
Before:
After:
=> 🐛fix(saved-sets): SKFP-568 Fix QueryPill title and file set query

package-lock.json, package.json, src/views/Variants/components/ConsequencesCell/index.tsx, src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #3242
Should use title case
...
=> 🐛fix(variant): SKFP-581 use title case

src/locales/en.ts, src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[SKFP-302](https://d3b.atlassian.net/browse/SKFP-302)
- Added tooltip to Consequences column
Before:
After:
=> ✨feat(variant): SFKP-302 Add tooltip to consequences column

src/locales/en.json, src/views/DataExploration/index.tsx, src/views/Variants/index.tsx
=> :sparkles: Add ontology browsers to clinical facets in explore data

package-lock.json, package.json, src/views/DataExploration/components/PageContent/index.tsx, src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx
- closes #[SKFP-547](https://d3b.atlassian.net/browse/SKFP-547)
- Ajout d'une QueryPill pour gérer les uploaded lists + tests
After:
=> ✨feat(queryPill): SKFP-547 Uploaded List QueryPill 

src/utils/fieldMapper.ts, src/views/DataExploration/components/UploadIds/FileUploadIds.tsx
- closes [SKFP-547](https://d3b.atlassian.net/browse/SKFP-547)
- Fixed file query when searching a participant
- Fixed file QueryPill when uploading a file list 
Before:
After:
=> 🐛fix(data-exploration): SKFP-547 No files when searching by participant

src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- closes [SKFP-559](https://d3b.atlassian.net/browse/SKFP-559)
- Fixed keys to display and sort on the correct field keys
before:
after:
=> 🐛fix(data-exploration): SKFP-559 Participant columns multi-sorting

README.md
- closes [SKFP-527](https://d3b.atlassian.net/browse/SKFP-527)
Added a few details to the README while I didn't have access to the data
=> 🐛fix(docs): SKFP-527 Improve documentation

src/utils/helper.test.tsx, src/utils/helper.ts
- closes [SKFP-592](https://d3b.atlassian.net/browse/SKFP-592)
Fix sorting query when changing page in the table 
Before:
After:
=> 🐛fix(data-exploration): SKFP-592 Fix sorting when changing table page

src/store/savedSet/index.ts, src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/AddRemoveSaveSetModal.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx, src/views/DataExploration/utils/constant.ts, src/views/Variants/components/PageContent/VariantsTable/index.tsx, src/views/Variants/utils/constants.ts
- closes #[493](https://d3b.atlassian.net/browse/SKFP-493)
1. Le nom du bouton devrait être “Save variant set” au singulier.
2. L’accord pour “x variant seclected” devrait être au singulier pour 1 variant
3. Les items Add et Remove ne devraient pas être grisés
=> 🐛fix(variant): SKFP-493 fix variants save set

src/store/savedSet/index.ts, src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/UserSetForm/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx
closes #[493](https://d3b.atlassian.net/browse/SKFP-493)
Fix icon
=> 🐛fix(set): SKFP-494 set the good icons

src/locales/en.ts, src/utils/translation.ts, src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/Variants/components/PageContent/index.tsx
- closes #[493](https://d3b.atlassian.net/browse/SKFP-493)
1. L’étiquette de la pilule devrait être Variant ID
2. Le ID du set dans la pilule n’est pas bon
Before
After
=> 🐛fix(savedset): SKFP-493 fix querybuilder pill

src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- closes #[610](https://d3b.atlassian.net/browse/SKFP-610)
Change O for R
=> ✨feat(file): SKFP-610 change open to registred

src/store/report/thunks.tsx, src/views/Studies/components/PageContent/index.tsx, src/views/Studies/index.tsx, src/views/Variants/components/PageContent/VariantsTable/index.tsx
#BUG 
- closes #[609](https://d3b.atlassian.net/browse/SKFP-609)
Can now save study row in config
=> Fix/skfp 609/study tsv

src/locales/en.ts, src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/UserSetForm/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx
#[BUG | FEATUER | DOC] [TITLE]
- closes #3242
Dans le but d’uniformiser les composantes communes des différents projets, voici le consensus du texte affiché pour les modals des Saved Filter/Set.
Pour chaque modal (et manière d’y accéder), s’assurer que le texte correspond à ce qui est décrit ci-dessous
Saved filter - Modal de création (Accessible via l’icône du crayon de la Query Bar)
Titre: Save this filter
Étiquette: Filter name
Boutons: Cancel & Save
Saved filter - Modal d’édition (Accessible via Manage my filters de la Query Bar & via le Widget du Dashboard)
Titre: Edit filter
Étiquette: Filter name
Boutons: Cancel & Save
Saved set - Modal de création (Accessible via le bouton Save participant|biospecimen|file set)
Titre: Save participant|biospecimen|file set
Étiquette: Set name …
=> 🐛fix(filter): SKFP-587 update text for saved filter and saved set

package-lock.json, package.json, src/components/uiKit/search/GlobalSearch/Search/index.tsx, src/components/uiKit/search/GlobalSearch/index.tsx, src/views/Studies/components/StudySearch/index.tsx
#FEATURE 
- closes #[603](https://d3b.atlassian.net/browse/SKFP-603)
Goal: Modify the Search by study to the improved search on the server side.
E.g. Currently server side strategy: you need to input TARGET: Neuroblastoma  to have the resulting study show up. You cannot write Neuroblastoma as it does not respect the order of the words and characters of the Study Name. 
We would want the Search by study to be able to search for any string Study Name without respecting the specific order of the words and characters. Similar to what we see in prod currently. 
It is not necessary to identify a study by finding the letters within a word. E.g., imagine a value “hello”. We would want to be able to input he or He or HE  to find the value but it is not necessary to find the study by entering …
=> ✨feat(search): SKFP-603 add wild card search

src/views/DataExploration/components/SetsManagementDropdown/AddRemoveSaveSetModal.tsx
- closes #[587](https://d3b.atlassian.net/browse/SKFP-587)
=> fix(set): SKFP-587 fix singular file

src/graphql/files/actions.ts, src/graphql/files/models.ts, src/graphql/files/queries.ts, src/services/api/user/models.ts, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/FileEntity/BiospecimenTable/index.tsx, src/views/FileEntity/ExperimentalProcedure/ExperimentalProcedureTable/index.tsx, src/views/FileEntity/ExperimentalProcedure/index.tsx, src/views/FileEntity/index.tsx, src/views/FileEntity/utils/getExperimentalProcedureColumns.tsx, src/views/FileEntity/utils/getExperimentalProcedureItems.tsx
- Update file queries for sequencing_experiment that is now a list.
- Update file search and file entity pages with the new format for sequencing experiments
After:
=> ✨feat(files): SKFP-619 Sequencing Experiments

package-lock.json, package.json, src/graphql/variants/models.ts, src/views/DataExploration/components/UploadIds/FileUploadIds.tsx, src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx, src/views/Variants/components/GeneUploadIds/index.tsx
- closes [SKFP-605](https://d3b.atlassian.net/browse/SKFP-605)
- Fix matches found when uploading a list of case insensitive ids
- Related to https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/234
[SKFP-605]: https://d3b.atlassian.net/browse/SKFP-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 🐛fix(upload): SKFP-605 Case insensitive upload search

src/views/ParticipantEntity/index.module.scss, src/views/ParticipantEntity/index.tsx
- closes #[403](https://d3b.atlassian.net/browse/SKFP-403)
Ajout de download clinical data participant et family sur la page
=> ✨feat(participant): SKFP-403 add download clinical data

src/style/themes/kids-first/_theme.template.scss
- closes #[647](https://d3b.atlassian.net/browse/SKFP-647)
=> 🪲fix(queryBuilder): SKFP-647 fix query pill and bg color

package-lock.json, package.json
Corrige le problème relié a ferlab-ui qui ne build plus
=> chore(package): update version

public/_headers, public/index.html
We don't want beta portal to be listed by search engine at this moment.
=> :chart_with_upwards_trend: No index, no follow for beta site

package-lock.json, package.json, src/utils/translation.ts, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/DataExploration/index.tsx, src/views/Variants/components/PageContent/VariantsTable/index.tsx, src/views/Variants/components/PageContent/index.tsx
see https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/263
=> 🪲fix(searchafter): FLUI-29 FLUI-39 FLUI-42 fix searchafter

src/views/Dashboard/components/DashboardCards/Notebook/index.module.scss
- closes #[381](https://d3b.atlassian.net/browse/SKFP-381)
La couleur du texte “Currently available…” n’est pas la bonne.
=> 🪲fix(dashboard): SKFP-381 fix color

src/common/constants.ts, src/components/uiKit/reports/DownloadClinicalDataDropdown.tsx, src/components/uiKit/reports/DownloadFileManifestModal/FilesTable.tsx, src/components/uiKit/reports/DownloadFileManifestModal/index.module.scss, src/components/uiKit/reports/DownloadFileManifestModal/index.tsx, src/components/uiKit/reports/DownloadRequestAccessModal/FilesTable.tsx, src/components/uiKit/reports/DownloadRequestAccessModal/index.module.scss, src/components/uiKit/reports/DownloadRequestAccessModal/index.tsx, src/components/uiKit/reports/TooMuchFilesAlert.tsx, src/locales/en.ts, src/services/api/reports/index.ts, src/services/api/reports/models.ts, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- closes #[556](https://d3b.atlassian.net/browse/SKFP-556)
Add file manifest modal
=> ✨feat(file): SKFP-556 add file manifest download

src/components/uiKit/reports/DownloadFileManifestModal/index.tsx, src/locales/en.ts, src/services/api/reports/index.ts
- closes #[556](https://d3b.atlassian.net/browse/SKFP-556)
=> 🪲fix(datafile): SKFP-556 fix typo, style and filenames

src/components/uiKit/reports/DownloadFileManifestModal/index.tsx, src/services/api/reports/index.ts, src/services/api/reports/models.ts
- closes #[556](https://d3b.atlassian.net/browse/SKFP-556)
Update file name to be manifest and familyManifest
=> 🪲fix(manifest): SKFP-556 fix filemanifest name

docker-compose.yaml, src/graphql/utils/Filters.tsx, src/graphql/utils/nameTransformer.tsx
=> :bug: Fix facet display for chromosome 1

package-lock.json, package.json, src/components/uiKit/charts/Bar/index.module.scss, src/services/api/user/models.ts, src/views/DataExploration/components/PageContent/tabs/Summary/AgeAtDiagnosisGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DataCategoryGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DataTypeGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/SunburstGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/index.module.scss, src/views/DataExploration/components/PageContent/tabs/Summary/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/utils/grid.tsx, src/views/ParticipantEntity/utils/files.tsx
- closes #[664](https://d3b.atlassian.net/browse/SKFP-664)
Add grid
Voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/270 et https://www.notion.so/ferlab/ResizableGridLayout-f38c403926a94daaaf7296e7325739f1
=> feat(grid): SKFP-664 add a resizable grid view

src/views/DataExploration/utils/constant.ts
- closes #[667](https://d3b.atlassian.net/browse/SKFP-667)
=> 🪲fix(biospecimen): SKFP-667 set the correct id

package-lock.json, package.json, src/graphql/queries.ts, src/graphql/utils/Filters.tsx, src/graphql/utils/nameTransformer.tsx, src/views/Variants/components/PageContent/VariantsTable/index.tsx
see https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/274
=> fix(filter): SKFP-682 use key_as_string instead of key for boolean

src/views/Variants/components/GeneUploadIds/index.tsx
- closes #[398](https://d3b.atlassian.net/browse/SJIP-398)
Dans l’upload gene list de la page des variants, tenter de loader ce fichier ou copier/coller la liste de gènes.
https://user-images.githubusercontent.com/65532894/236477670-e13d7b07-c6c0-4115-b8c5-0e6e8f585322.mp4
=> fix(gene): SKFP-691 fix gene without alias

src/locales/en.ts, src/views/Persona/components/TermsConditions/index.module.scss, src/views/Persona/components/TermsConditions/index.tsx
- closes #[439](https://d3b.atlassian.net/browse/SKFP-439)
1. Le Box title devrait être « Terms & Conditions » 
2. Il manque un espace entre « Conduct. » et « These » 
3. Les 6 bullets devraient être des chiffres
4. Les hyperliens devraient être soulignés
5. Ajouter un espace entre les « : » et les liens https
6. Ajouter un espace entre « at » et l’email « support@… »
7. « First Name » et « Last Name » devraient être en Title Case
...
=> 🪲fix(registration): SFKP-439 fix typo and styles

src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx
- closes #[699](https://d3b.atlassian.net/browse/SKFP-699)
Upload id ne fonctionne pas
=> fix(biospecimen): SKFP-699 fix biospecimens match check

src/views/Studies/index.tsx
[SKFP-689](https://d3b.atlassian.net/browse/SKFP-689)
Remove code hyperlink in studies page when we don't have the data to redirect.
[SKFP-689]: https://d3b.atlassian.net/browse/SKFP-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(studies): SKFP-689 remove code hyperlink

.gitignore, dev_tools/nginx/nginx-prd.conf, src/views/Community/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx, src/views/ParticipantEntity/utils/diagnosis.tsx, src/views/Studies/index.tsx
[SKFP-684](https://d3b.atlassian.net/browse/SKFP-684)
Add comma as separator to thousand number.
Impacted pages: 
- Dashboard => saved set number
- Studies table => column participants, biospecimen and families
- Community => member count
[SKFP-684]: https://d3b.atlassian.net/browse/SKFP-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(number): SKFP-684 add thousand separator

jest.config.js, package-lock.json, package.json, src/components/uiKit/ComunityProfile/index.tsx, src/tests/setupTests.tsx, src/views/Variants/components/PageContent/index.test.tsx
Update version
Fix test compilation
workaround to prevent recursive error
=> chore(package): update to latest ferlab-ui

package-lock.json, package.json
#[BUG | FEATURE | DOC] [TITLE]
- closes #3739 
[SKFP-684](https://d3b.atlassian.net/browse/SKFP-684)
Fix QA comment to format items count with thousand separator.
[SKFP-684]: https://d3b.atlassian.net/browse/SKFP-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(itemsCount): SKFP-684 update ferlab ui version

package-lock.json, package.json, src/components/uiKit/FilterList/CustomFilterContainer.tsx, src/graphql/utils/Filters.tsx, src/locales/en.ts
- closes #[698](https://d3b.atlassian.net/browse/SKFP-698)
1. L’item « Download data » devrait être Sentence case
2. Le nom des fichier générés pour le TSV devrait dontenir data au lieu de chart
3. Le nom des images contiennent deux fois l’extension
voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/312
=> fix(summary): SKFP-698 fix summary, update ferlab-ui

src/locales/en.ts
- closes #[698](https://d3b.atlassian.net/browse/SKFP-698)
L’item « Download data » devrait être Sentence case
=> fix(summary): SKFP-698 fix typos

package-lock.json, src/graphql/participants/queries.ts, src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx
[SKFP-737](https://d3b.atlassian.net/browse/SKFP-737)
Goal: Change the Study values to point to the publicly facing study codes ( e.g. KF-NBL) instead of the KF operational study codes (e.g. SD____) 
[SKFP-737]: https://d3b.atlassian.net/browse/SKFP-737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(upload): SKFP-737 display KF study match

src/locales/en.ts
https://d3b.atlassian.net/browse/SKFP-758?atlOrigin=eyJpIjoiNTI5ZTIyOTZkNDA2NDkwOWE4OTU2NmE0NzczYTkwMWYiLCJwIjoiaiJ9
=> :pencil: Improve display for family id field in query builder

src/views/Studies/components/PageContent/index.tsx, src/views/Studies/index.tsx
#[BUG] Add dash to empty cell in Studies
[SKFP-688](https://d3b.atlassian.net/browse/SKFP-688)
Add dash in empty dbGaP cell in studies page.
[SKFP-688]: https://d3b.atlassian.net/browse/SKFP-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(studies): SKFP-688 add dash empty cell

src/views/Community/components/Filters/Box/index.tsx
###[BUG] Clear input filter is not working
[SKFP-723](https://d3b.atlassian.net/browse/SKFP-723)
Individual clear filter must work.
see video in the Jira ticket
https://github.com/kids-first/kf-portal-ui/assets/133775440/20192416-f679-4e64-9bd1-084381a87139
[SKFP-723]: https://d3b.atlassian.net/browse/SKFP-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(community): SKFP-723 clear filter input

src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx, src/views/DataExploration/components/UploadIds/FileUploadIds.tsx
[SKFP-761](https://d3b.atlassian.net/browse/SKFP-761)
Uploads need to work 😄 
See ticket description
[SKFP-761]: https://d3b.atlassian.net/browse/SKFP-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(upload): SKFP-761 fix bio and file upload ids

src/graphql/genes/queries.ts, src/views/Variants/components/GeneUploadIds/index.tsx, src/views/Variants2/components/GeneUploadIds/index.tsx, src/views/Variants2/index.tsx
https://d3b.atlassian.net/browse/SKFP-694?atlOrigin=eyJpIjoiYzQ5ZWI3MzdkZjgzNGQ4YjlkNzJkNzY1ODI5YmUyMGEiLCJwIjoiaiJ9
=> :wrench: Fix upload genes in Variants 2

src/locales/en.ts, src/utils/translation.ts
#BUG | Domain tranlation in study
- closes https://d3b.atlassian.net/browse/SKFP-483
- 
update translation in querybar
voir ticket
=> fix: skfp-483 update tranlation for domain in querybar

src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx
[SKFP-761](https://d3b.atlassian.net/browse/SKFP-761)
If you filed two times the same biospecimen id with different cases it should be match two times.
[SKFP-761]: https://d3b.atlassian.net/browse/SKFP-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(upload ids): SKFP-761 biospecimen insensitive case

src/graphql/files/queries.ts
[SKFP-678](https://d3b.atlassian.net/browse/SKFP-678)
Use study.external_id for dbGaP value in file entity, data access table.
[SKFP-678]: https://d3b.atlassian.net/browse/SKFP-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(file): SKFP-678 add dbGaP value

src/views/DataExploration/components/PageContent/tabs/Summary/SunburstGraphCard/GraphContent/index.tsx, src/views/DataExploration/utils/OntologyTree.tsx, src/views/DataExploration/utils/PhenotypeStore.ts
https://d3b.atlassian.net/browse/SKFP-727?atlOrigin=eyJpIjoiYTQ4YzY0MmUxZWY2NDllMDg5OTZmYzAxY2NjYWNmZjMiLCJwIjoiaiJ9
Better looking but this feature needs a serious refactor.
=> :bug: Fix sunburst

src/store/fenceStudies/index.ts, src/views/Dashboard/components/DashboardCards/AuthorizedStudies/index.tsx
closes [#3242](https://d3b.atlassian.net/browse/SKFP-719)
Description
This sqon is not well contructed. It missing a content array wrapping it. See PR that was done for include to fix the same issue:
=> fix: skfp-719 fix auth studies sqon 3

src/store/fenceStudies/thunks.ts
closes [#3242](https://d3b.atlassian.net/browse/SKFP-719)
Description
This sqon is not well contructed. It missing a content array wrapping it. See PR that was done for include to fix the same issue:
=> fix: skfp-719 fix auth studies sqon 5

src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx
[SKFP-800](https://d3b.atlassian.net/browse/SKFP-800)
[SKFP-800]: https://d3b.atlassian.net/browse/SKFP-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dataexplo): SKFP-800 fix demo graph data

src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
[SKFP-796](https://d3b.atlassian.net/browse/SKFP-796)
Link is working now 😄 
Link is not working
https://github.com/kids-first/kf-portal-ui/assets/133775440/5c10633a-4666-44ba-ad81-103d92ae06df
[SKFP-796]: https://d3b.atlassian.net/browse/SKFP-796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(explo): SKFP-796 update link ncit diagnosis

src/views/Dashboard/components/DashboardCards/AuthorizedStudies/index.tsx
closes [#3242](https://d3b.atlassian.net/browse/SKFP-719)
Description
fix the use of a modal instead of a new page
=> fix: skfp-719 auth studies manage connection

src/locales/en.ts
[SKFP-712](https://d3b.atlassian.net/browse/SKFP-712)
Fix title typo
[SKFP-712]: https://d3b.atlassian.net/browse/SKFP-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dataexplo): SKFP-712 fix page title

src/components/uiKit/FilterList/CustomFilterContainer.tsx, src/components/uiKit/FilterList/CustomFilterSelector.tsx, src/components/uiKit/FilterList/index.tsx, src/graphql/queries.ts, src/views/Studies/components/SideBarFacet/index.tsx
[SKFP-790](https://d3b.atlassian.net/browse/SKFP-790)
https://github.com/kids-first/kf-portal-ui/assets/133775440/90329404-3187-4123-b111-9bf6c18fd6ae
https://github.com/kids-first/kf-portal-ui/assets/133775440/566f6832-c7d3-4b10-bd35-3e310eb80030
[SKFP-790]: https://d3b.atlassian.net/browse/SKFP-790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dataexplo): SKFP-790 revert agg refactor

src/views/FileEntity/utils/biospecimens.tsx
[SKFP-803](https://d3b.atlassian.net/browse/SKFP-803)
Before redirect to dashboard.
https://github.com/kids-first/kf-portal-ui/assets/133775440/7beddebc-9e46-46a4-8d60-2130c13d3c54
[SKFP-803]: https://d3b.atlassian.net/browse/SKFP-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(file): SKFP-803 fix part redirect

src/services/api/savedSet/models.ts
https://d3b.atlassian.net/browse/SKFP-814?atlOrigin=eyJpIjoiNmU5ZGViZjVmNGE1NDMzYTgyZjMyN2JjZDU4YzZlYzIiLCJwIjoiaiJ9
=> :bug: Fix Saved Sets when files

src/components/uiKit/FilterList/CustomFilterContainer.tsx, src/components/uiKit/FilterList/index.tsx, src/components/uiKit/FilterList/types.ts
[SKFP-811](https://d3b.atlassian.net/browse/SKFP-811)
Remove decimal on numeric facet for variant position
[SKFP-811]: https://d3b.atlassian.net/browse/SKFP-811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variant): SKFP-811 remove decimal

src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
[SKFP-773](https://d3b.atlassian.net/browse/SKFP-773)
Sort is not working due to a study added not intended for this project.
I use this ticket to fix a JS error on a cell without key.
[SKFP-773]: https://d3b.atlassian.net/browse/SKFP-773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dataexplo): SKFP-773 sort column

src/graphql/files/queries.ts, src/graphql/participants/models.ts, src/views/FileEntity/utils/getDataAccessItems.tsx
=> :pencil: Add consent codes to file entity

src/locales/en.ts, src/views/ParticipantEntity/utils/getProfileItems.tsx
=> :recycle: Change col name

src/graphql/biospecimens/queries.ts
=> :bug: Add parent_sample_id

src/locales/en.ts, src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx, src/views/Variants/utils/constants.ts
#[FEATURE] Shared filter not working from Variants page
[SKFP-836](https://d3b.atlassian.net/browse/SKFP-836)
- Receive a share filter url from Variants page is working now 
- Fix typo in saved sets and filters tooltip (dashboard widget)
- Fix redirect of a variant saved filter from dashboard
https://github.com/kids-first/kf-portal-ui/assets/133775440/54602085-8466-4fd0-9180-9090e31d77d1
[SKFP-836]: https://d3b.atlassian.net/browse/SKFP-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variants): SKFP-836 shared filter

src/store/fenceConnection/index.ts, src/store/fenceConnection/thunks.ts, src/store/fenceStudies/index.ts, src/store/fenceStudies/thunks.ts, src/views/Dashboard/components/DashboardCards/AuthorizedStudies/index.tsx
https://d3b.atlassian.net/browse/SKFP-826?atlOrigin=eyJpIjoiYTg2NTQ3OWE5YTkxNDIwY2FhOGE2MzM2ODQ3MjUzODEiLCJwIjoiaiJ9
=> :recycle: Add support for NCIT fence

package-lock.json, package.json, src/components/uiKit/FilterList/GenericFilters.tsx, src/components/uiKit/FilterList/index.tsx, src/components/utils/filterUtils.tsx, src/graphql/utils/Filters.tsx, src/views/DataExploration/components/PageContent/index.tsx, src/views/DataExploration/index.tsx, src/views/Variants/components/PageContent/index.tsx, src/views/Variants/index.tsx
#[BUG] Remove no data option for range filters
[SKFP-831](https://d3b.atlassian.net/browse/SKFP-831)
Remove no data option for range filters in Variants exploration page.
[SKFP-831]: https://d3b.atlassian.net/browse/SKFP-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variants): SKFP-831 hide no data for range

package-lock.json, package.json, src/auth/keycloak-api/keycloak.ts
SKFP-857 [Keycloak] Update Keycloak to latest version
=> feat: SKFP-857 upgrade keycloak dependancy for KF next

package-lock.json, package.json
- closes #[852](https://d3b.atlassian.net/browse/SKFP-852)
Update to lasted package json
=> fix(summay): SKFP-852 fix layout save behavior

package-lock.json, package.json, src/keycloak.ts
#[FEATURE] Update keycloak dependancy for KF legacy
SKFP-857 [Keycloak] Update Keycloak to latest version
=> feat: #SKFP-857 update keycloak dep for legacy

package-lock.json, package.json
#BUG
Voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/352
=> chore(package): SKFP-852 update package

package-lock.json, package.json, src/views/DataExploration/components/PageContent/tabs/Summary/SunburstGraphCard/GraphContent/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/SunburstGraphCard/utils/sunburst-d3.jsx, src/views/FileEntity/Title/index.tsx
- closes #[858](https://d3b.atlassian.net/browse/SKFP-858)
- related https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/353
he mouse over is cut off when close to the graph border. This is commonly seen when we reduce the size of the graphs
https://github.com/kids-first/kf-portal-ui/assets/65532894/8d6150f0-5646-43f5-ad50-9831a6b85c9e
https://github.com/kids-first/kf-portal-ui/assets/65532894/78d4fab1-020b-4a2d-8036-e14e1c583ffd
=> fix(grid): SKFP-858 fix mouseover cutoff

src/locales/en.ts, src/views/Dashboard/components/DashboardCards/SavedFilters/index.module.scss, src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/index.module.scss, src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
#[FEATURE] Dashboard widget, update empty tab for filter and set
[SKFP-861](https://d3b.atlassian.net/browse/SKFP-861)
- Rework empty tab for filter and set widget, change wording and style.
- Rework style for list tab when we have no scroll to display fully height background
(Validate by Lucas)
[SKFP-861]: https://d3b.atlassian.net/browse/SKFP-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(widget): SKFP-861 empty for filter and set

src/auth/keycloak-api/utils.ts, src/views/Profile/Settings/cards/Identification/index.tsx
[SKFP-910](https://d3b.atlassian.net/browse/SKFP-910)
After login with email and password, when the user go on settings page it will not crashed.
Error 500
[SKFP-910]: https://d3b.atlassian.net/browse/SKFP-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(settings): SKFP-910 500 login with mail pwd

.gitignore, cypress.config.ts, cypress/e2e/Navigation/Logout.cy.ts, cypress/plugins/index.ts, cypress/support/commands.ts, cypress/support/createUUID.ts, cypress/support/e2e.js, cypress/support/index.d.ts, cypress/support/utils.ts, cypress/tsconfig.json, package-lock.json, package.json
#[FEATURE] Setup Cypress tests
- closes #SKFP-746
First setup for Cypress tests
=> feat: SKFP-746 Setup Cypress tests

package-lock.json, package.json, src/views/Variants/components/PageContent/VariantsTable/index.module.scss, src/views/Variants/components/PageContent/VariantsTable/index.tsx
[SKFP-880](https://d3b.atlassian.net/browse/SKFP-880)
Acceptance Criterias / Retour QA de JP
- Regression NO_GENE displayed instead of dash in Gene column
- Increase variant column
- Reduce Most Del Csq column and add ellipsis
- Most Del Csq column display aa_change at the end no hsgv
[SKFP-880]: https://d3b.atlassian.net/browse/SKFP-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variants): SKFP-880 fix JP QA

src/style/themes/kids-first/antd/tables.less
SKFP-926
In fixed columns, line colors must be alternated. (sorted or not, selected or not)
=> fix(style): SKFP-926 fixed column color

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
#FIX: adjust table data to match with Facets formatting
- closes [#SKFP-817](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-817)
=> fix: SKFP-817 adjust table data to match with Facets formatting

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/VariantEntity/utils/summary.tsx
- closes [#SKFP-817(https://d3b.atlassian.net/browse/SKFP-817?focusedCommentId=20584)
This adresses some QA comments for initial SKFP-817
=> fix: SKFP-817 adjust Variant entity sample type casing and biospecimen availability mapping 

src/store/user/thunks.test.tsx, src/store/user/thunks.ts, src/store/user/thunksTestData.ts
[SKFP-941](https://d3b.atlassian.net/browse/SKFP-941)
- User config from data exploration summary reset should work
See video in ticket please.
https://github.com/kids-first/kf-portal-ui/assets/133775440/d0cc2cc1-bedb-44e7-bcd6-815dc4efe45e
[SKFP-941]: https://d3b.atlassian.net/browse/SKFP-941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(user): SKFP-941 update user config

src/graphql/files/models.ts, src/graphql/files/queries.ts, src/graphql/participants/models.ts, src/services/api/cavatica/index.ts, src/store/passport/thunks.test.ts, src/store/passport/thunks.ts, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.test.tsx
#FEAT: export custom metadata from data files to cavatica
- closes [#SKFP-888](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-888)
=> feat: SKFP-888 export custom metadata from data files to cavatica

src/App.tsx, src/locales/en.ts, src/utils/routes.ts, src/views/VariantEntity2/index.module.scss, src/views/VariantEntity2/index.tsx
- add new url to dev variant entity v2
url example : https://localhost:3000/variants2/10-79386441-G-A
N/A
=> feat(variant2): SKFP-899 add url

package-lock.json, package.json, src/components/Cavatica/AnalyzeButton/index.tsx, src/components/uiKit/reports/DownloadFileManifestModal/index.tsx, src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx
- closes [#SKFP-949](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-949)
=> feat: SKFP-949 add tooltips to disabled buttons

src/components/uiKit/reports/DownloadFileManifestModal/index.tsx, src/graphql/files/queries.ts, src/views/FileEntity/Title/index.tsx, src/views/FileEntity/index.tsx
- closes [#SKFP-953](https://d3b.atlassian.net/browse/SKFP-953)
With Family:
Without Family:
=> feat: SKFP-953 Remove the option to include family member files if no family

src/services/api/cavatica/index.ts, src/store/passport/metadata.ts, src/store/passport/thunks.test.ts
- closes [#SKFP-888](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-888)
=> fix: SKFP-888 add missing observed phenotype source text

src/graphql/participants/queries.ts, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx, src/views/DataExploration/utils/OntologyTree.tsx, src/views/DataExploration/utils/PhenotypeStore.ts, src/views/DataExploration/utils/selectionSqon.ts
- closes [#SKFP-943](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-943)
=> fix: SKFP-943 show missing values for phenotypes

package-lock.json, package.json, src/store/fences/thunks.ts
#FIX: various bugs in auth studies
- closes[ #SKFP-964](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-964)
All points are fixed. 
Point 1 is fixed in this MR.
Point 2.a and 2.b were fixed in the backend
Point 2.c is fixed in this MR
=> fix: SKFP-964 various bugs in auth studies

src/store/report/index.ts, src/store/report/thunks.tsx, src/views/FileEntity/BiospecimenTable/index.tsx
- closes [#SKFP-966](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-966)
=> fix: SKFP-966 Adjust Track Report Download format in GA4

src/views/VariantEntity2/index.module.scss, src/views/VariantEntity2/utils/summary.tsx
[SKFP-900](https://d3b.atlassian.net/browse/SKFP-900)
- add clinVar link
[SKFP-900]: https://d3b.atlassian.net/browse/SKFP-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variant): SKFP-900 add clinvar link

package-lock.json, package.json
- closes #[924](https://d3b.atlassian.net/browse/SKFP-924)
Voir PR https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/402
=> fix(authorizedstudies): SKFP-924 fix title and tooltip

package-lock.json, package.json, src/views/VariantEntity2/utils/summary.tsx
[SKFP-900](https://d3b.atlassian.net/browse/SKFP-900)
- Fix summary colors in banner and in details parts
[SKFP-900]: https://d3b.atlassian.net/browse/SKFP-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variant): SKFP-900 style

cypress/e2e/Colonnes/TableauxPageFile.cy.ts, cypress/e2e/Consultation/PageParticipant.cy.ts, cypress/e2e/Consultation/PageVariant.cy.ts, cypress/e2e/Consultation/TableauParticipants.cy.ts, cypress/e2e/Consultation/TableauStudies.cy.ts, cypress/e2e/Consultation/TableauVariants.cy.ts, cypress/e2e/Facettes/PageDataExploration.cy.ts, cypress/e2e/Facettes/PageStudies.cy.ts, cypress/e2e/Facettes/PageVariants.cy.ts, cypress/e2e/Requetes/ActionsSur0Requete.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts, cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts, cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts, cypress/e2e/Telechargement/TableauStudies.cy.ts, cypress/e2e/Telechargement/TableauxPageFile.cy.ts, cypress/fixtures/ExportTableauParticipants.json, cypress/fixtures/ExportTableauStudies.json, cypress/support/commands.ts, cypress/support/index.d.ts
- closes #SKFP-994
[SKFP-994](https://d3b.atlassian.net/browse/SKFP-994)
[SKFP-994]: https://d3b.atlassian.net/browse/SKFP-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-994 Adjust Cypress tests

src/components/Layout/Header/index.module.scss, src/components/uiKit/PopoverContentLink/index.module.scss, src/components/uiKit/search/SearchLabel/index.module.scss, src/components/uiKit/select/SelectItem/index.module.scss, src/style/themes/kids-first/_theme.template.scss, src/style/themes/kids-first/antd-kids-first-theme.less, src/style/themes/kids-first/antd/buttons.less, src/style/themes/kids-first/antd/dropdowns.less, src/style/themes/kids-first/antd/form.less, src/style/themes/kids-first/antd/input.less, src/style/themes/kids-first/antd/list.less, src/style/themes/kids-first/antd/pagination.less, src/style/themes/kids-first/antd/selects.less, src/style/themes/kids-first/antd/tables.less, src/style/themes/kids-first/antd/tabs.less, src/style/themes/kids-first/antd/tags.less, src/style/themes/kids-first/colors.less, src/views/Dashboard/components/CardHeader/index.module.scss, src/views/Dashboard/components/DashboardCards/CaringForChildrenWithCovid/index.module.scss, src/views/Dashboard/components/DashboardCards/Notebook/index.module.scss, src/views/FileEntity/SummaryHeader/index.module.scss, src/views/FileEntity/Title/index.module.scss, src/views/ParticipantEntity/SummaryHeader/index.module.scss, src/views/Studies/components/SideBarFacet/index.module.scss, src/views/VariantEntity/SummaryHeader/index.module.scss, src/views/VariantEntity/index.module.scss, src/views/VariantEntity2/index.module.scss
[SKFP-983](https://d3b.atlassian.net/browse/SKFP-983)
[SKFP-988](https://d3b.atlassian.net/browse/SKFP-988)
- Update tag colors
- Remove body colors and replace by the new gray range
[SKFP-983]: https://d3b.atlassian.net/browse/SKFP-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-988]: https://d3b.atlassian.net/browse/SKFP-988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(theme): SKFP-983 and SKFP-988 update colors

package-lock.json, package.json
[SKFP-900](https://d3b.atlassian.net/browse/SKFP-900)
- Fix colon color in summary variant v2 from Ferlab
[SKFP-900]: https://d3b.atlassian.net/browse/SKFP-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variant): SKFP-900 update ferlab

src/views/VariantEntity/index.tsx
[SKFP-985](https://d3b.atlassian.net/browse/SKFP-985)
- Remove NO_GENE in consequence section (variant entity)
[SKFP-985]: https://d3b.atlassian.net/browse/SKFP-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variant): SJIP-985 remove no gene in csq table

cypress/e2e/Consultation/PageVariant.cy.ts, cypress/e2e/Consultation/TableauVariants.cy.ts, cypress/e2e/Facettes/PageDataExploration.cy.ts, cypress/e2e/Facettes/PageVariants.cy.ts, cypress/e2e/Navigation/Pages.cy.ts, cypress/e2e/Requetes/ActionsSur0Requete.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts, cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts, cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts
Closes [SKFP-999](https://d3b.atlassian.net/browse/SKFP-999)
[SKFP-999]: https://d3b.atlassian.net/browse/SKFP-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-999 Adjust Cypress tests

src/store/passport/thunks.ts
- https://d3b.atlassian.net/browse/SKFP-1001
Certains controlled files devraient fonctionner, c'est lié a comment le tableau des acls est construit
=> fix(fence): fix unauthorized files

cypress/e2e/Consultation/PageVariant.cy.ts
- closes #3242
- Add cypress tests
=> feat(cypress): SKFP-1000 Variant Entity page

src/views/Dashboard/components/DashboardCards/index.tsx
- closes #[1002](https://d3b.atlassian.net/browse/SKFP-1002)
Mask the Variant Workbench widget. As we will develop the Cavatica Variant Workbench, we will rework this widget.
=> feat(dashboard): SKFP-1002 hide notebook widget

src/components/Layout/Header/index.module.scss, src/components/Layout/Header/index.tsx, src/locales/en.ts
[SKFP-968](https://d3b.atlassian.net/browse/SKFP-968)
- remove forum link
- update existing links
- add divider between documentation and contact
[SKFP-968]: https://d3b.atlassian.net/browse/SKFP-968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(header): SKFP-968 resources dropdown

src/style/themes/kids-first/antd-kids-first-theme.less
- closes [#SKFP-1007](https://d3b.atlassian.net/browse/SKFP-1007)
Before: 
After:
=> fix: SKFP-1007 update link and button link styles to match ui kit

package-lock.json, package.json, src/locales/en.ts, src/utils/translation.ts, src/views/Community/index.tsx
- closes #[3242](https://d3b.atlassian.net/browse/SKFP-1003)
=> fix(variant): SKFP-1003 fix tag

package-lock.json, package.json, src/locales/en.ts, src/utils/translation.ts, src/views/Community/index.tsx, src/views/Dashboard/components/DashboardCards/AuthorizedStudies/index.tsx, src/views/Dashboard/components/DashboardCards/Cavatica/index.tsx, src/views/VariantEntity/index.module.scss, src/views/VariantEntity/index.tsx, src/views/VariantEntity/utils/summary.tsx
[SKFP-1004](https://d3b.atlassian.net/browse/SKFP-1004)
1. Le souligné du gène devrait être de la même couleur que le texte
2. Le tag devrait être gris comme les autres
3. L’icône devrait être de la même couleur que celui pour Canonical
4. Tous les tableaux ne devraient pas avoir les lignes alternés gris/blanc
[SKFP-1004]: https://d3b.atlassian.net/browse/SKFP-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variant): SKFP-1004 style fixes

package-lock.json, package.json
[SKFP-1009](https://d3b.atlassian.net/browse/SKFP-1009)
- align functionnal scores
[SKFP-1009]: https://d3b.atlassian.net/browse/SKFP-1009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variant): SKFP-1009 align scores

src/style/themes/kids-first/_theme.template.scss
- closes [#3242](https://d3b.atlassian.net/browse/SKFP-665)
Before: 
After:
=> fix: SKFP-665 adjust border color on query bar

package-lock.json, package.json, src/store/passport/slice.ts, src/utils/translation.ts
[SKFP-1018](https://d3b.atlassian.net/browse/SKFP-1018)
- Add loader on copy files button to analyse in cavatica
https://github.com/kids-first/kf-portal-ui/assets/133775440/fd715e0a-6233-4a1d-807f-8e9beab881d6
[SKFP-1018]: https://d3b.atlassian.net/browse/SKFP-1018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(cavatica): SKFP-1018 add loader on copy files

src/locales/en.ts, src/views/FileEntity/BiospecimenTable/index.module.scss, src/views/FileEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/BiospecimenTable/index.tsx, src/views/ParticipantEntity/FileTable/index.tsx, src/views/ParticipantEntity/index.module.scss
[SKFP-1011](https://d3b.atlassian.net/browse/SKFP-1011)
- update design of View in exploration button in participant and file entities pages
[SKFP-1011]: https://d3b.atlassian.net/browse/SKFP-1011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(entity): SKFP-1011 view explo btn style

src/views/Studies/utils/helper.ts
- closes [#SKFP-1047](https://d3b.atlassian.net/browse/SKFP-1047)
=> fix: SKFP-1047 Update pedcbioportal studyID link

src/components/uiKit/FilterList/CustomFilterContainer.tsx
- closes [#SKFP-938](https://d3b.atlassian.net/browse/SKFP-938)
=> fix: SKFP-938 adjust facet value to match query bar pill

.github/workflows/quality.yml
- closes [#SKFP-1067](https://d3b.atlassian.net/browse/SKFP-1067)
=> fix: SKFP-1067 Adjust CI lint and tests to work on dev branch

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
- closes [#SKFP-1065](https://d3b.atlassian.net/browse/SKFP-1065)
=> feat: SKFP-1065 Add hyperlink on the Histological Diagnosis field formatting

src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.module.scss, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
- closes [#SKFP-1065](https://d3b.atlassian.net/browse/SKFP-1065)
=> fix: SKFP-1065 add spacing in mondo code display

src/components/UserDashboard/index.js, src/components/UserProfile/UserProfilePage.js, src/style/themes/kids-first/dist/_colors.scss, src/style/themes/kids-first/dist/antd.css
- closes [#SKFP-1068](https://d3b.atlassian.net/browse/SKFP-1068)
=> feat(legacy): #SKFP-1068 hide VWB and setting page in profile

docs/deployment.md
- closes [#SKFP-1062](https://d3b.atlassian.net/browse/SKFP-1062)
=> feat: SKFP-1062 update deployment procedure for PROD

cypress.config.ts, cypress/e2e/Consultation/PageParticipant.cy.ts, cypress/e2e/Consultation/TableauBiospecimens.cy.ts, cypress/e2e/Consultation/TableauFiles.cy.ts, cypress/e2e/Consultation/TableauParticipants.cy.ts, cypress/e2e/Consultation/TableauStudies.cy.ts, cypress/e2e/Consultation/TableauVariants.cy.ts, cypress/e2e/Facettes/PageDataExploration.cy.ts, cypress/e2e/Facettes/PageStudies.cy.ts, cypress/e2e/Facettes/PageVariants.cy.ts, cypress/e2e/Requetes/ActionsSur0Requete.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts, cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts, cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts, cypress/e2e/Telechargement/TableauBiospecimens.cy.ts, cypress/support/commands.ts, cypress/support/index.d.ts
- closes #SKFP-1073
[SKFP-1073](https://d3b.atlassian.net/browse/SKFP-1073)
[SKFP-1073]: https://d3b.atlassian.net/browse/SKFP-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1073 Adjust Cypress tests

src/utils/dataFiles.ts
- closes [#SKFP-1059](https://d3b.atlassian.net/browse/SKFP-1059)
=> fix: SKFP-1059 debug acl permissions on file

src/graphql/files/queries.ts, src/utils/dataFiles.ts
- closes [#SKFP-1059](https://d3b.atlassian.net/browse/SKFP-1059)
=> fix: SKFP-1059 add acls to file entity request

package-lock.json, package.json, src/graphql/quickFilter/queries.ts, src/locales/en.ts, src/views/DataExploration/components/PageContent/index.tsx, src/views/DataExploration/index.tsx
[SKFP-1043](https://d3b.atlassian.net/browse/SKFP-1043) => subtasks : 
- [SKFP-1042](https://d3b.atlassian.net/browse/SKFP-1042)
- [SKFP-1044](https://d3b.atlassian.net/browse/SKFP-1044)
- [SKFP-1045](https://d3b.atlassian.net/browse/SKFP-1045)
- [SKFP-1046](https://d3b.atlassian.net/browse/SKFP-1046)
- all suggestion list display except substask [SKFP-1078](https://d3b.atlassian.net/browse/SKFP-1078)
https://github.com/kids-first/kf-portal-ui/assets/133775440/7c3118c3-004c-4a6f-bc83-f74575ee6a79
[SKFP-1043]: https://d3b.atlassian.net/browse/SKFP-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1042]: https://d3b.atlassian.net/browse/SKFP-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
=> feat(Quick Filter): SKFP-1043 display suggestion list

src/locales/en.ts, src/services/api/arranger/models.ts, src/store/global/thunks.ts, src/store/global/types.ts, src/views/Community/index.tsx
- closes [#SKFP-1077](https://d3b.atlassian.net/browse/SKFP-1077)
=> feat: SKFP-1077 add total members count in community page

src/locales/en.ts, src/store/notebook/slice.ts, src/store/notebook/thunks.ts, src/views/Dashboard/components/DashboardCards/Notebook/index.tsx
- closes #[1081](https://d3b.atlassian.net/browse/SKFP-1081)
[JIRA LINK]
=> fix(notebook): SFKP-1081 add error message, fix typo

src/views/Dashboard/components/DashboardCards/Notebook/index.tsx
- closes #[1083](https://d3b.atlassian.net/browse/SKFP-1083)
=> fix(vwb): SKFP-1083 fix fences

src/services/api/notebook/model.ts, src/store/notebook/thunks.ts
- closes #[1084](https://d3b.atlassian.net/browse/SKFP-1084)
=> feat(vwb): Manage new redirect behavior

src/store/notebook/index.ts, src/store/notebook/selector.ts, src/store/notebook/slice.ts, src/store/notebook/types.ts, src/views/Dashboard/components/DashboardCards/Notebook/index.tsx
- closes #[1084](https://d3b.atlassian.net/browse/SKFP-1084)
Lorsqu'on appuie sur le bouton launch in cavatica, il reste en spin mode même si le nouvel onglet est ouvert
=> fix(vwb): SKFP-1084 manage loading state

src/store/passport/metadata.ts, src/store/passport/thunks.test.ts
- closes [#SKFP-1086](https://d3b.atlassian.net/browse/SKFP-1086)
=> fix: SKFP-1086 remove some cavatica metadata

package-lock.json, package.json, src/graphql/quickFilter/queries.ts, src/views/DataExploration/index.tsx
[SKFP-1048](https://d3b.atlassian.net/browse/SKFP-1048)
- Add to QB from level 1
- Add to QB from level 2
NA
- Level 1
https://github.com/kids-first/kf-portal-ui/assets/133775440/dd1b387b-208e-4adb-acb3-838228bb838e
- Level 2
https://github.com/kids-first/kf-portal-ui/assets/133775440/c74dd21e-8d70-414d-8a01-556c5fb5dfbe
[SKFP-1048]: https://d3b.atlassian.net/browse/SKFP-1048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(quick filter): SKFP-1048 add apply method

src/locales/en.ts, src/services/analytics.ts, src/store/notebook/thunks.ts, src/views/Dashboard/components/DashboardCards/Notebook/index.tsx, src/views/Dashboard/components/DashboardCards/index.tsx
- closes #[1082](https://d3b.atlassian.net/browse/SKFP-1082)
- closes #[1066](https://d3b.atlassian.net/browse/SKFP-1066)
- closes #[1088](https://d3b.atlassian.net/browse/SKFP-1088)
- closes #[1090](https://d3b.atlassian.net/browse/SKFP-1090)
=> fix(notebook): SKFP-1082 SKFP-1088 fix type, add analytics

src/views/Studies/utils/helper.ts
- closes [#SKFP-1087](https://d3b.atlassian.net/browse/SKFP-1087)
=> feat: SKFP-1087 update study mappings for pedc bioportal

src/views/Studies/components/PageContent/index.tsx
- closes [#SKFP-1093](https://d3b.atlassian.net/browse/SKFP-1093)
=> fix: SKFP-1093 add the ability to search in the middle of a string

package-lock.json, package.json, src/views/DataExploration/index.tsx
[SKFP-1042](https://d3b.atlassian.net/browse/SKFP-1042)
- reduce number of call to get suggestion list
[SKFP-1042]: https://d3b.atlassian.net/browse/SKFP-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(quick filter): SKFP-1042 reduce number of call to get suggestion list

package-lock.json, package.json, src/style/themes/kids-first/_theme.template.scss
[SKFP-1046](https://d3b.atlassian.net/browse/SKFP-1046)
- extract variable for background color
- remove space
[SKFP-1046]: https://d3b.atlassian.net/browse/SKFP-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(quickfilter): SKFP-1046 higlight style

package-lock.json, package.json
- closes [#SKFP-1053](https://d3b.atlassian.net/browse/SKFP-1053)
=> fix: SKFP-1053 remove visual glitch on side menu collapse

package-lock.json, package.json, src/views/VariantEntity/index.tsx, src/views/VariantEntity/utils/consequence.tsx, src/views/VariantEntity/utils/summary.tsx
- closes [#SKFP-1104](https://d3b.atlassian.net/browse/SKFP-1104)
=> fix: SKFP-1104 temporarily change variant value renders

package-lock.json, package.json, src/locales/en.ts, src/views/DataExploration/index.tsx
[SKFP-1106](https://d3b.atlassian.net/browse/SKFP-1106)
[SKFP-1107](https://d3b.atlassian.net/browse/SKFP-1107)
- clear instead of cancel button
- total results
[SKFP-1106]: https://d3b.atlassian.net/browse/SKFP-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1107]: https://d3b.atlassian.net/browse/SKFP-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(quick filter): SKFP-1106 total result SKFP-1107 clear btn

package-lock.json, package.json
[SKFP-1111](https://d3b.atlassian.net/browse/SKFP-1111)
- not checked all value with the same label
[SKFP-1111]: https://d3b.atlassian.net/browse/SKFP-1111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(quickfilter): SKFP-1111 multiple value checked

package-lock.json, package.json
[SKFP-1108](https://d3b.atlassian.net/browse/SKFP-1108)
[SKFP-1109](https://d3b.atlassian.net/browse/SKFP-1109)
[SKFP-1112](https://d3b.atlassian.net/browse/SKFP-1112)
- clear style button
- all/none style actions
- suggestion list max height
- SKFP-1108
hover
- SKFP-1109
Level 1
Level 2
- SKFP-1112
hover
[SKFP-1108]: https://d3b.atlassian.net/browse/SKFP-1108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1109]: https://d3b.atlassian.net/browse/SKFP-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1112]: https://d3b.atlassian.net/browse/SKFP-1112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(quick filter): SKFP-1108 SKFP-1109 SKFP-1112

src/locales/en.ts, src/views/Dashboard/components/DashboardCards/Notebook/index.tsx
- closes #[1102](https://d3b.atlassian.net/browse/SKFP-1102)
Re-add Data Studio link
=> fix(vwb): SKFP-1102 update description

src/locales/en.ts
- closes [#SKFP-1100](https://d3b.atlassian.net/browse/SKFP-1100)
=> fix: SKFP-1100 adjust saved set success message

package-lock.json, package.json
- closes[ #SKFP-1096](https://d3b.atlassian.net/browse/SKFP-1096)
=> fix: SKFP-1096 use default link hover color from theme

package-lock.json, package.json
- closes [#SKFP-1097](https://d3b.atlassian.net/browse/SKFP-1097)
=> fix: SKFP-1097 adjust auth studies allowed files count

cypress/e2e/SaveSetButton/PageDataExploration.cy.ts, cypress/e2e/SaveSetButton/PageVariants.cy.ts, cypress/support/commands.ts, cypress/support/index.d.ts
- closes #SKFP-1125
[SKFP-1125](https://d3b.atlassian.net/browse/SKFP-1125)
[SKFP-1125]: https://d3b.atlassian.net/browse/SKFP-1125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1125 Add SaveSetButton Cypress tests

package-lock.json, package.json, src/graphql/quickFilter/queries.ts
[SJFP-1149](https://d3b.atlassian.net/browse/SKFP-1149)
- reduce btn size
- Level 1
- Level 2
=> fix(qf): SKFP-1149 apply btn style and clean

cypress/e2e/Consultation/PageParticipant.cy.ts, cypress/e2e/Consultation/PageProfileSettings.cy.ts, cypress/e2e/Consultation/TableauParticipants.cy.ts, cypress/e2e/Navigation/Pages.cy.ts, cypress/support/commands.ts, cypress/support/index.d.ts
- closes #SKFP-1150
[SKFP-1150](https://d3b.atlassian.net/browse/)
[SKFP-1150]: https://d3b.atlassian.net/browse/SKFP-1150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cypress/skfp 1150 feat: SKFP-1150 Add Profile Settings Cypress tests

package-lock.json, package.json, src/locales/en.ts, src/services/api/savedSet/index.ts, src/services/api/savedSet/models.ts, src/store/savedSet/thunks.ts, src/views/Dashboard/components/DashboardCards/BiospecimenRequests/index.tsx, src/views/Dashboard/components/DashboardCards/index.tsx
- closes #[1126](https://d3b.atlassian.net/browse/SKFP-1126)
see https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/471
=> feat(dashboard): SKFP-1126 add biospecimen requests widgets

package-lock.json, package.json, src/locales/en.ts, src/middleware/AuthMiddleware.tsx, src/store/savedSet/index.ts, src/store/savedSet/slice.ts, src/views/Dashboard/components/DashboardCards/BiospecimenRequests/index.tsx, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/utils/constant.ts, src/views/DataExploration/utils/selectionSqon.ts
- closes #[1126](https://d3b.atlassian.net/browse/SKFP-1126)
=> fix(widget): SKFP-1126 fix share link

src/locales/en.ts, src/middleware/AuthMiddleware.tsx, src/store/savedFilter/thunks.ts
[SKFP-1151](https://d3b.atlassian.net/browse/SKFP-1151)
- don't display error message just login page and redirect after
- Share filter
https://github.com/kids-first/kf-portal-ui/assets/133775440/39fc71e7-72b5-4750-af03-963c7eb8a32d
- Share Biospecimen request
https://github.com/kids-first/kf-portal-ui/assets/133775440/7974ea73-db14-43e6-a1ba-aacbc1848a5e
[SKFP-1151]: https://d3b.atlassian.net/browse/SKFP-1151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(share): SKFP-1151 manage share link not login

src/views/Dashboard/components/DashboardCards/BiospecimenRequests/index.tsx
- closes #[1126](https://d3b.atlassian.net/browse/SKFP-1126)
Bad date format
=> fix(biospecimen): SKFP-1126 fix date format

src/services/api/persona/index.ts, src/services/api/persona/models.ts, src/store/persona/thunks.ts
- closes [#SKFP-1155](https://d3b.atlassian.net/browse/SKFP-1155)
=> fix: SKFP-1155 add back subscription to newsletter in registration

src/locales/en.ts, src/views/Dashboard/components/DashboardCards/Notebook/index.tsx
- closes [#SKFP-1120](https://d3b.atlassian.net/browse/SKFP-1120)
- closes [#SKFP-1122](https://d3b.atlassian.net/browse/SKFP-1122)
- closes[ #SKFP-1146](https://d3b.atlassian.net/browse/SKFP-1146)
https://www.notion.so/ferlab/Cavatica-VWB-UI-4ecde7f599a742c9a8c85fbd8d3709a3
=> fix: SKFP-1120 adjust various translations

cypress/e2e/Consultation/Login.cy.ts, cypress/e2e/Consultation/TableauBiospecimens.cy.ts, cypress/e2e/Consultation/TableauStudies.cy.ts, cypress/e2e/Facettes/PageDataExploration.cy.ts, cypress/e2e/Navigation/Logout.cy.ts, cypress/e2e/Requetes/ActionsSur0Requete.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts, cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts, cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts
- closes #SKFP-1167
- relate to #SKFP-1132 and SKFP-1052
[SKFP-1167](https://d3b.atlassian.net/browse/SKFP-1167)
[SKFP-1132](https://d3b.atlassian.net/browse/SKFP-1132)
[SKFP-1052](https://d3b.atlassian.net/browse/SKFP-1052)
[SKFP-1167]: https://d3b.atlassian.net/browse/SKFP-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1132]: https://d3b.atlassian.net/browse/SKFP-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1052]: https://d3b.atlassian.net/browse/SKFP-1052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1167 Adjust Cypress tests related to SKFP-1132 and SKFP-1052

cypress/e2e/Filtres/PageDataExploration.cy.ts, cypress/e2e/Filtres/PageVariants.cy.ts, cypress/e2e/Navigation/Pages.cy.ts, cypress/e2e/Widgets/SavedFilters.cy.ts
- closes #SKFP-1168
[SKFP-1168](https://d3b.atlassian.net/browse/SKFP-1168)
[SKFP-1168]: https://d3b.atlassian.net/browse/SKFP-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1168 Add Saved Filters Widget Cypress tests

cypress/e2e/Navigation/Pages.cy.ts, cypress/e2e/Widgets/SavedFilters.cy.ts, cypress/e2e/Widgets/SavedSets.cy.ts
- closes #SKFP-1170
[SKFP-1170](https://d3b.atlassian.net/browse/SKFP-1170)
[SKFP-1170]: https://d3b.atlassian.net/browse/SKFP-1170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1170 Add Saved Sets Widget Cypress tests

package-lock.json, package.json
voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/482
=> chore(package): SKFP-1010 update ferlab-ui

package-lock.json, package.json
- closes [#SKFP-1152](https://d3b.atlassian.net/browse/SKFP-1152)
=> fix: SKFP-1152 change color and style in dashboard cards title

cypress/e2e/Consultation/TableauStudies.cy.ts, cypress/e2e/Facettes/PageDataExploration.cy.ts, cypress/e2e/Requetes/ActionsSur0Requete.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts, cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts, cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts
- closes #SKFP-1175
- relate to #SKFP-1171 and SKFP-1052
[SKFP-1175](https://d3b.atlassian.net/browse/SKFP-1175)
[SKFP-1171](https://d3b.atlassian.net/browse/SKFP-1171)
[SKFP-1052](https://d3b.atlassian.net/browse/SKFP-1052)
[SKFP-1175]: https://d3b.atlassian.net/browse/SKFP-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1171]: https://d3b.atlassian.net/browse/SKFP-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1052]: https://d3b.atlassian.net/browse/SKFP-1052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1175 Adjust Cypress tests related to SKFP-1171 and SKFP-1052

package-lock.json, package.json
- closes #[1134](https://d3b.atlassian.net/browse/SKFP-1134)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1134)
=> chore(package): SKFP-1134 update ferlab-ui

cypress/e2e/Widgets/CavaticaProjects.cy.ts
- closes #SKFP-1177
[SKFP-1177](https://d3b.atlassian.net/browse/SKFP-1177)
[SKFP-1177]: https://d3b.atlassian.net/browse/SKFP-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1177 Add Cavatica Widget Cypress tests

src/store/savedSet/thunks.ts
- closes #[1153](https://d3b.atlassian.net/browse/SKFP-1153)
https://github.com/kids-first/kf-portal-ui/assets/65532894/4718d45a-1be0-4a9a-8b9b-5d6006dee488
=> fix(biosp): SKFP-1153 prevent duplicate when sharing a biospeciment request

src/locales/en.ts, src/views/DataExploration/components/TreeFacet/TreeFacetModal.tsx
- closes #[1172](https://d3b.atlassian.net/browse/SKFP-1172)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1172)
=> fix(phenotype): SKFP-1172 add missing trads

cypress/e2e/Widgets/BiospecimenRequests.cy.ts, cypress/support/commands.ts, cypress/support/index.d.ts
- closes #SKFP-1202
[SKFP-1202](https://d3b.atlassian.net/browse/SKFP-1202)
[SKFP-1202]: https://d3b.atlassian.net/browse/SKFP-1202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1202 Add Widget Biospecimen Requests Cypress tests

cypress/e2e/Widgets/AuthorizedStudies.cy.ts, cypress/e2e/Widgets/KidsFirstFhirApi.cy.ts, cypress/e2e/Widgets/VariantWorkbench.cy.ts
- closes #SKFP-1203
[SKFP-1203](https://d3b.atlassian.net/browse/SKFP-1203)
[SKFP-1203]: https://d3b.atlassian.net/browse/SKFP-1203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1203 Add FHIR and VWB Widgets Cypress tests

package-lock.json, package.json, src/locales/en.ts, src/views/Community/Member/index.tsx, src/views/Community/constants.ts, src/views/Profile/View/index.tsx
voir https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/496
=> fix(community): SKFP-374 fix roles and interests display

package-lock.json, package.json, src/components/Layout/Header/index.tsx, src/services/api/user/models.ts, src/style/themes/kids-first/main.css, src/views/Community/Member/index.tsx, src/views/Community/components/MemberCard/index.tsx, src/views/Community/index.tsx, src/views/Community/utils.ts, src/views/Profile/Settings/cards/Identification/index.tsx, src/views/Profile/View/index.module.css, src/views/Profile/View/index.tsx
- closes[ #TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-906)
- closes[ #TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-907)
1. La location ne s’affiche pas dans la « View Page Profile » 
2. Le bouton Community n’est pas de la bonne couleur dans la « View Page Profile »
3. Tous les utilisateurs ont la même image. C’est louche.
4. Ne pas afficher le rôle « other »
=> fix(community): SKFP-334 fix styles

src/components/Cells/index.tsx
=> fix: SKFP-1222 remove duplicates for some ontology terms

src/style/themes/kids-first/main.css
- closes https://d3b.atlassian.net/browse/SKFP-1219
[
[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1219)
=> fix: SKFP-1219 apply correct colors for empty icon

package-lock.json, package.json, src/views/VariantEntity/index.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-1094)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1094)
=> feat(variant): SKFP-1094 add basic-bordered theme

src/services/api/arranger/models.ts, src/views/Community/index.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-1243)
Stats are using old ES index
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1243)
=> fix(community): SKFP-1243 remove stats on community page

package-lock.json, package.json, src/views/VariantEntity/utils/summary.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-1094)
...
=> fix(SKFP-1090): fix basic-bordered theme for description

src/locales/en.ts
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-1235)
Files => files
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1235)
=> fix(authorizedstudies): SKFP-1179 fix typo

package-lock.json, package.json
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-1235)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1235)
=> chore(ferlab): SKFP-1235 update version

src/graphql/participants/queries.ts, src/views/ParticipantEntity/BiospecimenTable/index.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-809)
Dans l’export TSV des biospecimens, il manque les colonnes
Histological Diagnosis (Source Text) Fixé par [SKFP-1207](https://d3b.atlassian.net/browse/SKFP-1207) 
Tumor Location (Source Text)
Colonne ajoutée par [SKFP-1207](https://d3b.atlassian.net/browse/SKFP-1207) 
Manque les données
Tumor Descriptor (Source Text)
Colonne ajoutée par [SKFP-1207](https://d3b.atlassian.net/browse/SKFP-1207) 
Manque les données
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-809)
[SKFP-1207]: https://d3b.atlassian.net/browse/SKFP-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1207]: https://d3b.atlassian.net/browse/SKFP-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
=> feat(participant): SKFP-809 addd tumor in tsv export

cypress/e2e/Telechargement/TableauxPageParticipant.cy.ts, cypress/e2e/Widgets/AuthorizedStudies.cy.ts
- closes #SKFP-1251
- relate to #SKFP-778
- relate to #SKFP-1179
[SKFP-1251](https://d3b.atlassian.net/browse/SKFP-1251)
[SKFP-778](https://d3b.atlassian.net/browse/SKFP-778)
[SKFP-1179](https://d3b.atlassian.net/browse/SKFP-1179)
[SKFP-1251]: https://d3b.atlassian.net/browse/SKFP-1251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-778]: https://d3b.atlassian.net/browse/SKFP-778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1179]: https://d3b.atlassian.net/browse/SKFP-1179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1251 Adjust Cypress tests related to SKFP-778 and SKFP-1179

cypress/e2e/Telechargement/TableauParticipants.cy.ts
- closes #SKFP-1253
- relate to #SKFP-809
[SKFP-1253](https://d3b.atlassian.net/browse/SKFP-1253)
[SKFP-809](https://d3b.atlassian.net/browse/SKFP-809)
[SKFP-1253]: https://d3b.atlassian.net/browse/SKFP-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-809]: https://d3b.atlassian.net/browse/SKFP-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1253 Adjust Cypress tests related to SKFP-809

cypress/e2e/Facettes/PageDataExploration.cy.ts
- closes #SKFP-1260
- relate to #SKFP-1259
[SKFP-1260](https://d3b.atlassian.net/browse/SKFP-1260)
[SKFP-1259](https://d3b.atlassian.net/browse/SKFP-1259)
[SKFP-1260]: https://d3b.atlassian.net/browse/SKFP-1260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1259]: https://d3b.atlassian.net/browse/SKFP-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1260 Adjust Cypress tests related to SKFP-1259

src/graphql/quickFilter/queries.ts, src/utils/translation.ts, src/views/DataExploration/index.tsx
- closes [#TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-1258)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1258)
=> feat(quickfilter): add correct field for diagnosis mondo

cypress/e2e/CavaticaButton/PageDataExploration.cy.ts, cypress/e2e/CavaticaButton/PageFile.cy.ts
- closes #SKFP-1261
[SKFP-1261](https://d3b.atlassian.net/browse/SKFP-1261)
[SKFP-1261]: https://d3b.atlassian.net/browse/SKFP-1261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1261 Add Analyze in Cavatica button Cypress tests

cypress/e2e/Consultation/Login.cy.ts, cypress/e2e/Navigation/Logout.cy.ts
- closes #SKFP-1265
- relate to #SKFP-1208
[SKFP-1265](https://d3b.atlassian.net/browse/SKFP-1265)
[SKFP-1208](https://d3b.atlassian.net/browse/SKFP-1208)
[SKFP-1265]: https://d3b.atlassian.net/browse/SKFP-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-1208]: https://d3b.atlassian.net/browse/SKFP-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1265 Adjust Cypress tests related to SKFP-1208

cypress/e2e/Requetes/ActionsSur0Requete.cy.ts
- closes #SKFP-1267
[SKFP-1267](https://d3b.atlassian.net/browse/SKFP-1267)
[SKFP-1267]: https://d3b.atlassian.net/browse/SKFP-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SKFP-1267 Adjust Cypress tests related to timing issue

src/locales/en.ts, src/views/LandingPage/TopBanner/LoginForm/index.tsx
- closes [#SKFP-1289](https://d3b.atlassian.net/browse/SKFP-1289)
=> fix: SKFP-1289 adjust landing button order and login button text

cypress/e2e/Requetes/ActionsSur0Requete.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts, cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts, cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts
=> feat: SKFP-1290 Adjust Cypress tests after ETLs run

cypress/e2e/CavaticaButton/PageDataExploration.cy.ts, cypress/e2e/Consultation/PageFile.cy.ts, cypress/e2e/Consultation/PageParticipant.cy.ts, cypress/e2e/Consultation/PageVariant.cy.ts, cypress/e2e/Consultation/TableauBiospecimens.cy.ts, cypress/e2e/Consultation/TableauFiles.cy.ts, cypress/e2e/Consultation/TableauParticipants.cy.ts, cypress/e2e/Consultation/TableauVariants.cy.ts, cypress/e2e/Facettes/PageVariants.cy.ts, cypress/e2e/Navigation/Pages.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts, cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts, cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts, cypress/e2e/Widgets/BiospecimenRequests.cy.ts, cypress/e2e/Widgets/SavedFilters.cy.ts, cypress/e2e/Widgets/SavedSets.cy.ts, cypress/support/commands.ts
=> feat: SKFP-1287 Improved locators in Cypress tests

src/views/Studies/index.tsx
- closes [#SKFP-1296](https://d3b.atlassian.net/browse/SKFP-1296)
=> feat: SKFP-1296 add imaging column in studies

src/utils/dataFiles.ts, src/views/FileEntity/utils/getImagingItems.tsx
- closes [#SKFP-1286](https://d3b.atlassian.net/browse/SKFP-1286)
=> fix: SKFP-1246 adjust label in file entity and configure cavatica for unauthorized files

src/graphql/files/models.ts, src/store/passport/thunks.test.ts, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/FileEntity/Imaging/index.tsx, src/views/FileEntity/utils/getImagingItems.tsx
- closes [#SKFP-1322](https://d3b.atlassian.net/browse/SKFP-1322)
=> fix: SKFP-1322 restore imaging technique and sequence type

src/locales/en.ts, src/views/FileEntity/Title/index.module.css, src/views/FileEntity/Title/index.tsx
- closes [#SKFP-1323](https://d3b.atlassian.net/browse/SKFP-1323)
=> fix: SKFP-1323 replicate cavatica warning in file entity

src/services/api/cavatica/index.ts, src/utils/dataFiles.ts, src/views/FileEntity/Title/index.tsx
- closes [#SKFP-1323](https://d3b.atlassian.net/browse/SKFP-1323)
=> fix: SKFP-1323 prevent object mutation

cypress/e2e/Consultation/PageFile.cy.ts
=> feat: SKFP-1355 Adjust Cypress tests related to SKFP-1334

src/locales/en.ts, src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx, src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx, src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx, src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
[SKFP-1231](https://d3b.atlassian.net/browse/SKFP-1231)
- Check authorized characters in saved set name.
No check before
[SKFP-1231]: https://d3b.atlassian.net/browse/SKFP-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(set): SKFP-1231 add rule for special characters

package-lock.json, package.json, src/components/uiKit/FilterList/CustomFilterContainer.tsx, src/components/uiKit/FilterList/index.tsx, src/components/uiKit/FilterList/types.ts, src/views/DataExploration/index.module.css, src/views/DataExploration/index.tsx
[SKFP-1358](https://d3b.atlassian.net/browse/SKFP-1358)
- Add icon on facet with count
- Add icon in both level of quick filter
**Facet**
**Quick filter**
[SKFP-1358]: https://d3b.atlassian.net/browse/SKFP-1358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat (facet and QF): SKFP-1358 add category icon

src/views/LandingPage/TopBanner/LoginForm/index.tsx, src/views/Login/index.tsx
[SKFP-1353](https://d3b.atlassian.net/browse/SKFP-1353)
- add redirect to website
image only
https://github.com/user-attachments/assets/9832655a-f71e-4e99-88b9-89d98b912a35
[SKFP-1353]: https://d3b.atlassian.net/browse/SKFP-1353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(login): SKFP-1353 add redirect to website

cypress/e2e/Consultation/TableauStudies.cy.ts, cypress/e2e/Recherche/PageStudies.cy.ts
- Closes SKFP-1370
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1370)
1. 
2.
=> feat: SKFP-1370 Adjust Cypress tests to fix some issues

src/locales/en.ts, src/store/report/thunks.tsx, src/views/Variants/components/PageContent/VariantsTable/index.module.css, src/views/Variants/components/PageContent/VariantsTable/index.tsx, src/views/Variants/components/PageContent/VariantsTable/utils.tsx
[SKFP-1223](https://d3b.atlassian.net/browse/SKFP-1223)
Add export TSV on variants exploration table.
- export all columns
- add warning modal if more than 10 000 variants selected
NA
[SKFP-1223]: https://d3b.atlassian.net/browse/SKFP-1223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(variants): SKFP-1223 Export TSV

src/views/Variants/components/PageContent/VariantsTable/index.tsx
[SKFP-1223](https://d3b.atlassian.net/browse/SKFP-1223)
Fix defect
- Close button must be blue
[SKFP-1223]: https://d3b.atlassian.net/browse/SKFP-1223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(variants): SKFP-1223 modal button color

cypress/e2e/Consultation/TableauFiles.cy.ts, cypress/e2e/Requetes/ActionsSur0Requete.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts, cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts, cypress/e2e/Requetes/ValidationParticipants.cy.ts
- Closes SKFP-1378
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1378)
1. 
2.
=> feat: SKFP-1378 Adjust Cypress tests related to last ETL run

src/views/DataExploration/index.tsx
- Closes SKFP-1383
Modifier l'icône sur tous les niveaux
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1383)
=> fix(quickfilter): SKFP-1383 fix first level icon

src/components/Layout/Header/index.tsx, src/components/uiKit/GradientAccent/index.module.css
- Closes SKFP-1285
On variant and exploration, there is a double scrollbar
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1285)
=> fix(gradiant): SKFP-1285 remove double scrollbar

src/components/PublicLayout/Header/index.tsx, src/components/PublicLayout/LoginModal/index.module.css, src/components/PublicLayout/LoginModal/index.tsx, src/locales/en.ts, src/views/PublicStudies/PageContent/index.tsx, src/views/PublicStudies/utils.tsx
[SKFP-1368](https://d3b.atlassian.net/browse/SKFP-1368)
Add login modal in public studies page.
- Open modal from all header buttons and table links
NA
https://github.com/user-attachments/assets/42074938-11cb-4efd-8b47-13d632b0167c
[SKFP-1368]: https://d3b.atlassian.net/browse/SKFP-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(studies): SKFP-1368 add login modal

src/components/PublicLayout/Header/index.tsx, src/components/PublicLayout/LoginModal/index.tsx, src/services/analytics.ts, src/views/LandingPage/StudiesSection/Studies/index.tsx
[SKFP-1389](https://d3b.atlassian.net/browse/SKFP-1389)
Add Google Analytics tracking on Public studies page and landing page.
- in Landing page on view all studies button
- in Public studies page on all header buttons and on login modal buttons
[SKFP-1389]: https://d3b.atlassian.net/browse/SKFP-1389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(studies): SKFP-1389 add GA tracking

src/components/PublicLayout/Header/index.tsx
[SKFP-1392](https://d3b.atlassian.net/browse/SKFP-1392)
Add link to login on header logo
- Add link to login page
NA
https://github.com/user-attachments/assets/5c08cfdb-e3f1-40a8-9deb-bcd65dabeaa9
=> feat(studies): SKFP-1392 add login link in public header

src/components/PublicLayout/Header/index.tsx, src/components/PublicLayout/LoginModal/index.tsx, src/hooks/useQueryParams.tsx, src/views/PublicStudies/PageContent/index.tsx, src/views/PublicStudies/utils.tsx
- Closes SKFP-1397
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1397)
1. 
2.
=> feat(studies): SKFP-1397 redirect after login in public page

cypress/e2e/Consultation/TableauFiles.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts, cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts, cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts
- Closes SKFP-1398
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1398)
1. 
2.
=> feat: SKFP-1398 Adjust Cypress tests related to SKFP-1396

package-lock.json, package.json
- Closes SKFP-1057
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1057)
=> fix(cavatica): SKFP-1057 remove native tooltips for label and input

package-lock.json, package.json, src/components/uiKit/FilterList/CustomFilterContainer.tsx, src/components/uiKit/FilterList/index.tsx, src/components/uiKit/FilterList/types.ts, src/graphql/quickFilter/queries.ts, src/views/DataExploration/index.tsx, src/views/DataExploration/utils/quickFilter.tsx, src/views/Variants/index.tsx
[SKFP-1407](https://d3b.atlassian.net/browse/SKFP-1407)
Define default range operator for facet and quick filter.
- Define default operator
Less than default value for all range facet.
Page Variants
Page Data Exploration
Quick filter
[SKFP-1407]: https://d3b.atlassian.net/browse/SKFP-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(facet): SKFP-1407 add default operator facet and QF

cypress.config.ts, cypress/e2e/Consultation/PageVariant.cy.ts, cypress/e2e/Consultation/TableauVariants.cy.ts, cypress/e2e/Facettes/PageVariants.cy.ts
- Closes SKFP-1423
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1423)
1. 
2.
=> feat: SKFP-1423 Adjust Cypress tests related to last ETL run

src/graphql/studies/actions.ts, src/graphql/studies/queries.ts, src/views/VariantEntity/index.tsx, src/views/VariantEntity/utils/frequency.tsx
[SKFP-257](https://d3b.atlassian.net/browse/SKFP-257)
Add study name hover
- In frequency section, add hover on study code of study name
[SKFP-257]: https://d3b.atlassian.net/browse/SKFP-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(variant): SKFP-257 add study name hover in frequency section

cypress/e2e/Consultation/PageVariant.cy.ts, cypress/e2e/Consultation/TableauVariants.cy.ts, cypress/e2e/Facettes/PageVariants.cy.ts
- Closes SKFP-1424
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1424)
1. 
2.
=> feat: SKFP-1424 Adjust Cypress tests related to last ETL run

cypress/e2e/Consultation/Landing.cy.ts, cypress/e2e/Consultation/PageFile.cy.ts, cypress/e2e/Consultation/TableauBiospecimens.cy.ts, cypress/e2e/Consultation/TableauFiles.cy.ts, cypress/e2e/Consultation/TableauParticipants.cy.ts, cypress/e2e/Consultation/TableauStudies.cy.ts, cypress/e2e/Facettes/PageDataExploration.cy.ts, cypress/e2e/Facettes/PageStudies.cy.ts, cypress/e2e/Navigation/Pages.cy.ts, cypress/e2e/Requetes/ActionsSur0Requete.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts, cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts, cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts, cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts, cypress/e2e/Telechargement/SampleDataTableauBiospecimens.cy.ts, cypress/e2e/Telechargement/TableauFiles.cy.ts, cypress/fixtures/ExportTableauFiles.json, cypress/support/commands.ts
- Closes SKFP-1435
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1435)
1. 
2.
=> feat: SKFP-1435 Adjust Cypress tests related to last ETL run

cypress/e2e/Colonnes/TableauVariantsSomatic.cy.ts, cypress/e2e/Consultation/TableauVariantsSomatic.cy.ts, cypress/e2e/Facettes/PageVariantsSomatic.cy.ts, cypress/e2e/Filtres/PageVariantsSomatic.cy.ts, cypress/e2e/Navigation/Pages.cy.ts, cypress/e2e/SaveSetButton/PageVariantsSomatic.cy.ts, cypress/e2e/UploadList/PageVariantsSomatic.cy.ts, cypress/support/commands.ts, cypress/support/index.d.ts
- Closes SKFP-1456
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1456)
1. 
2.
=> feat: SKFP-1456 Add SKFP-1429 Cypress tests

package-lock.json, package.json, src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx
- Closes SKFP-1392
La légende de Demographics est tronquée
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1392)
=> fix(demographic): SKFP-1392 adjust legend size

cypress/e2e/Navigation/Pages.cy.ts, cypress/e2e/Widgets/SavedFilters.cy.ts, cypress/e2e/Widgets/SavedSets.cy.ts, src/locales/en.ts, src/views/Variants/components/PageContent/index.tsx, src/views/VariantsSomatic/components/HeaderDropdown/index.tsx, src/views/VariantsSomatic/components/PageContent/index.tsx
[SKFP-1448](https://d3b.atlassian.net/browse/SKFP-1448)
Add page selection beside title
- Add dropdown to switch between germline and somatic variant exploration page
https://github.com/user-attachments/assets/b9f41f96-8f35-4989-9e8b-46b432a6c091
[SKFP-1448]: https://d3b.atlassian.net/browse/SKFP-1448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(somatic): SKFP-1448 add page dropdown header

src/locales/en.ts, src/views/VariantEntity/index.module.css, src/views/VariantEntity/index.tsx, src/views/VariantSomaticEntity/index.module.css, src/views/VariantSomaticEntity/index.tsx, src/views/Variants/components/PageContent/index.tsx
[SKFP-1441](https://d3b.atlassian.net/browse/SKFP-1441)
Add link in variant entities
- Add link to variant exploration with variant id = locus 
[SKFP-1441]: https://d3b.atlassian.net/browse/SKFP-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(somatic): SKFP-1441 Add link to germline or somatic in entity

cypress/e2e/SaveSetButton/PageVariantsSomatic.cy.ts, src/common/queryBuilder.ts, src/locales/en.ts, src/services/api/savedSet/models.ts, src/store/savedSet/index.ts, src/views/Dashboard/components/DashboardCards/SavedFilters/ListItem/index.module.css, src/views/Dashboard/components/DashboardCards/SavedFilters/ListItem/index.tsx, src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.module.css, src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx, src/views/DataExploration/components/SetsManagementDropdown/index.tsx, src/views/VariantsSomatic/components/PageContent/VariantsTable/index.tsx
[SKFP-1459](https://d3b.atlassian.net/browse/SKFP-1459)
Manage set and filter for somatic variant.
- Implement saved set for somatic
- Add filter and set in dashboard widgets
NA
[SKFP-1459]: https://d3b.atlassian.net/browse/SKFP-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(somatic): SKFP-1459 add filter and saved set to somatic explo

cypress/e2e/Consultation/PageVariant_1.cy.ts, cypress/e2e/Consultation/PageVariant_2.cy.ts, cypress/support/commands.ts
- Closes SKFP-1470
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1470)
1. 
2.
=> feat: SKFP-1470 Adjust Cypress tests related to recent changes

cypress/e2e/Colonnes/TableauVariantsSomatic.cy.ts, cypress/e2e/Consultation/TableauVariantsSomatic_1.cy.ts, package-lock.json, package.json, src/locales/en.ts, src/views/VariantSomaticEntity/index.tsx, src/views/VariantsSomatic/components/PageContent/VariantsTable/index.tsx
[SKFP-1469](https://d3b.atlassian.net/browse/SKFP-1469)
Various fixes
- Add tooltip on table column header
- Remove column
- Manage entity long title
NA
[SKFP-1469]: https://d3b.atlassian.net/browse/SKFP-1469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(somatic): SKFP-1469 various fixes

package-lock.json, package.json, src/locales/en.ts, src/style/themes/kids-first/main.css, src/utils/translation.ts, src/views/DataExploration/index.tsx
[SKFP-1485](https://d3b.atlassian.net/browse/SKFP-1485)
Sentry error
Add validation on input search
--error--
[SKFP-1485]: https://d3b.atlassian.net/browse/SKFP-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(quickfilter): SKFP-1485 add validation on input

package-lock.json, src/components/uiKit/search/SetSearch/index.tsx, src/locales/en.ts, src/services/analytics.ts, src/services/api/arranger/index.ts, src/services/api/savedSet/models.ts, src/store/index.tsx, src/store/savedSet/thunks.ts, src/store/savedSet/types.ts, src/store/types.ts, src/store/venn/index.ts, src/store/venn/selector.ts, src/store/venn/slice.ts, src/store/venn/thunks.ts, src/store/venn/types.ts, src/style/themes/kids-first/main.css, src/utils/translation.ts, src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx, src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx, src/views/DataExploration/components/PageContent/index.tsx, src/views/DataExploration/index.tsx
- Closes SJIP-1399
- [JIRA](https://d3b.atlassian.net/browse/SJIP-1399)
=> feat(venn): SKFP-1399 add venn modal and temporary set

src/locales/en.ts, src/views/DataExploration/index.tsx
[SKFP-1488](https://d3b.atlassian.net/browse/SKFP-1488)
Add forbidden characters for QF
Add forbidden characters for QF
/ 
[SKFP-1488]: https://d3b.atlassian.net/browse/SKFP-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(quickfilter): SKFP-1488 add forbidden characters

src/index.js
[SKFP-1415](https://d3b.atlassian.net/browse/SKFP-1415)
Configure error send to sentry
Ignore some errors.
[SKFP-1415]: https://d3b.atlassian.net/browse/SKFP-1415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(sentry): SKFP-1415 add beforeSend to catch non error

src/views/VariantEntity/index.tsx
[SKFP-1475](https://d3b.atlassian.net/browse/SKFP-1475)
Manage long title in Germline entity
- Add tooltip and ellipsis on title
/ 
[SKFP-1475]: https://d3b.atlassian.net/browse/SKFP-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(germline): SKFP-1475 manage long title

src/services/analytics.ts, src/views/LandingPage/CollaboratorSection/index.tsx, src/views/LandingPage/Footer/Socials/index.tsx, src/views/LandingPage/Footer/index.tsx, src/views/LandingPage/StudiesSection/Studies/index.tsx, src/views/LandingPage/TopBanner/LoginForm/index.tsx
- Closes SKFP-1491
Location	Button	GA event name
Landing page — upper section	Login	Landing - Login
Landing page — upper section	Sign Up	Landing - Sign Up
Landing page — Accelerate research	Get Started	Landing - Get Started
Landing page — Advancing science through collaboration	Explore Variant data	Landing - Variant 
Landing page— Advancing science through collaboration	Get Started (Cavatica)	Landing - Get Started (Cavatica)
Landing page— Advancing science through collaboration	Get Started (PedcBioportal)	Landing - Get Started (pedcbio)
Landing page — Find inspiration	View Publications	Landing - Publications
Landing page — Get Answers	Help Center	Landing - Help Center
Landing page — Footer	EMAIL KIDS FIRST	Landing - Email KF
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1491)
=> feat(landing): SKFP-1491 add new analytics

cypress/e2e/Consultation/TableauStudies_1.cy.ts, package-lock.json, package.json, src/locales/en.ts, src/views/PublicStudies/PageContent/index.tsx, src/views/Studies/components/PageContent/index.module.css, src/views/Studies/components/PageContent/index.tsx, src/views/Studies/index.tsx
- Closes SKFP-1492
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1492)
=> feat(studies): SKFP-1492 Add summary

package-lock.json, package.json
- Closes SKFP-1541
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1541)
1. 
2.
=> feat: SKFP-1541 Add TestQualityCli to project

package-lock.json, package.json, src/views/DataExploration/components/PageContent/tabs/Summary/AgeAtDiagnosisGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DataCategoryGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DataTypeGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentDiagnosisGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentPhenotypesGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/SampleType/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.tsx
[SKFP-829](https://d3b.atlassian.net/browse/SKFP-829)
Frequency values are not displayed in Age At Diagnosis download data.
- fix frequency value in Age At Diagnosis
- format frequency
- rename first column header
- remove empty column
[SKFP-829]: https://d3b.atlassian.net/browse/SKFP-829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(summary): SKFP-829 improve download data

package-lock.json, package.json
- Closes SKFP-1552
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1552)
1. 
2.
=> feat: SKFP-1552 Update testqualitycli

package-lock.json, package.json, src/locales/en.ts, src/services/api/user/index.ts, src/store/community/slice.ts, src/store/community/thunks.ts, src/store/community/types.ts, src/views/Community/index.tsx
[SKFP-1537](https://ferlab-crsj.atlassian.net/browse/SKFP-1537)
Add suffix after results in community page
- Add suffix props to pro table dictionnary
[SKFP-1537]: https://d3b.atlassian.net/browse/SKFP-1537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(community): SKFP-1537 add total user count

src/graphql/studies/models.ts, src/graphql/studies/queries.ts, src/locales/en.ts, src/store/passport/thunks.test.ts, src/views/Studies/components/PageContent/index.tsx, src/views/Studies/index.tsx
[SKFP-1547](https://d3b.atlassian.net/browse/SKFP-1547)
Add files column
- Add files column with file count
- Redirect to data explo files tab on count
- Add footer summary with file total count
No files column
https://github.com/user-attachments/assets/44cab827-a5d1-4876-aa26-b97bc638acb5
[SKFP-1547]: https://d3b.atlassian.net/browse/SKFP-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(studies): SKFP-1547 add files column

cypress/e2e/Colonnes/TableauStudies.cy.ts, cypress/e2e/Consultation/TableauStudies_1.cy.ts, cypress/e2e/Consultation/TableauStudies_2.cy.ts, cypress/e2e/Consultation/TableauStudies_3.cy.ts
- Closes SKFP-1547
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1547)
1. 
2.
=> feat: SKFP-1547 Adjust Cypress tests

src/locales/en.ts, src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentDiagnosisGraphCard/index.tsx, src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentPhenotypesGraphCard/index.tsx
[SKFP-1550](https://d3b.atlassian.net/browse/SKFP-1550)
Enrich Most Frequent Phenotype and Diagnosis graph tooltip.
- Add exact count and with descendant count.
[SKFP-1550]: https://d3b.atlassian.net/browse/SKFP-1550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(summary): SKFP-1550 improve most frequent graphs tooltip
