- src/App.js
- src/components/Header.js
- src/components/Join.js
- src/components/Login.js
- src/components/LoginPage.js
- src/components/UserProfile/index.js
- src/stateProviders/index.js
- src/stateProviders/provideToast.js
- src/theme/defaultTheme.js
- src/uikit/Toast.js
- Root route changed to login page, this displays same OAuth provider login buttons as Join wiz but different text to guide UX.
- Pulled in GDC toast Notifications, renamed to Toast because there was always confusion with these and BannerNotifications in GDC.
- Toast with 'Fill out Profile or Skip and Browse Files' on complete of join wiz.
> 74 - refine login flow

- src/index.js
going to a shared url doesn't work if you've already been to the app on the same url. i suspect this is a service worker issue. I think it's worth merging this for the demo to test since it won't break anything and might potentially fix this.
then we can fiddle with the manifest.json later if we want to keep the service worker at all.
> 🔥 remove service worker to test share url cache fix

- src/components/FamilyManifestModal/FamilyManifestModal.js
It was injecting `null` into the filters
but if filters is `null` it will return all files anyways, so it can just return null in that case
> 🐛 if no filters selected, don't create filters

- src/components/Login.js
- src/stateProviders/provideLoggedInUser.js
this introduces a check to see if a user's JWT is expired before setting it in state (on load). it'll get us around the persona api errors on page load, however a subsequent PR should address persona authentication issues in the case of a token expiring within the context of a single session.
> 🐛 don't set the JWT if it's invalid

- src/components/FileRepo.js
> 🐛 shouldn't assume user is loaded from the get-go

- src/components/Stats/Stats.js
- src/components/Stats/index.js
the missing bucket was throwing counts off by one. I've added a PR to arranger to give the gql client the ability to specify whether or not to include the missing bucket, this uses that to fix the issue.
depends on https://github.com/overture-stack/arranger/pull/346
> 🐛 the missing bucket was throwing counts off by 1

- src/services/ajax.js
- src/services/api.js
This makes sure unless indicated otherwise, `'Content-Type': 'application/json'` is set in the header
> 🐛 adds and implements default ajax headers

- src/common/constants.js
- src/stateProviders/provideLoggedInUser.js
accounts for some user roles not having all default fields. 
Use Case: 
if you created an account with the Community Role and filled out all available fields on the screen the CompleteOMeter would not show 100% because it accounted for all fields for all roles
> 🐛 accurately udpate CompleteOMeter per user role

- src/components/Login.js
- src/components/UserProfile/index.js
- src/services/profiles.js
persona `users` resolver is now only available to admins.
we should use the `self` resolver to grab the logged in user's profile from their jwt
> ✨ use the new safe self persona resolver

- src/components/UserProfile/InterestsAutocomplete.js
a few fixes:
- dropdown menu style was initialized wrong / therefore not applied
- tags should all be lowercase
- only show the tag as a new item if it's not already a suggestion
> 🐛 tags should be lower, other ui fixes

- src/components/UserProfile/Gen3Connection.js
@hlminh2000 - is there a chance we have different prettier / eslint settings? for me atom complains if there are unused vars, in addition to the CRA client-server console warnings
> 🔥 remove unused vars

- src/services/gen3.js
so its more apparent and fixes the gen3 download issue
> 🐛 moves gen3 oauth scope to the front-end

- src/components/UserProfile/UserIntegrations/index.js
adds `trackUserInteraction` calls to Gen3 connection calls in the profile settings area.
@hlminh2000 wasn't able to test successful connections on my local as it threw a incorrect redirect url error
> :chart_with_upwards_trend: gen3 tracking update

- src/components/FamilyManifestModal/FamilyManifestModal.js
this tracks the sqon and the `file_name` column for file manifest downloads. This allows us to re-query the manifest for filenames and then cross-reference those file names agaist S3 logs to see how many files were actually downloaded
> 📈track sqon and columns for file manifest downloads

- public/index.html
- src/components/FileRepo/FileRepo.js
- src/services/analyticsTracking.js
simple events to track when people bail out of completing query actions
> 📈 tracking events for  query abandonment

- src/components/loginButtons/GoogleLogin.js
wrong prop name was being called :P
also just grab the callbacks in the outer scope to be completely obvious
> 🐛 fixes the login code

- Jenkinsfile
Adds Jenkinsfile to use the cloudfront module.
This will allow us to deploy portal using the standard cloudfront deployment pipeline, but will not interfere with the current netlify deployment.
> 👷  Adds Jenkinsfile

- src/components/UserDashboard/QueryBlock.js
- src/services/analyticsTracking.js
Tracks when queries are deleted and when the user clicks on a saved query title
> 📈 adds tracking events to Saved Queries widget

- src/chartkit/components/Donut.js
- Use full available height
- Shrink less but lose labels for narrow width (margin changes)
- 45 degree starting angle
- shorter dashes
> Donut Dashboard Chart Styles

- src/components/FileRepo/ui.js
After discussing with @rosibaj, also made the following changes:
- made the number "chip" the same height for text lines > 1
- number value aligned to the right within the "chip:
> #688 Align facet text

- src/components/FileRepo/AggregationSidebar/AggregationSidebar.js
- src/components/FileRepo/AggregationSidebar/CustomAggregationsPanel.js
Eventually we should look into introducing client-side caching at the data-fetching layer, but that's a bigger task
> 🐛 prevents refetch on aggs panel expansion

- src/components/EntityPage/File/fileProperties.js
- src/components/EntityPage/File/index.js
- src/components/EntityPage/File/participantBiospecimenTable.js
- src/uikit/DataTable/BaseDataTable.js
- src/uikit/DataTable/ToolbarButtons/Export.js
Hooked up GA events to the page. Swapped the `<ExternalLink>` components for react-router `<Link>` that have hardcoded file repo urls. These are just temp so that we can launch and track engagement while the other entity pages are being built
> :chart_with_upwards_trend: File Entity Page tracking

- src/components/EntityPage/EntityActionBar.js
- src/components/Header/ui.js
- src/theme/defaultTheme.js
I had to add a new color in the `defaultTheme` for those shadows since they don't match any other shadows at the `colors` level.
They are the same shadows as in `components.card`, though. I'm not sure if I should just use the value I added in `colors` inside `components.card` to avoid creating duplication.
What do you think?
> fixed #1088 -  FileEntityPage header shadows being too dark

- src/uikit/DataTable/ToolbarButtons/styles.js
I used `z-index: 200` since it is used elsewhere.
Modals use `1000` and most deeper layer components are <= 100.
> fixes #1107 - column selection was beneath the footer

- src/components/EntityPage/File/index.js
- src/components/EntityPage/File/participantBiospecimenTable.js
- src/components/EntityPage/File/sequencingProperties.js
- src/components/EntityPage/File/utils.js
…Also, better check for  null value.
`pickData` does not invoke the transform when the field is absent or null (`_.get` returns null).
```
export const pickData = (data, valuePath, transform = x => x) => {
const selectedData = _.get(data, valuePath, null);
return selectedData === null ? '--' : transform(selectedData);
};
```
Would you prefer to invoke the transforms even with null values?
```
export const pickData = (data, valuePath, transform = x => x) => {
const selectedData = _.get(data, valuePath, null);
return transform(selectedData);
};
```
Pro: each field can transform a null value.
Con: more risk of inserting a regression, maybe some minor refactor on some usage of `pickData`.
Another option is to return `--` by default if no `transform` is provided:
```
export const pickData = …
```
> fixes 1094 - sets default value of 'Proband' correctly.

- src/components/EntityPage/EntityActionBar.js
Had to use a different shadow than the one in Zeplin to avoid having a shadow on top, without changin the z-index.
> fixes 1179 - header not clickable

- src/chartkit/components/Pie.js
- src/chartkit/components/Tooltip.js
React cannot find the component properly based on string name, it needs a component reference. `className` needs to be passed down to the dom node so the style applies. Was causing this originally when hovering on the pie charts:
> 🐛 fixes the tooltip rendering error

- src/components/CohortBuilder/ParticipantsTableView/queries.js
Some of the indices under `participant_centric` in Elasticsearch do not have the `family.family_id` field in their mappings, resulting in inconsistent GraphQL API generated by arranger. 
While this is a symptom of a deeper back-end issue, this UI fix ensures the table will always load as the `family_id` at the root level of participant is confirmed to be the reliable field.
@rosibaj FYI :)
> 🐛uses family_id instead of family.family_id

- src/components/CohortBuilder/QueriesResolver.js
I don't think this is necessary, but please correct me if I'm wrong :)
Removing it now so we don't accidentally rely on it
> ♻️ removes the spread props in QueriesResolver

- src/chartkit/components/Pie.js
This breaks when `this.props.data.length === 0`, which happens on empty data
> 🐛 pie chart breaking on no data

- src/App.js
- src/components/CohortBuilder/index.js
Works same as `UserDashboard`
Footer at bottom pushed down by content.
Will be further improved once we have the Cards displaying without a page loader. (like the UserDashboard where Cards load without a page loader)
> changed page layout component

- package-lock.json
- package.json
- src/components/CohortBuilder/QueriesResolver.js
2 things here:
1) implement caching with a global cache store so it persists throughout application lifecycle (a highly simplified solution)
2) QueriesResolver updates were allowed to happen in parallel so there was room for race conditions. Fixed this with a task queue.
> QueriesResolver race condition

- src/components/CohortBuilder/QueriesResolver.js
no ticket for this. just fixes using React.Component instead of the Component from `react-component-component`
> change to React.Component

- src/components/CohortBuilder/Results.js
- src/uikit/LinkWithLoader.js
Adds option to display loader to side of link
Looks better in Results header instead of `6,432 Participants with <Loader>`,
now it is `6,432 Participants with 2,232 Files <Loader>`
> add option to not replace text with loader, display to side instead

- src/components/UserDashboard/SavedQueries/index.js
- src/stateProviders/provideSavedQueries.js
stop gap solution to allow dashboard SavedQueries card to identify saved queries from riff data.
> 🐛 filters out riff entries that are not saved queries

- src/chartkit/components/HorizontalBar.js
- src/chartkit/components/VerticalBar.js
There are cases where `onMouseLeave` is fired and there isn't an event object to style cursor off.
eg. moving from one chart to the next.
Adds check that we have event object
Flips styles to be correct
> account for not having event object and flip styles

- src/components/CohortBuilder/Summary/SurvivalChart.js
Keeps overflow visible so that tooltip is visible if it flows over the graph to the top part of the card
Add resize provider to render (snap into place when window is resized)
> add Resize provider to re-render on resize

- config-overrides.js
- package-lock.json
- package.json
- src/App.js
- src/common/injectGlobals.js
- src/components/ArrangerAdmin.js
Integrating the new arranger admin UI to replace the legacy one.
This is effectively a separate app from the existing platform, so trying to keep it relatively decoupled from the rest of the `kf-portal-ui`, in case future needs arises to have this deployed separately altogether.
- Lazy loading to avoid bloating up the bundle size, also a good example for implementing code split in future.
- Leaving the legacy admin dashboard around for now, will be removed once all finalized
> Integrate with new Arranger admin system

- src/components/CohortBuilder/ParticipantsTableView/ParticipantsTable.js
Make explicit which column can be sorted or not in the Participant Table.
That PR does not affect the File Repo Table.
> fix/1572 - disable sorting on Participant Table arrays fields

- src/components/CohortBuilder/SqonBuilder/index.js
- src/components/Utils/index.js
- src/services/analyticsTracking/trackingEventConstants.js
This tracks all the multi-sqon changes (duplicate, remove, updated) that can be done to Combined Queries in the Cohort Builder. This tracking event overload the label property to track specific sqon and event details and could potentially cause the event not to be tracked for large complex queries
> 📈 Cohort Builder Combined Queries tracking

- src/components/CohortBuilder/Summary/AgeDiagChart.js
In relation to #1548, which was a back-end issue, but found some quirk of the query while debugging that. Basically using hit counts instead of histogram aggregation because participants with multiple diagnosis that fits in the same range would be counted multiple times within that range.
Back-end portion has already been released to QA
> 🐛 Using hits count for age_at_diagnosis chart

- src/components/cavatica/CavaticaCopyButton.js
All files were uploaded, unless specific files were selected in the table (checkboxes)
The number of files should now match the current query.
> fixed the Cavatica button in File Repo uploading every files, ignoring the sqon

- src/services/login.js
- src/store/actionCreators/user.js
- src/store/actionTypes.js
- src/store/reducers/cohortBuilder.js
- src/store/reducers/user.js
- src/store/reducers/virtualStudies.js
Fixes:
- When we disconnect and reconnect, no virtual study should be opened #1779 
Could fix:
- Cannot logout (to be confirmed)
- At the login page, if no account exists, the Web site tries to create a user for you, and then walk you through the signup process. (to be confirmed)
> [RELEASE] Clean the store after fixed the logout issue

- package.json
- src/components/CohortBuilder/SqonBuilder/index.js
- src/components/CohortBuilder/index.js
- src/icons/ParticipantIcon.js
Adds the number of participants in each query of the virtual study.
Dependent on ~~https://github.com/overture-stack/arranger/pull/519~~ https://github.com/kids-first/arranger/pull/3
Dependent on `@kfarranger/components@1.3.0`, not yet published. We must merge the above PR before, bump the version and publish to npm, then adjust it in this PR if needs be, then merge this one.
> feat/1688 - added number of participants to queries

- src/components/CohortBuilder/Summary/SurvivalChart.js
- src/store/reducers/cohortBuilder.js
The `@@INIT` event can't be used because we're using a preloaded state, so we have to reset the value of `areSqonsEmpty`, which the button uses to determine if it's enabled, whenever the state change.
> Fix/1830 Fixed the Cohort Builder "New" button state

- src/chartkit/components/HorizontalBar.js
- src/chartkit/components/VerticalBar.js
- src/components/CohortBuilder/Summary/AgeDiagChart.js
- src/components/CohortBuilder/Summary/DataTypeChart.js
Fixes:
#1875 
#1876 
- alignment of y-axis labels in HorizontalBar charts (Studies, Most Frequent Diagnosis) on Firefox
Remaining issues:
- Small difference between he padding between x-axis labels of both Horizontal and Vertical graphs
> fix/1875 & fix/1876 various charts issues with Firefox

- src/components/EntityPage/File/index.js
Acl of DCF files were not taken into account.
⚠️  Needs to be tested before this fix is accepted.
Also, it had to be based on `fix/1991-file-entity-phenotypes` because the file entity page wasn't working . Will be rebased on dev once `fix/1991-file-entity-phenotypes` is merged.
> fix/1961 - access of DCF files not taken into account properly

- NEWS.md
- src/common/injectGlobals.js
:warning: This is a PR to `master`, so merging it will trigger a deployment in production.
The OrcId login button will only be displayed it we add a parameter named `orcid` in the query string, i.e. : https://portal.kidsfirstdrc.org/dashboard?orcid
This is only done to test the OrcId login in production, and might be reverted in future release of `2.7.x`, and won't be included in the release of `2.8.0`.
> feat/1858 - allow to display OrcId conditionnaly, for testing purpose

- src/components/FileRepo/DownloadButton.js
- src/services/reports/familyClinicalData.js
- src/services/reports/index.js
- Made the "Family Clinical Data" report available from the "Download" button of the Cohort Builder table.
- Cleaned the page a little, it was getting out of hand
- Hidden behind the `clinicalDataReport` feature toggle (same as the Participant Clinical Data report)
- Removed the condition that disables the report : the current condition makes no sense with the format of the family compositions. There could be both false positive and false negatives.
> feat/2031 - made the new family report available in the Cohort Builder

- src/components/FileRepo/DownloadButton.js
- src/services/reports/biospecimenData.js
- src/services/reports/index.js
Added the choice in the "Download" button of the cohort builder to download the Biospecimen Data Report.
The reports are under the feature toggle `REACT_APP_FT_CLINICAL_DATA_REPORT`. If it is false, the old report will be downloaded instead.
> Added UI button for the Biospecimen report in Cohort Builder

- src/common/downloader.js
- src/components/FileRepo/DownloadButton.js
- src/components/Header/index.js
- src/store/actionCreators/errors.js
- src/store/actionTypes.js
- src/store/reducers/errors.js
- src/store/reducers/index.js
This also adds the functionality of displaying an error alert from anywhere in the app, given that the standard header is displayed.
> Display an error when downloading of a report fails

- src/antdTheme.less
- src/components/MemberSearchPage/FilterDrawer.js
- src/components/MemberSearchPage/FilterTable.js
- src/components/MemberSearchPage/MemberSearchBorder.js
- src/components/MemberSearchPage/MemberSearchPage.css
- src/index.css
- src/index.js
- Changed import order in Index.js so that our styles overrides Ant Design (not the other way around) 
- Updates Style for titles (H1-H2-H3) for Ant Design
> :lipstick: Override ant design styles for titles

- src/components/CohortBuilder/Results.css
- src/components/CohortBuilder/Results.js
- src/icons/DemographicIcon.js
> fix: 2285 - Improve design of the result header

- src/components/CohortBuilder/Summary/Cards/AgeDiagChart.js
- src/components/CohortBuilder/Summary/Cards/SurvivalChart.js
- src/components/CohortBuilder/Summary/Summary.css
- src/components/CohortBuilder/Summary/index.js
- src/components/UI/Charts/Sunburst/sunburst.css
summary css is leaking on all the site and override what should be theme based.
Validated with design we should use ant design default card header height. Fix height specificaly where needed.
> 2995 fix card header

- src/pages/variantsSearchPage/VariantTable.module.scss
I know there is an `!important` But the way the ant design work, I can't see how I can do without in that context.
> fix table header right aligment

- src/pages/variantEntity/TabFrequencies.tsx
- src/pages/variantEntity/TabSummary.tsx
- src/pages/variantEntity/clinical.tsx
> fix: #3089 table alignment accros tables

- src/pages/variantEntity/TabSummary.tsx
- src/style/dist/themes/default/_colors.scss
- src/style/dist/themes/default/antd.css
- src/style/themes/default/_colors.scss
- src/style/themes/default/antd/_colors.less
- src/style/themes/default/antd/tag.less
> fix: #3092 variant tag match default theme color

- src/pages/variantsSearchPage/WorkBench.tsx
- src/store/WorkBenchTypes.ts
- src/store/actionCreators/workBench.ts
- src/store/reducers/workbench.ts
- src/store/selectors/workBench.ts
Test Suites: 26 passed, 26 total
Tests:       153 passed, 153 total
Time:        4.645s, estimated 7s
> make sure to add url when cluster is ready

- src/pages/variantsSearchPage/WorkBench.tsx
- src/store/WorkBenchTypes.ts
- src/store/actionCreators/workBench.ts
Modify the code to continue pinging even after the cluster is up because when it shuts down, we want to switch back the button to it's original state "Start cluster".
> feat: #2905 improve spark cluster session management

- src/pages/variantEntity/TabFrequencies.tsx
- src/pages/variantEntity/TableSummaryKfStudies.tsx
- src/pages/variantsSearchPage/VariantTable.tsx
- src/store/graphql/variants/queries.tsx
- src/store/graphql/variants/tabActions.tsx
- src/ui/types.ts
`npm run test `(bypass circle-ci if needed):
```
Time:        5.822s, estimated 8s
```
QA: in variant search page + entity page (frequency tab; frequency in summary board)
> Fix studies freq tab

- src/pages/studies/StudyPageContainer.tsx
- src/pages/studies/studies.tsx
- src/store/graphql/studies/actions.tsx
Make sure that facet names are the same as the ones displayed in the query bar.
Currently, the facet Domain is in lower case in the query i.e. domain = Cancer
> fix: #3134 Match Querybar and filter names

- src/pages/variantEntity/Summary.tsx
> fix(variant summary card): #3166 correct typo

- src/pages/variantEntity/TabSummary.tsx
- src/pages/variantEntity/tables.module.scss
```
Time:        5.008 s, estimated 8 s
```
**note:** eslint tests fails. It seems that it doesn't like sass variable. The team is notified, but I had to bypass the pretest
the error was
```
✖ npm run eslint:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kf-portal-ui@3.0.1 eslint: `eslint $(git diff-index --name-only --diff-filter=d HEAD | xargs) ..omitted...kidsFirst/kf-portal-ui/src/pages/variantEntity/TabSummary.tsx"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kf-portal-ui@3.0.1 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! …
```
> feat(summarytab): #3202 add canonical symbol if needed

- src/pages/variantEntity/TabFrequencies.tsx
- src/pages/variantEntity/tables.module.scss
- src/pages/variantsSearchPage/VariantTable.module.scss
- src/pages/variantsSearchPage/VariantTable.tsx
#3165 
```
Time:        5.19 s
```
**Note:** I had to bypass eslint again since it doesn't like variables in scss. However, I made sure to correct all that I could.
> feat(FreqTab): #3165 add participants tooltip

- src/components/Variants/Test/consequences.test.ts
- src/components/Variants/consequences.ts
- src/pages/variantEntity/TabClinical.tsx
- src/pages/variantEntity/TabFrequencies.tsx
- src/pages/variantEntity/TabSummary.tsx
- src/pages/variantEntity/tables.module.scss
- src/pages/variantsSearchPage/SuggestionOptions.tsx
- src/pages/variantsSearchPage/VariantTable.tsx
fixes following qa
- remove 'c' avatar in the summary tab
- make sure that there is consistency when empty tables (maybe not all cases are covered yet)
- put '--' when empty data (variant entity and variant search page only) 
- remove react duplicate keys in the variant suggestions (bug discovered after qa)
-  use <Link/> vs Button in the variant search results table
**Note:** eslint does not pass (scss file)
```
...omitted.../kidsFirst/kf-portal-ui/src/pages/variantEntity/tables.module.scss
1:1  error  Parsing error: Expression expected
✖ 1 problem (1 error, 0 warnings)
```
**circle-ci bypass:**
```
Time:        7.741 s
```
> fix(variant): remove canonical but fix sorting + empty data fillers

- src/common/injectGlobals.ts
https://create-react-app.dev/docs/adding-custom-environment-variables/
`There is also a built-in environment variable called NODE_ENV. You can read it from process.env.NODE_ENV. When you run npm start, it is always equal to 'development', when you run npm test it is always equal to 'test', and when you run npm run build to make a production bundle, it is always equal to 'production'. You cannot override NODE_ENV manually. This prevents developers from accidentally deploying a slow development build to production.`
> build: #3225 remove unneeded debug

- src/index.js
I needed to ignore eslint import order alerts since if I change the order of the first 5 imports, it breaks the UI
> fix: #3244 fix warning message about babel polyfill deprecated

- package-lock.json
- package.json
- Force use react-router and reace-router-dom 5.2 even for kf-arranger
- Upgrade graphql-client
- Upgrade react-social-icons
- Remove unnecessary dependancy
> Fix/3271: Force use of react-router and react-router-dom 5.2 and upgrade some dependancies

- src/components/Charts/Charts.module.css
- src/components/Charts/index.js
- src/ui/Tooltips/tooltips.scss
Explore Data - Studies
Before
After
Explore Data - Most Frequent Diagnoses (Mondo)
Before
After
Dashboard - Studies Participants
Before
After
Dashboard - Most Frequent Diagnoses
Before
After
> fix: #3255 remove underline in charts tooltip

- src/pages/studies/Sidebar.tsx
- src/pages/studies/SidebarFilters.tsx
- src/pages/studies/StudyPageContainer.tsx
- src/pages/studies/StudyTableContainer.tsx
- src/pages/studies/studies.tsx
> feat: #3353 remove pagination form study page table

- src/store/actionCreators/cavatica.ts
#[BUG] Cavatica status is not fetch
Cavatica connection status was clear each time we refresh
Connect to cavatica then refresh page, should still be connected
...
> fix: #SKFP-8 cavatica connection status is not fetch

- NEWS.md
- package-lock.json
- package.json
- src/App.js
#SKFP-140: Hotfix ORCID login always redirect to login page
- closes #SKFP-140
Login with ORCID redirect to login page instead of Dashboard even if login process worked with success
It should redirect to Dashboard or Orcid error page instead of Login page
Login with ORCID provider
...
Hotfix
> fix: #SKFP-140 hotfix login with orcid always redirect to login page

- src/components/UserDashboard/CavaticaProjects/index.js
SKFP-127: Error when creating a new Cavatica project from Dashboard
- closes [SKFP-127](https://d3b.atlassian.net/browse/SKFP-127)
In dashboard, when creating a new project in cavatica, an error occurs even if the project has been created with success
No more error and user should be on Projects tab after creation success
Before
After
Connect to cavatica and create a project from dashboard page, no error should occur and after creation user is on Projects tab. If user cancel creation, then it returns on Projects tab too (without any error)
> fix: #SKFP-127 fix switch tab in cavatica card in dashboard

- src/pages/variantEntity/Summary.module.scss
- src/pages/variantEntity/Summary.tsx
- src/pages/variantEntity/TabSummary.tsx
- src/pages/variantEntity/tables.module.scss
#BUG  [Variant Entity page: Alt. Allele Ellipsis]
- [SKFP-278](https://d3b.atlassian.net/browse/SKFP-278)
Incorporate an ellipsis for the Alt. allele and add a tooltip similar to the one in the Variant table results (see screenshot) when the text goes over the space limit. The tooltip would show the result for the Alt. Allele.
Ellipsis and tooltip can be added to the AA and the Coding DNA columns in the table below. Similarly, the ellipsis can be applied when the maximum column width is attained.
> fix: #skfp-278 entity page long ellipsis values

- package-lock.json
- src/components/Login/Login.tsx
#SKFP-290 BUG Clicking back on the login services menu
Also update caniuse browsert
- closes #SKFP-290
Clicking on the back arrow from the Keycloak/login services menu (RAS, Google, ORCID) does not bring you back to the portal “Login” page. 
Clicking back on the Keycloak service should bring you back to the login page on the portal. 
Click on button then click on back button, should be redirect to the previous page
...
> fix: #SKFP-290 fix back to login

- src/components/OntologyBrowser/SelectionTree.tsx
- src/components/OntologyBrowser/Test/SelectionTree.test.tsx
- closes [SKFP-347](https://d3b.atlassian.net/browse/SKFP-347)
Display all child node matched by the query
> fix: #SKFP-347 display child nodes from search match

- .env.schema
- src/common/constants.ts
- src/components/Layout/SideImage/index.tsx
- src/helpers/EnvVariables.ts
- src/locales/en.ts
- src/style/themes/kids-first/antd-kids-first-theme.less
- src/style/themes/kids-first/colors.less
- src/views/Dashboard/components/DashboardCards/DataExplorationLinks/LinkBox/index.module.scss
- src/views/Dashboard/components/DashboardCards/DataExplorationLinks/index.module.scss
- closes #381
Goal:  Refactor the Authorized Studies widget seen in INCLUDE. The KF Authorized Studies widget will have two connections (fences). This will allow users with the appropriate Fence credentials to access their controlled data files. 
Upon clicking on the Connect button, it will open the Connections modal seen in the Design. Once a user clicks either connection, it will redirect to their respective Gen3 login process (See KF settings page for more information on redirect).
With a successful login, the toggle with be “Activated”, and the Authorized Studies widget will be populated with the Studies with controlled data that the user has access to
> feat(theme): SKFP-381 add kids-first colorscheme to the dashboard page

- src/services/api/savedFilter/models.ts
- src/views/Dashboard/components/DashboardCards/SavedFilters/index.module.scss
- src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx
- closes [#448](https://d3b.atlassian.net/browse/SKFP-448)
Set up the Saved Filter widget as it is in INCLUDE. One difference, however, is that the users will be able to save filters from the Data Exploration page but also from the Variant Search page. Therefore, we will need to migrate the API to function with the Variant Search query management bar.
https://user-images.githubusercontent.com/65532894/190187902-d8c043f3-ef5f-4e7e-804f-805ab64b8253.mp4
> :lipstick: feat(dashboard): SKFP-377 add variants tab in saved filters

- src/views/Persona/components/RegistrationForm/index.tsx
- src/views/Persona/components/TermsConditions/index.tsx
- closes [#462](https://d3b.atlassian.net/browse/SKFP-462) [#463](https://d3b.atlassian.net/browse/SKFP-463) [#464](https://d3b.atlassian.net/browse/SKFP-464)
Goal: Adjust KIDS FIRST to Kids First for the red boxes. Also, in the green box, instead of writing KF, write Kids First. 
The font size for the buttons at the bottom of the registration page should be 14px
The “Accept” button should be “Submit” instead 
The "I am a" field should be required. If a user selects a checkmark and deselects, the error message saying that this field is required should appear. Similarly, if the user does not check one of the boxes and clicks “Submit”, the error message should appear under the specific field.
> :bandaid: fix(registration): SKFP-462 SKFP-463 SKFP-464 visuals fix

- src/style/themes/kids-first/antd/buttons.less
- closes #3242
There seems to be some CSS overriding at the theme level.
> 🩹fix(button): SKFP-469 fix button padding

- src/locales/en.ts
- src/views/Community/contants.ts
- src/views/Persona/components/RegistrationForm/index.tsx
- src/views/ProfileSettings/cards/Identification/ToggleProfileVisibility/index.module.scss
- src/views/ProfileSettings/cards/Identification/ToggleProfileVisibility/index.tsx
- src/views/ProfileSettings/cards/Identification/index.module.scss
- src/views/ProfileSettings/cards/Identification/index.tsx
- src/views/ProfileSettings/cards/Location/index.tsx
- src/views/ProfileSettings/cards/RoleAndAffiliation/index.tsx
- closes [#406](https://d3b.atlassian.net/browse/SKFP-406)
1. Typos: “First name”, “Last name” et “LinkedIn”
2. Pour la section “Role & Affiliation”
2.1. Le champ “Institution or organization” ne devrait pas être requis
2.2. Typos
Retirer les deux points après “I am a”
Mettre les choix en Title Case (ex. Healthcare Professional”
3. Mettre les champs dans l’ordre et nommé tel que mentionné dans l’analyse Notion
4. Les champs ne devraient pas être requis
5. Typo: “Research Interest”
6. Typo: “Chidhood Cancer”
7. Il manque la section “Delete Account”
Bouton toggle
1. Card header alignment is off
2. Color of switch label is still wrong (should be body text colour)
3. Size of switch label font + tooltip still wrong
nshot (Before and After)
> 🩹fix(profile) SKFP-406 update and fix profile edit page

- src/components/uiKit/DataRelease/index.tsx
- src/views/Dashboard/components/DashboardCards/DataExplorationLinks/LinkBox/index.module.scss
- src/views/Dashboard/components/DashboardCards/DataExplorationLinks/index.module.scss
- src/views/Dashboard/components/DashboardCards/DataExplorationLinks/index.tsx
- closes [#376](https://d3b.atlassian.net/browse/SKFP-376)
> La couleur des icônes devrait être cyan-4 et non cyan-5, à vérifier. S’assurer aussi que la flèche est cyan-4.
> La boîte Data Files devrait rediriger vers la page DataFiles existante.
> Retirer la boîte "Storage" (Décision prise suite à une discussion avec Jean-Philippe)
> 🩹fix(data): fix colors, adjust icons, remove storage

- src/components/Layout/Header/HeaderLink/index.module.scss
- src/components/Layout/Header/index.module.scss
- src/components/Layout/Header/index.tsx
- src/style/themes/kids-first/antd/dropdowns.less
- closes #3242
1.Au Focused State, l’encadré et le texte des items Links et des items Buttons devraient être purple-7.
2. Au Focused State, les items Buttons devraient avoir un encadré. Étant donné qu’aucun projet (Include, CQDG) n’a implémenté ce feature, un ticket d’ordre général sera créé. La correction de ce point par ce ticket-ci est facultatif.
3. En profiter pour modifier la couleur du Default State sur l’item Button User. Le texte devrait être purple-6.
4. En profiter pour ajouter le Hover State sur les items Buttons (Resources et User). Le texte devrait être purple-7.
5. En profiter pour ajouter le Pressed State sur les items Buttons (Resources et User). Le texte devrait être purple-8.
6. En profiter pour modifier le style des dropdown des items Buttons (Resources et User). Se …
> 🩹fix(header): SKFP-448 fix menu headers

- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- closes #[385](https://d3b.atlassian.net/browse/SKFP-385)
Implement the Data Exploration-- Participant tab facets and columns.
> 🧨feat(participant): SKFP-385 add user-defined columns

- src/locales/en.ts
- src/style/themes/kids-first/antd/buttons.less
- src/views/Dashboard/components/DashboardCards/Cavatica/index.tsx
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- src/views/DataExploration/components/UploadIds/FileUploadIds.tsx
- closes #[386](https://d3b.atlassian.net/browse/SKFP-386)
1. Typo Access URL
2. Ajuster la couleur du "Hover State » et du « Pressed State » du bouton « Save file set »
3. Voir les spécifications ajoutées pour la colonne Data Access 
4. Nommer les 2 premières colonnes pour la personnalisation des colonnes
5. Ajouter un label au bouton d’upload
> 🩹 fix(data-explore): SKFP-386 adjust data file tab

- src/components/uiKit/search/SearchLabel/index.module.scss
- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[422](https://d3b.atlassian.net/browse/SKFP-422)
8. Il manque un encadré blanc autour du tableau. 
9. Les lignes grises du tableau ne vont pas jusqu’aux variants
10. La couleur des en-têtes du tableau n’est pas celle du thème Kids First.
11. La couleur du contour des cases du tableau n’est pas celle du thème Kids First. 
12. La couleur du « i » n’est pas celle du thème Kids First.
> 🐛fix(variant): SKFP-422 fix visuals

- src/views/Variants/components/PageContent/VariantsTable/index.tsx
Remove sorter since api is broken (we cannot paginate when results exceeds 10k results)
> :adhesive_bandage: : Remove sorter since api is broken for large values

- src/components/uiKit/PopoverContentLink/index.module.scss
- src/views/Dashboard/components/DashboardCards/CaringForChildrenWithCovid/index.module.scss
- src/views/Dashboard/components/DashboardCards/Notebook/index.module.scss
- closes #[381](https://d3b.atlassian.net/browse/SKFP-381)
Link text colour inside tooltip: the link colour should inherit from parent (is same as text colour)
Border colour around content in FHIR and Zeppelin is wrong. Update to be like the others.
> 🐛fix(dashboard): SKFP-381 fix colors

- src/locales/en.ts
- src/views/DataExploration/components/PageContent/tabs/Summary/AgeAtDiagnosisGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.module.scss
- src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.tsx
- closes #[393](https://d3b.atlassian.net/browse/SKFP-393)
2. Demographics : Mettre les graphs dans le même ordre que la liste de l’analyse
3. Age at Diagnosis: Il manque le titre de l’axe des y
4. Age at Diagnosis: Typo dans le texte du Mouseover
5. Age at Diagnosis: Cliquer sur une barre du graph ne construit pas la bonne requête
6. Studies: Afficher les codes en majuscule, comme c’est fait dans la facette
7. Studies: Centrer le graph verticalement dans la carte
> 🐛fix(dataexplore): SKFP-393 fix summary

- src/style/themes/kids-first/antd/buttons.less
- src/views/FakeStorybook/index.tsx
- closes #3242
Primary Button
Focus state: wrong background colour
Dropdown Button:
Focus state: missing border on focus
Primary Disabled
Wrong border colour
Disabled (all)
Disabled buttons should not have hover or focus states (ie they should not change for any mouse or tab events)
> 💎style(button): SKFP-460 fix buttons focus state

- package-lock.json
- closes #[499](https://d3b.atlassian.net/browse/SKFP-499)
Pour nettoyer les warnings "deprecated" lors des "npm install". Ça semblait seulement être causé par des dépendances inutilisées qui avait des dépendances deprecated.  
J'ai juste delete le package-lock.json et je l'ai regénéré au complet avec "npm install".
Edit: Juste pour mettre un peu plus de contexte, les warnings venaient du package request 2.88.2 qui utilisait des versions deprecated de har-validator et uuid. Par contre ce package ne semble pas utilisé dans le projet puisque sur un "npm install" fresh (après avoir delete le package-lock.json), le nouveau package-lock.json ne contient plus le package "request" et les warnings disparaissent.
> 🛠build(npm): SKFP-499 Update deprecated dependencies

- src/locales/en.ts
- src/views/Dashboard/components/DashboardCards/CaringForChildrenWithCovid/index.tsx
- closes #[537](https://d3b.atlassian.net/browse/SKFP-537)
Ajustement du contenu du popover pour l'icône d'info de KF FHIR API
Before:
After:
> 🐛fix(dashboard): SKFP-537 Update FHIR api widget popover content

- src/locales/en.json
- src/utils/string.ts
- src/views/Variants/components/GeneUploadIds/index.tsx
- closes #[529](https://d3b.atlassian.net/browse/SKFP-529)
- Allow search by alias
- Allow case insensitive search
- change column header "ID ENSEMBL" to "Ensembl ID"
Before:
After:
> 🐛fix(variant): SKFP-529 Upload list by alias and case insensitive search

- package-lock.json
- package.json
- src/graphql/variants/queries.ts
- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- src/views/Variants/components/PageContent/index.tsx
- src/views/Variants/utils/constants.ts
- closes #[522](https://d3b.atlassian.net/browse/SKFP-522)
Notion updated : https://www.notion.so/ferlab/Search-After-guide-de-migration-Front-End-8a0cd7ed40984f219f0174d64404b09b
1. Désactiver le bouton Next quand il n’y a qu’une seule page d’affichée pour éviter d’afficher une page vide en cliquant sur Next.
2. Désactiver le bouton Next lorsqu’il n’y a aucun résultat. Note: Cliquer sur Next ne fait rien ici.
3. Retourner à la première page au changement de requête.
4. Il n’est pas possible d’afficher les résultats au delà de 10K éléments.
https://user-images.githubusercontent.com/65532894/202556063-99313a42-06f6-480a-8447-1ddbb47c4377.mp4
> 🐛fix(pagination): SKFP-522 fix next button disable behaviour

- src/views/DataExploration/components/PageContent/index.tsx
- closes #[544](https://d3b.atlassian.net/browse/SKFP-544)
Pour reproduire:
Avoir deux Saved Filters
Copier la Share url d’un filtre
Basculer sur l’autre filtre 
Coller l’url dans le browser
Le nom du filtre copié s’affiche, mais avec les requêtes du filtre qui était affiché (ce qui modifie le contenu du filtre copié - icône orange).
> 🐛fix(exploration): SKFP-544 use shared filter instead of filterid

- src/services/api/persona/index.ts
- closes #[550](https://d3b.atlassian.net/browse/SKFP-550)
Pour reproduire:
> Créer un nouveau membre
> Renseigner le rôle à la création
> À l’affichage de la Profile Settings Page, aucune information du rôle renseignée n’est présente.
https://user-images.githubusercontent.com/65532894/203601228-73319f18-9b19-487b-8af7-b2eb518eedbb.mp4
https://user-images.githubusercontent.com/65532894/203601231-67eabf0b-d1c5-4cad-912d-eded09bf8dbd.mp4
> 🐛fix(registration): SKFP-550 should register roles at account creation

- src/utils/translation.ts
- closes #[553](https://d3b.atlassian.net/browse/SKFP-553)
Adjust the query pill values to the ones seen in the facets. Currently it is set as “T” which is an acronym for Tolerated. This was fixed in the facets, but the query pills will need to be updated.
Before
After
> 🐛fix(variant): SKFP-553 add translation for sift values

- src/views/Variants/index.tsx
- closes #[518](https://d3b.atlassian.net/browse/SKFP-518)
Page Variants - Pathogenicity: Déplacer ClinVar et VEP en haut de la section Predictions
Before
After
> 🐛fix(variants): SKFP-518 change clinvar and vep order

- src/locales/en.json
- src/utils/translation.ts
- closes #[553](https://d3b.atlassian.net/browse/SKFP-553)
Sync query pill values
With translations since the facet doesn't return all the case
> 🐛fix(variant): SKFP-553 fix query pill values

- src/graphql/participants/queries.ts
- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- closes #[551](https://d3b.atlassian.net/browse/SKFP-551)
: Adjust the key value for dbGaP to the same value in the Study page. It seems like we are pulling the participant ID instead of the dbGaP number which starts with “phs_____”
> 🐛fix(exploration): SKFP-551 fix dbGaP

- src/components/uiKit/FilterList/CollapsePlaceHolderFacet/index.module.scss
- src/locales/en.ts
- src/utils/translation.ts
- closes #[473](https://d3b.atlassian.net/browse/SKFP-473)
Under the Variant and Gene category, currently we only specify “ External Reference” as a facet. However, this becomes problematic when we add a filter and the query pill for both categories is the same “External Reference”. Therefore, we will modify the facets and query pills to correspond to Variant External Reference / Gene External Reference for the Variant category and the Gene category respectively. [DONE]
Under Participant category, update the Phenotype (HPO) & Diagnosis (MONDO) facet to KF UI color theme  [DONE]
g)
> 🐛fix(variants): SKFP-473 minor fixs

- src/views/Dashboard/components/DashboardCards/Cavatica/CreateProjectModal/index.tsx
- closes #[510](https://d3b.atlassian.net/browse/SKFP-510)
Adjust the lorem ipsum placeholder to “e.g. KF-NBL Neuroblastoma Aligned Reads” in the New project modal when analyzing in cavatica. This modal can also be accessed using the Cavatica widget > New project button
> 🐛fix(cavatica): SKFP-510 change placeholder

- src/utils/helper.test.tsx
- src/utils/helper.ts
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes [SKFP-562](https://d3b.atlassian.net/browse/SKFP-560)
Refact of the ```formatQuerySortList()``` function. Made sure it still works everywhere it's used.
Only thing to keep in mind is that when creating a table, the 'key' property will now always be used as the ```field``` value sent to the backend for sorting (i.e. we can use ```key: 'study.study_code'``` for nested data) and the ```dataIndex```property will only be used to render the cell content.
Before, `dataIndex` would become ```sorter.field``` in the ```formatQuerySortList()``` function, which created inconsistent ways of using ```key``` vs ```dataIndex``` and would sometimes result in breaking the sorting because the wrong key was sent to the backend. 
Before:
After:
> 🐛fix(data-exploration): SKFP-560 Study column sorting

- src/graphql/variants/models.ts
- src/graphql/variants/queries.ts
- src/views/Variants/components/ConsequencesCell/index.tsx
- closes #[SKFP-569](https://d3b.atlassian.net/browse/SKFP-569)
Replace the aa_change value by hgvsp like it was done here: [CLIN-1518](https://ferlab-crsj.atlassian.net/browse/CLIN-1518)
Before:
After:
> 🐛fix(variant): SKFP-569 Display hgvsp data in ConsequencesCell

- src/services/api/user/models.ts
- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[573](https://d3b.atlassian.net/browse/SKFP-573)
Add column selection tool to the table of results in the Variant exploration page. All the columns can be set as default for the display. 
BEFORE
AFTER
> ✨feat(variant): SKFP-573 add column sort

- src/locales/en.ts
- src/views/Variants/components/ConsequencesCell/index.tsx
- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- src/views/Variants/utils/constants.ts
- closes #[574](https://d3b.atlassian.net/browse/SKFP-574)
- closes #[576](https://d3b.atlassian.net/browse/SKFP-576)
Goal: Add a column for the gnomAD 3.1.1 allele frequency between the ClinVar and Studies column. Currently, we only have the allele frequency of gnomAD 3.1.1 but once we update the Variant ETL we will have gnomAD  version 3.1.2 and at this point, we will need to update the column values, column header and tooltip. 
Replace underscores with spaces for ClinVar -- Gene consequences values in Variant Exploration page.
...
> ✨ feat(variant): SKFP-574 add gnomAD column, SKFFP-576 replace _ with space

- src/graphql/studies/queries.ts
- src/views/Studies/components/StudySearch/index.tsx
- src/views/Studies/index.tsx
- closes #[586](https://d3b.atlassian.net/browse/SKFP-586)
Change the Study codes seen in the studies page (SD_XXXXXXXX) for the short KF Study codes. The ones currently displayed are the operational Study codes that the CHOP team uses, whereas the short  KF study codes are the user friendly ones that we display on the portal (KF-XXX). The short KF study codes are used in the Data Exploration page under the Study category. 
After
> ✨feat(study): SKFP-586 use study_code instead of study_id

- src/style/themes/kids-first/antd/input.less
- closes [SKFP-584](https://d3b.atlassian.net/browse/SKFP-584)
Fix the InputNumber that was displaying in red even when not in error
Before:
After:
[SKFP-584]: https://d3b.atlassian.net/browse/SKFP-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-584]: https://d3b.atlassian.net/browse/SKFP-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🐛fix(facets): SKFP-584 Number input always red

- src/components/Icons/index.tsx
- src/locales/en.ts
- src/services/api/savedSet/models.ts
- src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx
- src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
- src/views/DataExploration/components/SetsManagementDropdown/AddRemoveSaveSetModal.tsx
- src/views/DataExploration/components/SetsManagementDropdown/index.tsx
- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- src/views/Variants/components/PageContent/index.tsx
- closes #[493](https://d3b.atlassian.net/browse/SKFP-493)
- closes #[494](https://d3b.atlassian.net/browse/SKFP-494)
Add “Variants” as an additional tab to the Saved Sets Widget. This will behave in the same way as it has for the other tabs. A user will open the Saved Set dropdown within the Variant Search page (see image below), and will add variants to a set. 
Add the “Saved variant set” above the table of results in the Variants Exploration.
Before
After
[SKFP-493]: https://d3b.atlassian.net/browse/SKFP-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-494]: https://d3b.atlassian.net/browse/SKFP-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨feat(savedset): SKFP-494 SKFP-493 add variants saved set

- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- closes [SKFP-591](https://d3b.atlassian.net/browse/SKFP-591)
Fix for the participant saved sets that are displaying no results. I am reverting the fix done in [SKFP-559](https://d3b.atlassian.net/browse/SKFP-559) so the multi-sorting will be broken again, but it should be working again once [SKFP-590](https://d3b.atlassian.net/browse/SKFP-590) is addressed. 
Before:
After:
[SKFP-591]: https://d3b.atlassian.net/browse/SKFP-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-559]: https://d3b.atlassian.net/browse/SKFP-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-590]: https://d3b.atlassian.net/browse/SKFP-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
> 🐛fix(dashboard): SKFP-591 No results for participant saved sets

- src/components/uiKit/search/GlobalSearch/Search/index.tsx
- src/utils/helper.ts
- src/views/DataExploration/components/BiospecimenSearch.tsx
- src/views/DataExploration/components/FileSearch.tsx
- src/views/Studies/components/StudySearch/index.tsx
- closes #[598](https://d3b.atlassian.net/browse/SKFP-598)
Backend should work at this point (arranger-project=next_qa). Frontend must be updated:
In src/components/uiKit/search/GlobalSearch/Search/index.tsx remove
value: [ `${search}*`, `${search.toUpperCase()}*`, `${search.toLowerCase()}*`, `${toPascalCase(search)}*`,]
only `${search}*` should suffice.
For participants use
participant_id
field as-is.
For other searches use the field
search_text
For example:
query searchBiospecimenById($sqon: JSON) {    biospecimens {      hits(filters: $sqon) {       edges {          node {            study {search_text}         }        }      }    }  }
{
"sqon":{
"op":"or",
"content":[
{"content":{"field":"study.search_text","index":"participant","value":["opendipg*"]},"op":"in"}]
}
}
> ✨feat(search): SKFP-598 implement new case sensitive api

- src/locales/en.ts
- src/services/api/user/models.ts
- src/views/FileEntity/BiospecimenTable/index.tsx
- src/views/FileEntity/index.tsx
- src/views/FileEntity/utils/getBiospecimensColumns.tsx
- src/views/FileEntity/utils/getLinks.tsx
- closes [SKFP-404](https://d3b.atlassian.net/browse/SKFP-404)
-Changed "Collection Type" column title to "Collection Sample Type" 
-Added functionality to save user config for Biospecimen table columns
-Extracted some logic in their own file to clean up a bit
Before:
After:
[SKFP-404]: https://d3b.atlassian.net/browse/SKFP-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🐛fix(files): SKFP-404 Save table config in FileEntity page

- package-lock.json
- package.json
- src/App.tsx
- src/graphql/participants/actions.ts
- src/graphql/participants/models.ts
- src/graphql/participants/queries.ts
- src/locales/en.ts
- src/utils/dates.ts
- src/utils/routes.ts
- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- src/views/DataExploration/components/SetsManagementDropdown/UserSetForm/index.tsx
- src/views/DataExploration/components/SetsManagementDropdown/index.tsx
- src/views/ParticipantEntity/index.tsx
- src/views/ParticipantEntity/utils/dataFile.tsx
- src/views/ParticipantEntity/utils/diagnosis.tsx
- src/views/ParticipantEntity/utils/family.tsx
- src/views/ParticipantEntity/utils/phenotype.tsx
- src/views/ParticipantEntity/utils/profil.tsx
- src/views/ParticipantEntity/utils/summary.tsx
- closes #[601](https://d3b.atlassian.net/browse/SKFP-601)
- Create a basic template for https://d3b.atlassian.net/browse/SKFP-403
**For conversion**
Convert the Age fields that are all in days into Year + Days. Therefore the rule would be Age in days / 365.2425 to capture the years +leap year and we would round down to the nearest whole number without the decimals. The remainder of that value will represent the remaining days rounded down without decimals. 
If there is number of days are smaller than 365, only represent the values in days without indicating 0 years. 
This will only apply in the Data Exploration tables and the Entity pages of the portal. The Report API and export as TSV that generates the downloaded reports will remain in days to ensure ease of data manipulation. 
Follow …
> ✨feat(particpant): SKFP-403 add partipant entity page and readable date

- src/utils/routes.ts
- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[611](https://d3b.atlassian.net/browse/SKFP-611)
Remove clinical download data
[Bonus] Re-add study route with the futur correct URL. Used in ParticipantEntity
Before
After
> ✨feat(variant): SKFP-611 remove download data button

- src/services/api/reports/index.ts
- src/store/report/thunks.tsx
- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[609](https://d3b.atlassian.net/browse/SKFP-609)
Implement the report tied to the Export as TSV button. When a user clicks the Export as TSV button, it will download a TSV file of the table of results. This is seen in the Studies page, Data Exploration-- Participant/File tab, File Entity (Participant / Sample table), Participant Entity page (Diagnostic, Phenotype, Biospecimen table).
When specific rows are selected, the Export as TSV should generate the table that is displayed in the portal for those rows specifically
The Export as TSV should correlate with the Column Selection tool. In other words, if a user adjusts the columns he wants to see, the TSV report should correspond to the display of the table and not include the columns that are unchecked in the column selection …
> 🐛 fix(report): SKFP-609 fix tsv export

- src/views/Dashboard/components/DashboardCards/SavedFilters/EditModal/index.tsx
- src/views/DataExploration/components/SetsManagementDropdown/AddRemoveSaveSetModal.tsx
- src/views/DataExploration/components/SetsManagementDropdown/UserSetForm/index.tsx
- closes #[587](https://d3b.atlassian.net/browse/SKFP-587)
À noter que le type variant s’est ajouté à la liste depuis la création du ticket.
1. Saved filter - Modal d’édition via le Widget du Dashboard - Le bouton devrait être Save au lieu de OK (pour tous les types)
2. Saved set - Modal d’ajout/retrait via le bouton Save participant|biospecimen|file|variant set - L’étiquette devrait débuter par une lettre majuscule (pour tous les types +variant)
3. Saved set - Modal d’ajout/retrait via le bouton Save participant|biospecimen|file|variant set - Le type dans le titre devrait être au singulier (pour file et variant)
> 🐛fix(filter): SKFP-587 normalize text

- src/views/Variants/components/ConsequencesCell/index.module.scss
- src/views/Variants/components/ConsequencesCell/index.tsx
- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[617](https://d3b.atlassian.net/browse/SKFP-617)
Goal: Currently, the Consequence column cells has a set width for the column and so it causes the consequence (e.g. Frameshift variant) to wrap. It also decreases the impact icon size. 
Remove the set width for the Consequence column, and allow the table to resize based on the content of the consequence column cell. (This will surely cause the horizontal scroll to be present more frequently)
Ultimately the goal is to remove the wrap because the consequence value (e.g. frameshift variant should never be wrapped
Ensure that the impact icon size does not alter from one row to another. 
Before
After
> fix(variant): SKFP-617 fix consequence row size

- src/helpers/index.ts
- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
Remove duplicates in some columns for participants table in data-explore. This is a frontend fix because data is fine.
Conceptually we have something like: [{p1: 'a', p2: 'b'}, {p1: 'a', p2: 'd'}, {p1: 'c', p2: 'b'}] if column uses only p1 in a cell we ll have 'a', 'a' ,'c' ('a' is duplicated)
> :adhesive_bandage: : Fix duplicates in participants table

- src/graphql/participants/queries.ts
- closes #[632](https://d3b.atlassian.net/browse/SKFP-632)
files et biospecimens retourne toujours 0 dans data-exploration/participants
> 🐛fix(participant): SKFP-632 fix search participants query

- .gitignore
- src/views/DataExploration/components/TreeFacet/TreeFacetModal.tsx
- src/views/DataExploration/index.tsx
- closes [SKFP-628](https://d3b.atlassian.net/browse/SKFP-628)
- closes [SKFP-593](https://d3b.atlassian.net/browse/SKFP-593)
- Fixed querybuilder not displaying the correct results when searching from TreeFacetModal
- Fixed duplicate options in Apply button dropdown
Before:
After:
[SKFP-628]: https://d3b.atlassian.net/browse/SKFP-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKFP-593]: https://d3b.atlassian.net/browse/SKFP-593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: SKFP-628 TreeFacetModal query gives wrong results in querybuilder

- src/views/Studies/index.tsx
- closes #[638](https://d3b.atlassian.net/browse/SKFP-638)
When a user clicks on the #Participants for a given study, it redirects correctly to the Data Exploration – Participant page but it has the wrong query Pill. It should be Study code: KF-EATF and not Study Code: SD 0TYVY1TW. The Study codes starting with SD… are CHOP’s operational study codes and shouldn’t be exposed in the front-end.
> 🐛fix(study): SKFP-683 fix count redirection

- src/views/Studies/components/StudySearch/index.tsx
- src/views/Studies/index.tsx
- closes #[606](https://d3b.atlassian.net/browse/SKFP-606)
go to study page
search for a study
select a suggestion
you will see that study_id from the response is used to create a query in the querybuilder. Make sure that study_id is used instead of searchText in the querybuilder.
Ensure that the query pill has it displayed as the “Study Code”: Study Code for example. 
Before
After
> 🐛fix(study): SKFP-606 fix search query

- package-lock.json
- package.json
- src/views/DataExploration/index.tsx
- closes [SKFP-628](https://d3b.atlassian.net/browse/SKFP-628)
- Change the field used to search in the QueryBuilder from the ontology browser. (the search results must include all participants in the hierarchy, not just the ones with the exact term)
- Related to https://github.com/Ferlab-Ste-Justine/ferlab-ui/pull/238 
Before:
After:
[SKFP-628]: https://d3b.atlassian.net/browse/SKFP-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🐛fix(ontology): SKFP-628 Change field to search in query builder

- src/views/Dashboard/components/DashboardCards/DataExplorationLinks/LinkBox/index.module.scss
- src/views/Dashboard/components/DashboardCards/DataExplorationLinks/LinkBox/index.tsx
- src/views/Dashboard/components/DashboardCards/DataExplorationLinks/index.tsx
- closes #[646](https://d3b.atlassian.net/browse/SKFP-646)
Remove the redirect link and hover state for the families button. Since there is no “official” families tab in the Data Exploration page we will simply remove the redirect link. 
Before
After
https://user-images.githubusercontent.com/65532894/221651829-0be093d3-8ed5-44e5-a37f-fdb477b32f48.mp4
> 🐛fix(link): SKFP-646 remove link on family data

- package-lock.json
- package.json
- src/graphql/biospecimens/actions.ts
- src/graphql/biospecimens/queries.ts
- src/graphql/files/actions.ts
- src/graphql/files/queries.ts
- src/graphql/participants/actions.ts
- src/graphql/participants/queries.ts
- src/utils/translation.ts
- src/views/DataExploration/components/PageContent/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- src/views/DataExploration/utils/constant.ts
- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[656](https://d3b.atlassian.net/browse/SKFP-656)
Les données de data-exploration dépassent les 10 000 résultats. Le search after a donc été implémenté.
> ✨ feat(data): SFKP-656 add search after on data-exploration

- src/views/Variants/components/PageContent/VariantsTable/index.tsx
- closes #[542](https://d3b.atlassian.net/browse/SKFP-542)
As part of the new integration of Search After, we will be able to sort across the table of results despite having a large number of results. Add sort to the following columns:
participant
ALT (API need to be done)
Homo. (API need to be done)
> ✨feat(variant): SKFP-542 add sort for alt. homo. and participants

- src/views/DataExploration/components/TreeFacet/helpers.tsx
- closes #[607](https://d3b.atlassian.net/browse/SKFP-607)
Currently, the HPO/MONDO browsers do not seem to accept “/”. The search request becomes null as soon as a letter is added after inputting “/”. Aplasia/Hypoplasia of the breasts (HP:0010311) can be used an example. 
The Search input should be able to accept “/”. 
This error is seen across KF and INCLUDE
> 🪲fix(hpobrowser): SKFP-607 allow / to be searched

- src/views/VariantEntity/utils/frequencies.tsx
> :bug: BACKPORT-9 display study_code vs study_id in variant entity page

- package-lock.json
- package.json
- src/locales/en.ts
- src/views/FileEntity/BiospecimenTable/index.tsx
- src/views/ParticipantEntity/BiospecimensTable/index.tsx
- src/views/ParticipantEntity/DiagnosisTable/index.tsx
- src/views/ParticipantEntity/PhenotypeTable/index.tsx
- src/views/ParticipantEntity/SummaryHeader/index.tsx
- src/views/ParticipantEntity/index.tsx
- closes #[695](https://d3b.atlassian.net/browse/SKFP-695)
- closes #[696](https://d3b.atlassian.net/browse/SKFP-696)
Goal: Similar to the Statistic buttons that are used to redirect to the Data Exploration, we will add a button “View in data exploration” on the right side of the table title for the respective entities. The filter to the Data Exploration page will be the same as the filters in the statistic button for the respective entity. 
Participant Entity tables:
Biospecimen (query = Participant ID, tab = Biospecimens)
Data File (query = Participant ID, tab = Data Files)
File Entity tables:
Participant / Sample  (query = File ID, tab = Participants)
----
Applies to KF/INCLUDE. Already implemented in FerlabUI
Goal:  Add number of total row items per table and place it beside the …
> feat(entity): SKFP-695 SKFP-696 add tile and header extra

- src/views/DataExploration/components/TreeFacet/index.module.scss
#[BUG]
[SKFP-686](https://d3b.atlassian.net/browse/SKFP-686)
On a small screen, if you open for example the "Observed Phenotype (HPO) Browser" modal you can see the second column of selected items overlap and get out of the modal.
I share with Lucas the behavior because now we have a scrollbar on the first column but we can access to the action item in the second column. He validate this behavior.
[SKFP-686]: https://d3b.atlassian.net/browse/SKFP-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(HPO/MONDO): SKFP-686 fix overlap

- src/components/Cavatica/CreateProjectModal/index.tsx
- src/style/themes/kids-first/antd/form.less
- src/views/DataExploration/index.tsx
[SKFP-697](https://d3b.atlassian.net/browse/SKFP-697)
Fix input label color in modal form.
I have removed the `Text` element in create project modal because it's not needed to have the right style now.
[SKFP-697]: https://d3b.atlassian.net/browse/SKFP-697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(modal/form): SKFP-697-form-input-label-color

- src/views/VariantEntity/utils/summary.tsx
- src/views/VariantEntity/utils/tests/summary.test.tsx
#BUG | [Variant Entity] Afficher un tiret quand il n'y a pas de donnée
- closes [3242](https://d3b.atlassian.net/browse/SKFP-623)
Par exemple il manque un tiret pour la valeur de OMIM manquante.
@kstonge
> fix: SKFP-623 add dash for empty omin

- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.test.tsx
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- closes #SKFP-702
The sequencing experiment which contains the field experimental strategy can be a list of documents, therefore multiple experimental strategies. This occurs when a VCF file is used to represent a jointGenotyping across family members for example. However, their experimental strategies should always be the same theoretically. Therefore, we will only display 1 experimental strategy for a file in the Data Exploration ta
...
@kstonge
> fix: SKFP-702 Only display 1 experimental strategy

- src/graphql/participants/actions.ts
- src/graphql/participants/models.ts
- src/graphql/participants/queries.ts
- src/locales/en.ts
- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- src/views/ParticipantEntity/utils/getPhenotypeColumns.tsx
#[FEAT] Fix phenotype table in participant entity
- [SKFP-701](https://d3b.atlassian.net/browse/SKFP-701)
Les phenotypes non observés perdent leur nom dans la page participant entity.
Ajout de la colonne interpretation.
Fix style, largeur de colonnes.
Maquette [ici](https://www.figma.com/file/baxEfYnqjk3d87iQAPEz8S/Pages-Entit%C3%A9s?node-id=223%3A17889&mode=dev)
...
[SKFP-701]: https://d3b.atlassian.net/browse/SKFP-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(participant): SKFP-701 fix phenotypes

- src/graphql/participants/models.ts
- src/views/ParticipantEntity/PhenotypeTable/index.tsx
- src/views/ParticipantEntity/utils/getPhenotypeColumns.tsx
#[BUG] Participant entity: fix tsv to display all phenotype names
[SKFP-701](https://d3b.atlassian.net/browse/SKFP-701)
Display all phenotype names in TSV like in the table.
[SKFP-701]: https://d3b.atlassian.net/browse/SKFP-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(participant): SKFP-701 fix tsv

- src/graphql/participants/models.ts
- src/graphql/participants/queries.ts
- src/views/ParticipantEntity/utils/getPhenotypeColumns.tsx
###[FIX] Phenotype interpretation must used is_observed
[SKFP-650](https://d3b.atlassian.net/browse/SKFP-650)
Fix interpretation column in phenotype value from participant entity page to use `phenotype.is_observed`.
[SKFP-650]: https://d3b.atlassian.net/browse/SKFP-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(participant): SKFP-650 use pheno.is_observed

- src/store/report/thunks.tsx
- src/views/FileEntity/BiospecimenTable/index.tsx
- src/views/FileEntity/ExperimentalProcedure/ExperimentalProcedureTable/index.tsx
- src/views/FileEntity/utils/biospecimens.tsx
- src/views/Profile/Settings/cards/DeleteCard/index.tsx
###[BUG] Export TSV, fix name and add to file entity
[SKFP-766](https://d3b.atlassian.net/browse/SKFP-766)
- Fix export file name for kids first
- Add export button implementation in File Entity for participant/sample and experimental procedure tables
See ticket screenshot
[SKFP-766]: https://d3b.atlassian.net/browse/SKFP-766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(export): SKFP-766 fix name and add file entity exports

- src/locales/en.ts
- src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
###[BUG] Display dash in empty cells
[SKFP-688](https://d3b.atlassian.net/browse/SKFP-688)
Cells fixed : 
- Data explo => participant => sex, vital status, Observed Phenotype (HPO)
- Data explo => biospecimen => age
cell empty 
[SKFP-688]: https://d3b.atlassian.net/browse/SKFP-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(data explo): SKFP-688 dash in empty cell

- src/views/VariantEntity/index.module.scss
- src/views/VariantEntity/utils/frequencies.tsx
- src/views/VariantEntity2/index.module.scss
- src/views/VariantEntity2/utils/frequencies.tsx
[SKFP-757](https://d3b.atlassian.net/browse/SKFP-757)
Align participant cell with link compare to the other participant cells, same for total line, in variant entity and variant 2 entity.
Variant 1
Variant 2
[SKFP-757]: https://d3b.atlassian.net/browse/SKFP-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(variant): SKFP-757 align participant cell in frequency

- src/components/uiKit/FilterList/CustomFilterSelector.tsx
- src/components/uiKit/FilterList/index.tsx
- src/locales/en.ts
- src/utils/translation.ts
- src/views/Variants2/components/PageContent/VariantsTable/index.tsx
[SKFP-772](https://d3b.atlassian.net/browse/SKFP-772)
- Variant 2 facet name in sidebar menu and in query builder
- Consequence column name in result table
[SKFP-772]: https://d3b.atlassian.net/browse/SKFP-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(variant 2): SKFP-772 variant facet and column names

- src/graphql/biospecimens/models.ts
- src/locales/en.ts
- src/views/ParticipantEntity/SummaryHeader/index.module.scss
- src/views/ParticipantEntity/utils/biospecimens.tsx
Ticket [SKFP-650](https://d3b.atlassian.net/browse/SKFP-650)
- La couleur du Statistic Title dans les bouton du Summary devraient être body-2 selon le UI-Kit
- Il manque la colonne « Consent Type » du tableau Biospecimen
- L’étiquette de la pilule au redirect de Collection ID devrait être « Collection Sample ID » 
[SKFP-650]: https://d3b.atlassian.net/browse/SKFP-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(participant): SKFP-650 fix QA comments

- src/components/uiKit/reports/DownloadFileManifestModal/index.module.scss
- src/components/uiKit/reports/DownloadFileManifestModal/index.tsx
- src/locales/en.ts
[Data Exploration & Entity ] File manifest fixes
- closes #SKFP-779
remove the “In development and will be available soon”. line
Go to Data Exploration > File tab > Select some files and click on Manifest button
> fix: SKFP-779 remove sub text in file manifest modal

- src/graphql/participants/models.ts
- src/graphql/participants/queries.ts
- src/locales/en.ts
- src/views/ParticipantEntity/utils/getProfileItems.tsx
[SKFP-777](https://d3b.atlassian.net/browse/SKFP-777)
Use `outcome.vital_status `in profile table from participant entity and remove tooltip on the label.
[SKFP-777]: https://d3b.atlassian.net/browse/SKFP-777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(participant): SKFP-777 fix vital status

- src/views/Community/index.tsx
#[BUG] [Community] Le filtre ne fonctionne pas dans les pages > 1
- closes SKFP-788
When filtering members on page > 1, it results nothing
Go to Community
Go to the second page
Enter a filter in search or role or interest
You should see members that match the filter
> fix: SKFP-788 fix members filters and pagination

- src/locales/en.ts
- src/views/VariantEntity2/SummaryHeader/index.module.scss
- src/views/VariantEntity2/index.tsx
- src/views/VariantEntity2/utils/summary.tsx
#[FEATURE] Variant2 entity multiple fixes
[SKFP-783](https://d3b.atlassian.net/browse/SKFP-783)
- stat colors
- Summary / Frequency => gnomad label
- Summary / Frequency => add tooltip on label and update value
- Summary / Frequency => fix OMIM value
- Frequency subsection label
- Avec OMIM 
- Sans OMIM 
[SKFP-783]: https://d3b.atlassian.net/browse/SKFP-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(variant2): SKFP-783 multiple fixes

- src/views/Dashboard/components/DashboardCards/SavedFilters/index.module.scss
- src/views/Dashboard/components/DashboardCards/SavedSets/index.module.scss
#[BUG] [Dashboard] Ajouter un scroll dans le widget des Saved Filters et Saved Sets
- closes SKFP-786
Add scroll on saved filters and saved sets cards in dashboard
Make sure to have at least 5 saved sets and 5 saved filters
Go on dashboard
You should see scroll in Saved filters and Saved sets card
> fix: SKFP-786 add scroll on saved filters and saved sets cards in dashboard

- src/locales/en.ts
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- src/views/FileEntity/Title/index.tsx
#[BUG] [Data Exploration & Entity ] File manifest fixes
- closes SKFP-779
- Manifest button in file entity page does nothing
- Add icon download in Manifest button in file entity page and make it default
- Make cavatica button primary in file entity page
- Switch Manifest and cavatica buttons in data exploration so cavatica is the most on the right
In Data Exploration > Files tab
Cavatica button should be on the right
In File Entity Page
Manifest button should be default with download icon and should one the manifest modal for the current file
Cavatica button should be primary
> fix: SKFP-779 fix manifest button in file entity page and small ui fixes

- src/views/FileEntity/SummaryHeader/index.tsx
[SKFP-750](https://d3b.atlassian.net/browse/SKFP-750)
In file entity, summary section biospecimen stat must redirect to data explo, bio tab with the file id in the QB.
https://github.com/kids-first/kf-portal-ui/assets/133775440/9c7118b3-6c88-41c5-b45d-5fbf0c316d59
[SKFP-750]: https://d3b.atlassian.net/browse/SKFP-750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(file): SKFP-750 fix redirect biospecimen

- src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx
- src/views/DataExploration/components/UploadIds/FileUploadIds.tsx
- src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx
- src/views/DataExploration/components/UploadIds/utils.tsx
[SKFP-801](https://d3b.atlassian.net/browse/SKFP-801)
Biospecimen upload ids need to work and add the ids list to QB.
No filter added before in the QB.
https://github.com/kids-first/kf-portal-ui/assets/133775440/feed18e3-9796-4655-a3a8-66fc391d71f8
[SKFP-801]: https://d3b.atlassian.net/browse/SKFP-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dataexplo): SKFP-801 fix bio upload ids

- src/services/api/reports/index.ts
#[BUG] [Manifest] withFamily param is not passed to the backend
closes SKFP-779
Description
withFamily param is not passed to the backend
QA
Select a file and check the checkbox to include family datas and download the manifest
> fix: SKFP-779 withFamily param is not passed to the backend

- src/views/Variants/index.tsx
[SKFP-808](https://d3b.atlassian.net/browse/SKFP-808)
In variants exploration, variants facets : remove upload ids.
[SKFP-808]: https://d3b.atlassian.net/browse/SKFP-808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(variantexplo): SKFP-808 remove upload ids

- src/views/DataExploration/components/PageContent/tabs/Biospecimens/index.tsx
[SKFP-810](https://d3b.atlassian.net/browse/SKFP-810)
[SKFP-810]: https://d3b.atlassian.net/browse/SKFP-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dataexplo): SKFP-810 remove sample id link

- src/views/VariantEntity/FerlabComponent/EntityGeneConsequenceSubtitle.tsx
[SKFP-804](https://d3b.atlassian.net/browse/SKFP-804)
If the value is 0 it's the real value, we want to display it. If the value is not defined we received null/undefined.
spliceAi value 0
gnomad pli value 0
We don't have an example for gnomad loeuf with 0 value.
[SKFP-804]: https://d3b.atlassian.net/browse/SKFP-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(variant): SKFP-804 fix protein coding display

- src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.tsx
[SKFP-799](https://d3b.atlassian.net/browse/SKFP-799)
Move the legend so that it is no longer above the graph.
[SKFP-799]: https://d3b.atlassian.net/browse/SKFP-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(graph): SKFP-799 studies graph legend

- src/views/Variants/components/PageContent/VariantsTable/index.module.scss
#BUG | remove double tooltip on safari
- closes https://d3b.atlassian.net/browse/SKFP-756
no double tooltip on safari
> fix: skfp-756 correction double tooltip safari

- src/locales/en.json
- src/locales/en.ts
[SKFP-825](https://d3b.atlassian.net/browse/SKFP-825)
[SKFP-825]: https://d3b.atlassian.net/browse/SKFP-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(variants): SKFP-825 typo tooltip

- src/components/OutcomesAgeCells/index.tsx
- src/graphql/participants/queries.ts
- src/locales/en.ts
- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- src/views/ParticipantEntity/utils/getProfileItems.tsx
At the moment of this PR, you can test at `/participants/PT_PPB4K1PJ`
> :typo: Add cell in profile table in pt entity page

- src/components/uiKit/FilterList/CustomFilterContainer.tsx
- src/components/uiKit/FilterList/index.tsx
- src/views/Studies/components/SideBarFacet/index.tsx
- src/views/Studies/index.tsx
#[FEATURE] Remove apply and clear button in filters
[SKFP-767](https://d3b.atlassian.net/browse/SKFP-767)
Remove buttons in the facets to(CLEAR, Apply). As soon as there is a value that is selected, it will automatically be added to the query builder.
[SKFP-767]: https://d3b.atlassian.net/browse/SKFP-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(studies): SKFP-767 filter without footer

- package-lock.json
- package.json
- src/views/DataExploration/components/PageContent/index.tsx
- src/views/VariantEntity/FerlabComponent/EntityGeneConsequence.tsx
- src/views/VariantEntity/FerlabComponent/Pathogenecity.utils.tsx
- src/views/VariantEntity/utils/consequences.tsx
- src/views/VariantEntity/utils/summary.tsx
- src/views/Variants/components/PageContent/index.tsx
- closes #[850](https://d3b.atlassian.net/browse/SKFP-850)
> Salut! Dans le tableau du Variant Exploration, on ne veut pas afficher “NO GENE”. On va simplement retirer le “NO GENE” mais garder le restant de l’information qu’on a dans la cellule du Most Deleterious Consequence (ex. le point gris “intergenic”)
> 
> ![image](https://github.com/kids-first/kf-portal-ui/assets/65532894/13710ebc-4568-46aa-8b3b-20e173f90c17)
> 
> Dans la page Variant entity section Consequence:
> 
> Si dans le tableau Gene Consequence, la seule conséquence est “intergenic”, afficher le message “No data available” comme c’est fait les autres sections comme Pathogenicity.
> 
> Si dans le tableau Gene Consequence, il y a une conséquence “intergenic” et d’autres conséquence autre que “intergenic”, simplement pas …
> fix(variant): SKFP-850 fix NO_GENE case

- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
#[BUG] Files export TSV is missing platform column
[SKFP-815](https://d3b.atlassian.net/browse/SKFP-815)
When I export files data with platform column I want to see it in the TSV export file.
Column not displayed
[SKFP-815]: https://d3b.atlassian.net/browse/SKFP-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(files): SKFP-815 export TSV with platform col

- src/views/VariantEntity/SummaryHeader/index.tsx
#[BUG] Query pill dropdown not working (error 500)
[SKFP-855](https://d3b.atlassian.net/browse/SKFP-855)
When we are redirect to data exploration from variant entity by the studies link, the value filter generated produce a 500 error on value click to display the dropdown.
https://github.com/kids-first/kf-portal-ui/assets/133775440/0cd7c8d6-e777-4c0f-b56c-6589d69357d6
https://github.com/kids-first/kf-portal-ui/assets/133775440/d34d29c7-ed87-4562-8bd4-daa20ad3a855
[SKFP-855]: https://d3b.atlassian.net/browse/SKFP-855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(query): SKFP-855 fix redirect from variant

- src/style/themes/kids-first/antd/tags.less
[SKFP-911](https://d3b.atlassian.net/browse/SKFP-911)
- The link text color within tags should not change.
https://github.com/kids-first/kf-portal-ui/assets/133775440/190f4058-d65e-4980-8389-ba848f28752e
https://github.com/kids-first/kf-portal-ui/assets/133775440/2cfb0f91-dba5-4ca1-955e-c33cc1f1109c
[SKFP-911]: https://d3b.atlassian.net/browse/SKFP-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(tag): SKFP-911 color link on hover

- package-lock.json
- package.json
- src/store/fences/slice.ts
[SKFP-918](https://d3b.atlassian.net/browse/SKFP-918)
- incorrect stats count in study item. We want (authorized_controlled_files_count + total_uncontrolled_files_count) of total_files_count
- Number of study items in the header sticks after fence disconnection. To reproduce, connect with success to a fence, make sure a number is displayed in the header, disconnect the fence, the list of item will empty itself but the count will remain.
- Wording between header and list cut sometimes.
Small screen
Small screen
Big screen
[SKFP-918]: https://d3b.atlassian.net/browse/SKFP-918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(widget): SKFP-918 auth studies style and count

- src/views/Variants/components/PageContent/VariantsTable/index.tsx
[SKFP-917](https://d3b.atlassian.net/browse/SKFP-917)
- Use `internal_frequencies.total.pf` instead of `af`
[SKFP-917]: https://d3b.atlassian.net/browse/SKFP-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(variants): SKFP-917 part frequency

- src/services/initUsersnap.ts
[SKFP-914](https://d3b.atlassian.net/browse/SKFP-914)
- if usersnap widget is not loaded the portal must open like in chrome.
[SKFP-914]: https://d3b.atlassian.net/browse/SKFP-914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(usersnap): SKFP-914 usersnap not loaded

- src/views/Variants/components/PageContent/VariantsTable/index.tsx
[SKFP-936](https://d3b.atlassian.net/browse/SKFP-936)
- display CADD phred instead of CADD raw in CADD column
[SKFP-936]: https://d3b.atlassian.net/browse/SKFP-936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(variants): SKFP-936 CADD value

- package-lock.json
- package.json
- src/components/Cavatica/AnalyzeButton/index.tsx
- src/components/utils/NotificationContextHolder/index.tsx
- src/graphql/files/queries.ts
- src/graphql/utils/helpers.test.ts
- src/graphql/utils/helpers.ts
- src/locales/en.ts
- src/store/passport/thunks.test.ts
- src/store/passport/thunks.ts
- src/utils/helper.test.ts
- src/utils/helper.ts
#[BUG | FEATURE | DOC] [TITLE]
- closes #[895](https://d3b.atlassian.net/browse/SKFP-895)
- closes #[934](https://d3b.atlassian.net/browse/SKFP-934)
I added more metadata when CavaticaBulkImport is triggered.
> Feat/skfp 934/cavatica bulk import

- src/store/user/slice.ts
- src/store/user/thunks.ts
[SKFP-915](https://d3b.atlassian.net/browse/SKFP-915)
- When a user changes columns config he wants it's saved for an other visit.
See video in ticket.
https://github.com/kids-first/kf-portal-ui/assets/133775440/3e86471d-0450-4396-be6e-f10adcb42aa7
[SKFP-915]: https://d3b.atlassian.net/browse/SKFP-915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(user): SKFP-915 user config lost

- src/graphql/biospecimens/queries.ts
- src/graphql/participants/queries.ts
- src/locales/en.ts
- src/views/DataExploration/components/BiospecimenSearch.tsx
- src/views/DataExploration/components/FileSearch.tsx
- src/views/DataExploration/components/ParticipantSearch.tsx
- src/views/DataExploration/components/UploadIds/BiospecimenUploadIds.tsx
- src/views/DataExploration/components/UploadIds/FileUploadIds.tsx
- src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx
- closes [SKFP-894](https://d3b.atlassian.net/browse/SKFP-894)
[JIRA LINK](https://d3b.atlassian.net/browse/SKFP-894)
Data Exploration (Participant)
Data Exploration (BioSpecimen)
[SKFP-894]: https://d3b.atlassian.net/browse/SKFP-894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: SKFP-894 add posibility to search by external ids in Data Exploration

- src/views/Studies/components/PageContent/index.tsx
- src/views/Studies/index.tsx
- src/views/Studies/utils/constant.ts
- closes [#SKFP-927](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-927)
Goal: add the sort funcitonality on the following fields in the study page table of results:
- Study code
- Study Name
- dbGaP
- Participants
- Families
- Biospecimens
> feat(studies): SKFP-927 Add sort to fields in Study Page

- src/components/Cavatica/AnalyzeButton/index.tsx
- src/components/Layout/Header/index.tsx
- src/components/uiKit/FilterList/CustomFilterContainer.tsx
- src/components/uiKit/search/GlobalSearch/Search/SearchAutocomplete/index.tsx
- src/components/uiKit/search/GlobalSearch/index.tsx
- src/provider/KeycloakProvider.tsx
- src/services/analytics.ts
- src/services/api/reports/index.ts
- src/store/report/thunks.tsx
- src/views/Dashboard/components/DashboardCards/AuthorizedStudies/index.tsx
- src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx
- src/views/Dashboard/components/DashboardCards/SavedSets/ListItem/index.tsx
- src/views/DataExploration/components/PageContent/index.tsx
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- src/views/DataExploration/components/SetsManagementDropdown/AddRemoveSaveSetModal.tsx
- src/views/DataExploration/components/SetsManagementDropdown/index.tsx
- src/views/FileEntity/Title/index.tsx
- src/views/Persona/index.tsx
- closes [#SKFP-734](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-734)
> feat: SKFP-734 Add tags to Google Analytics 4

- src/components/Cavatica/AnalyzeButton/index.tsx
- src/store/passport/metadata.ts
- src/store/passport/thunks.test.ts
- src/store/passport/thunks.ts
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- closes #[956](https://d3b.atlassian.net/browse/SKFP-956)
Lors du bulk import, il faudrait utiliser le même sorter que dans le tableau où on à fait selectAll quand on fetch les ids de fichiers. Car vue que plusieurs requêtes sont envoyé, on n’est pas sûr de recevoir les données dans le même ordre
> feat(cavatica): SKFP-956 add sorter when starting cavatica analyse

- package-lock.json
- package.json
- src/locales/en.ts
- src/views/VariantEntity2/index.module.scss
- src/views/VariantEntity2/index.tsx
- src/views/VariantEntity2/utils/consequence.tsx
[SKFP-901](https://d3b.atlassian.net/browse/SKFP-901)
- Add consequence section
No data available 
Not expanded
Expanded
[SKFP-901]: https://d3b.atlassian.net/browse/SKFP-901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(variant): SKFP-901 add consequence section

- src/graphql/participants/queries.ts
- src/locales/en.ts
- src/views/DataExploration/components/ParticipantSearch.tsx
- src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx
- closes [#SKFP-965](https://d3b.atlassian.net/jira/software/c/projects/SKFP/boards/82?selectedIssue=SKFP-965)
> feat: SKFP-965 add search by Family ID in Participant Data Exploration

- src/views/VariantEntity2/utils/consequence.tsx
[SKFP-995](https://d3b.atlassian.net/browse/SKFP-995)
- Variant has multiple refseq, display them with see more component
[SKFP-995]: https://d3b.atlassian.net/browse/SKFP-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(variant): SKFP-995 update refSeq display

- src/store/fences/selector.ts
- closes #[993](https://d3b.atlassian.net/browse/SKFP-993)
- Aller sur le dashboard
- Se connecter aux authorized studies
- Accéder a une étude via authorized widget
- Toutes les files sont lock alors qu'il devrait être unlock
> fix(files): SKFP-993 fix acls fetching for files authrorization

- package-lock.json
- package.json
- closes [#SKFP-964](https://d3b.atlassian.net/browse/SKFP-964)
Weird bug in Safari only. Cant reproduce in Local since i'm not able to run mock auth studies with Safari.
> fix: SKFP-964 prevent double title in safari

- src/views/Dashboard/components/DashboardCards/index.tsx
#BUG 
- closes #[975](https://d3b.atlassian.net/browse/SKFP-975)
Il n’est plus possible de déplacer le widget Authorized Studies
https://github.com/kids-first/kf-portal-ui/assets/65532894/048dd7fe-815f-48e9-ae10-655ac472a6f1
> fix(dashbard): SKFP-975 fix draggable card issue

- src/views/VariantEntity/utils/consequence.tsx
- closes #[974](https://d3b.atlassian.net/browse/SKFP-974)
Update the field Prediction to make it plural → Predictions in the Consequence section of the Variant Entity page when the gene is expanded
> fix(variant): SKFP-975 fix typo

- src/locales/en.ts
- src/views/VariantEntity/index.module.scss
- src/views/VariantEntity/utils/summary.tsx
[SKFP-1013](https://d3b.atlassian.net/browse/SKFP-1013)
- If no ensembl_transcript_id remove the link
- If symbol = NO_GENE remove link and display “No gene”
- If NO_GENE remove - for aa_change
[SKFP-1013]: https://d3b.atlassian.net/browse/SKFP-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(variant): SKFP-1013 no gene display in banner

- src/views/DataExploration/components/PageContent/tabs/Summary/AgeAtDiagnosisGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/DataCategoryGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/DataTypeGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/DemographicGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/StudiesGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/SunburstGraphCard/GraphContent/index.tsx
#BUG | FEATURE | DOC] [TITLE]
- closes #[3242](https://d3b.atlassian.net/browse/SKFP-1016)
t seems like the No data does not scale for certain charts (Participant by Data Category and Participants by sample type). It should be centered like the other charts.
> fix(summary): SKFP-1016 fix padding empty

- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
[SKFP-942](https://d3b.atlassian.net/browse/SKFP-942)
- remove sort on PedcBioPortal, Not Observed Phenotype (HPO) and Observed Phenotype (Source Text)
[SKFP-942]: https://d3b.atlassian.net/browse/SKFP-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(data explo): SKFP-942 remove sort

- src/locales/en.ts
- src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx
- src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
- closes [#SKFP-1021](https://d3b.atlassian.net/browse/SKFP-1021)
After:
> fix: SKFP-1021 add extra whitespace before support email in saved filters

- package-lock.json
- package.json
- src/locales/en.ts
- src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentDiagnosisGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentPhenotypesGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/utils/grid.tsx
[SKFP-1026](https://d3b.atlassian.net/browse/SKFP-1026)
- Add Most Frequent Phenotypes and Diagnosis graphs
[SKFP-1026]: https://d3b.atlassian.net/browse/SKFP-1026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(summary): SKFP-1026 add hpo and mondo graphs

- package-lock.json
- package.json
- src/locales/en.ts
- src/style/themes/kids-first/antd/descriptions.less
- src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx
- src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
[SKFP-971](https://d3b.atlassian.net/browse/SKFP-971)
- back after set or filter redirect => use link instead of a element.
From info popover
https://github.com/kids-first/kf-portal-ui/assets/133775440/e218aed3-7e04-4e88-9cd9-565ba4adad61
From empty tab
https://github.com/kids-first/kf-portal-ui/assets/133775440/304e2d40-805a-4aa3-a17e-c4babce6ac8e
[SKFP-971]: https://d3b.atlassian.net/browse/SKFP-971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dashboard): SKFP-971 fix return after redirect

- src/views/DataExploration/components/PageContent/tabs/Summary/MostFrequentDiagnosisGraphCard/index.tsx
- closes [#SKFP-1072](https://d3b.atlassian.net/browse/SKFP-1072)
> fix: SKFP-1072 remove trismoy 21 exclusions from data exploration graphs

- src/views/DataExploration/components/UploadIds/ParticipantUploadIds.tsx
- closes [#SKFP-1099](https://d3b.atlassian.net/browse/SKFP-1099)
[![image](https://github.com/kids-first/kf-portal-ui/assets/156684667/6900817b-f3ac-4fec-8df7-2fbf73d48a67)
> fix: skfp-1099 prevent crash from upload list when families_id is null

- cypress/e2e/Consultation/TableauBiospecimens.cy.ts
- cypress/e2e/Consultation/TableauFiles.cy.ts
- cypress/e2e/Consultation/TableauParticipants.cy.ts
- cypress/e2e/Consultation/TableauStudies.cy.ts
- cypress/e2e/Facettes/PageDataExploration.cy.ts
- cypress/e2e/Requetes/ActionsSur0Requete.cy.ts
- cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts
- cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts
- cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts
- cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts
- closes #SKFP-1145
[SKFP-1145](https://d3b.atlassian.net/browse/SKFP-1145)
[SKFP-1145]: https://d3b.atlassian.net/browse/SKFP-1145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: SKFP-1145 Adjust Cypress tests from last ETL execution

- src/graphql/participants/queries.ts
- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- src/views/ParticipantEntity/utils/summary.tsx
- src/views/Studies/utils/helper.ts
- closes #[1154](https://d3b.atlassian.net/browse/SKFP-1154)
Goal: CHOP noticed that certain pedcbioportal links in the Data Exploration – Participant tab and Participant Entity page are not redirecting to a valid participant. It seems like the rule that was provided to us was not accurate and need to be refined to the following. 
Recently we updated part of the rule in SKFP-1087: [Data Exploration] Update the study code to pedcbio StudyID mapping
TERMINÉ(E)
which is still valid. But we will further refine what was done to limit the display of the pedcbioportal link to the following query:
[Data Type = Somatic Simple Nucleotide Variations OR Raw Gene Fusions OR Gene Expression Quantification OR Somatic Copy Number Variations
AND proband=true]
> feat(pedcbioportal): SKFP-1154 add new pedcbioportal rules

- src/views/Studies/utils/helper.ts
- closes #[1154](https://d3b.atlassian.net/browse/SKFP-1154)
Le mapping de l'étude KF-NBL pour le studyId dans le URL devrait maintenant être studyId=x01_fy16_nbl_maris au lieu de studyId=openpedcan_v15
> Feat/skfp 1154/pedcbioportal rules

- src/style/themes/kids-first/main.css
- closes https://d3b.atlassian.net/browse/SKFP-1219
https://d3b.atlassian.net/browse/SKFP-1219
> fix: SKFP-1219 apply correct colors for empty icon

- src/store/report/thunks.tsx
- src/views/ParticipantEntity/BiospecimenTable/index.tsx
- src/views/ParticipantEntity/utils/biospecimens.tsx
- closes #[TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-1207)
1. Afficher un double-tiret dans le fichier tsv s’il n’y a pas de données
2. Les données ne sont pas affichées dans le fichier tsv
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-1207)
> fix(participant): SKFP-1207 fix biospecimens tsv export

- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- closes [#TICKET_NUMBER](https://d3b.atlassian.net/browse/SKFP-809)
Il manque les colonnes suivantes pour le tableau des participants.
Not Observed Phenotype (HPO)
Observed Phenotype (Source Text)
[[JIRA LINK]](https://d3b.atlassian.net/browse/SKFP-809)
> fix(exploration): SKFP-809 add missing fields in tsv

- package-lock.json
- package.json
- src/components/uiKit/FilterList/CustomFilterContainer.tsx
- src/graphql/files/models.ts
- src/graphql/files/queries.ts
- src/locales/en.ts
- src/services/api/user/models.ts
- src/store/passport/thunks.test.ts
- src/utils/translation.ts
- src/views/DataExploration/components/PageContent/tabs/DataFiles/ColumnSelectorHeader/index.module.css
- src/views/DataExploration/components/PageContent/tabs/DataFiles/ColumnSelectorHeader/index.tsx
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.test.tsx
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- src/views/DataExploration/index.tsx
- closes [#SKFP-1246](https://d3b.atlassian.net/browse/SKFP-1246)
> feat: SKFP-1246 add system for data imaging column preset

- src/locales/en.ts
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.module.css
- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
- closes [#SKFP-1313](https://d3b.atlassian.net/browse/SKFP-1313)
> feat: SKFP-1313 adjust authorization icon and flow for controlled Imaging files governed by the Cavatica DRS

- src/views/DataExploration/components/PageContent/tabs/DataFiles/index.tsx
[SKFP-1315](https://d3b.atlassian.net/browse/SKFP-1315)
- display empty placeholder
[SKFP-1315]: https://d3b.atlassian.net/browse/SKFP-1315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(data files): SKFP-1315 add empty placeholder

- src/graphql/queries.ts
[SKFP-1314](https://d3b.atlassian.net/browse/SKFP-1314)
- Be able to open magnetic field strength facet
[SKFP-1314]: https://d3b.atlassian.net/browse/SKFP-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(data explo): SKFP-1314 add double type to render facet

- src/locales/en.ts
[SKFP-1269](https://d3b.atlassian.net/browse/SKFP-1269)
- update link
[SKFP-1269]: https://d3b.atlassian.net/browse/SKFP-1269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(cavatica): SKFP-1269 change data access link

- src/locales/en.ts
[SKFP-1147](https://d3b.atlassian.net/browse/SKFP-1147)
- Upercase members on no result message
[SKFP-1147]: https://d3b.atlassian.net/browse/SKFP-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(community): SKFP-1147 fix typo

- src/components/uiKit/search/GlobalSearch/utils.tsx
- src/store/fences/thunks.ts
- src/store/passport/thunks.ts
[SKFP-1360](https://d3b.atlassian.net/browse/SKFP-1360)
Sentry error [error 1](https://ferlab.sentry.io/issues/5985548184/?project=4507736947687424&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=5) [error 2](https://ferlab.sentry.io/issues/5709610671/?project=4507736947687424&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=7) [error 3](https://ferlab.sentry.io/issues/5709567963/?project=4507736947687424&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=6)
**Before**
https://github.com/user-attachments/assets/07527cb8-a2b8-46bb-9d5b-d78218dd6137
**After** …
> fix(sentry): SKFP-1360 fix empty value in highlight search

- src/views/DataExploration/index.tsx
- src/views/DataExploration/utils/quickFilter.tsx
- Closes SKFP-1362
Il semble que le compte affiché n’est pas celui des participants. L’icône dans le Quick Filter devrait donc refléter la bonne catégorie de données.
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1362)
> fix(quickfilter): SKFP-1362 map icon to facet

- src/views/DataExploration/components/PageContent/tabs/Summary/DataCategoryGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/DataTypeGraphCard/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Summary/SampleType/index.tsx
- Closes SKFP-1376
Across all horizontal bar charts set the max bars to 10. This is meant to improve visibility of the charts as it can become difficult to read the entries if there are too many bars. Generally, users will use these graphs to get a high level overview and not specifically look for those smaller bars. 
- [JIRA](https://d3b.atlassian.net/browse/SKFP-1376)
> feat(summary): SKFP-1376 limit horizontal chart bar to 10

- src/views/Variants/components/PageContent/VariantsTable/index.tsx
[SKFP-1390](https://d3b.atlassian.net/browse/SKFP-1390)
Open limit modal on select all if needed
No modal
[SKFP-1390]: https://d3b.atlassian.net/browse/SKFP-1390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(variants): SKFP-1390 add condition in TSV export

- package-lock.json
- package.json
- src/components/Icons/index.tsx
- src/components/Layout/Header/index.tsx
- src/components/PublicLayout/Header/index.tsx
- src/components/uiKit/reports/DownloadClinicalDataDropdown.tsx
- src/components/uiKit/reports/DownloadFileManifestModal/index.tsx
- src/components/uiKit/reports/DownloadRequestAccessModal/index.tsx
- src/locales/en.ts
- src/views/Dashboard/components/DashboardCards/SavedFilters/EditModal/index.tsx
- src/views/Dashboard/components/DashboardCards/SavedFilters/index.tsx
- src/views/Dashboard/components/DashboardCards/SavedSets/CreateEditModal/index.tsx
- src/views/Dashboard/components/DashboardCards/SavedSets/index.tsx
- src/views/DataExploration/components/PageContent/index.tsx
- src/views/DataExploration/components/PageContent/tabs/Participants/index.tsx
- src/views/DataExploration/utils/quickFilter.tsx
- src/views/FakeStorybook/index.tsx
- src/views/LandingPage/CollaboratorSection/index.tsx
- src/views/LandingPage/StudiesSection/Carousel/Card/index.tsx
[SKFP-1379](https://d3b.atlassian.net/browse/SKFP-1379)
Sentry error on undefined object
Javascript errors fixed
[SKFP-1379]: https://d3b.atlassian.net/browse/SKFP-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(sentry): SKFP-1379 sentry and JS errors

- src/components/uiKit/search/GlobalSearch/Search/index.tsx
[SKFP-1487](https://d3b.atlassian.net/browse/SKFP-1487)
Sentru error
Add check if data returned by arranger is defined.
https://github.com/user-attachments/assets/e50de077-e167-4906-a08f-9defee08b134
[SKFP-1487]: https://d3b.atlassian.net/browse/SKFP-1487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(search): SKFP-1487 add check option data not defined

- cypress/e2e/Consultation/PageVariant_1.cy.ts
- src/locales/en.ts
- src/views/VariantEntity/utils/consequence.tsx
Currently, we only have the picked symbol on the gene with the most deleterious consequence, but we should also have the symbol for the most deleterious consequence itself (the one that is the highlight at the top of the page). 
https://d3b.atlassian.net/browse/SKFP-979
> SKFP-979 Add picked symbol to associated consequence/transcript

- cypress/e2e/Consultation/PageVariant_2.cy.ts
- src/views/VariantEntity/utils/summary.tsx
- src/views/VariantSomaticEntity/utils/summary.tsx
- Closes SJFP-1464
Update the hyperlink on the ensembl button in the variant entity page. Currently it redirects to the transcript ensembl url but we want it to redirect to the gene ensembl url. 
- [JIRA](https://d3b.atlassian.net/browse/SJFP-1464)
> feat(variant): SKFP-1464 update gene href

- package-lock.json
- package.json
- Closes SKFP-1524
Issue: Currently, when we hover on the Set Definitions in the Set Operations Analytics app, we get the set id which is not useful for the user. 
The correct behaviour is to see the same information in the set definition and see the full saved set name in the tooltip
- [JIRA](https://ferlab-crsj.atlassian.net/browse/SKFP-1524)
> fix(venn): SKFP-1524 fix an issue where the wrong tooltips was displayed
